T = {
# booking widget
"Book Your Transfer": "Rezervirajte transfer",
"Your Trip": "Vaša vožnja",
"Edit": "Uredi",
"Route": "Ruta",
"Split Airport → Split": "Zračna luka Split → Split",
"Trip type": "Vrsta vožnje",
"One way": "U jednom smjeru",
"Outbound": "Polazak",
"Return": "Povratna",
"Passengers": "Putnici",
"One Way": "U jednom smjeru",
"5% discount on return transfers": "5% popusta na povratne transfere",
"Pickup": "Polazište",
"Split Airport, hotel, address, marina...": "Zračna luka Split, hotel, adresa, marina...",
"Swap pickup and dropoff": "Zamijeni polazište i odredište",
"Dropoff": "Odredište",
"Hotel, address, marina, city...": "Hotel, adresa, marina, grad...",
"Pickup and dropoff can't be the same address.": "Polazište i odredište ne mogu biti ista adresa.",
"Trip Details": "Detalji vožnje",
"Date": "Datum",
"Time": "Vrijeme",
"Select time": "Odaberi",
"Return Date": "Datum povratka",
"Return Time": "Vrijeme povratka",
"Choose your vehicle": "Odaberite vozilo",
"Sedan": "Limuzina",
"Škoda Superb or similar": "Škoda Superb ili slično",
"Up to 4 pax": "Do 4 putnika",
"Business Van": "Poslovni kombi",
"Mercedes-Benz V-Class": "Mercedes-Benz V-Class",
"Up to 7 pax": "Do 7 putnika",
"Van": "Kombi",
"Renault Trafic or similar": "Renault Trafic ili slično",
"Up to 8 pax": "Do 8 putnika",
"Enter your pickup and dropoff to see your fixed price.": "Upišite polazište i odredište i odmah vidite fiksnu cijenu.",
"Calculating your price…": "Računamo cijenu…",
"Can't find your destination? Contact us on": "Ne možete pronaći odredište? Javite nam se na",
"WhatsApp": "WhatsApp",
"or": "ili",
"email": "e-mail",
"for a personalised quote.": "za ponudu po mjeri.",
"Your Details": "Vaši podaci",
"Full Name": "Ime i prezime",
"Email": "E-mail",
"Phone": "Telefon",
"Add luggage, flight number or a note": "Dodajte prtljagu, broj leta ili napomenu",
"Suitcases (optional)": "Broj kofera (neobavezno)",
"Flight Number (optional)": "Broj leta (neobavezno)",
"e.g. OU491": "npr. OU491",
"Notes (optional)": "Napomena (neobavezno)",
"Child seats, exact pickup address, special requests...": "Dječje sjedalice, točna adresa preuzimanja, posebni zahtjevi...",
"By booking, you agree to our": "Rezervacijom prihvaćate",
"Privacy Policy": "Pravila privatnosti",
"Book Now": "Rezerviraj",
"Booking request sent": "Zahtjev za rezervaciju je poslan",
"Thank you! We've received your transfer request. Your driver's confirmation will be sent to your email shortly before pickup.": "Hvala! Primili smo vaš zahtjev za transfer. Potvrdu s podacima vozača poslat ćemo vam e-mailom prije preuzimanja.",
"Booking reference": "Broj rezervacije",
"Vehicle": "Vozilo",
"Total": "Ukupno",
"Chat on WhatsApp": "Pišite nam na WhatsApp",
"Also visiting Plitvice Lakes or Krka National Park? We run private day trips too.": "Idete li i na Plitvička jezera ili u NP Krka? Vozimo i privatne jednodnevne izlete.",
"See Our Day Trips →": "Pogledajte izlete →",
"Need to change anything?": "Trebate nešto promijeniti?",
"Contact us anytime.": "Javite nam se bilo kada.",
"Price Summary": "Pregled cijene",
"Enter a pickup and dropoff address to see your fixed price and trip details here.": "Upišite polazište i odredište i ovdje ćete vidjeti fiksnu cijenu i detalje vožnje.",
"Sedan, Škoda Superb": "Limuzina, Škoda Superb",
"Fixed price, all-inclusive. No hidden fees, no taximeter.": "Fiksna cijena, sve uključeno. Bez skrivenih troškova, bez taksimetra.",

# homepage
"Split Airport Transfers | Airport Split Transfer": "Taxi Split aerodrom po fiksnoj cijeni | Airport Split Transfer",
"Fixed-price Split Airport transfers. Book a private transfer from Split Airport instead of a Split Airport taxi: meet & greet, flight tracking, 5% off returns.": "Privatni transfer i taxi sa Zračne luke Split po fiksnoj cijeni: doček s imenom na tabli, praćenje leta i 5% popusta na povratnu vožnju.",
"Airport Split Transfer": "Airport Split Transfer",
"Split-Dalmatia County, Croatia": "Splitsko-dalmatinska županija, Hrvatska",
"Fiona Maher": "Fiona Maher",
"Ivan was so friendly and helpful. We were travelling with our little 9 month old and he really helped us and made sure all was ok. Gave us great recommendations too! Nicest journey we have had as it is tough with a baby, really made it easy for us getting back to airport and fitting all our luggage.": "Ivan was so friendly and helpful. We were travelling with our little 9 month old and he really helped us and made sure all was ok. Gave us great recommendations too! Nicest journey we have had as it is tough with a baby, really made it easy for us getting back to airport and fitting all our luggage.",
"Ben Huffman": "Ben Huffman",
"Ivan is an excellent driver and I would highly recommend him for your driving needs. He is safe, intuitive, friendly, helpful. His car is clean, smoke free, and he was early for pick up time.": "Ivan is an excellent driver and I would highly recommend him for your driving needs. He is safe, intuitive, friendly, helpful. His car is clean, smoke free, and he was early for pick up time.",
"Chaneze B.": "Chaneze B.",
"I recommend, we were late for our plane and he helped us a lot! Nice drive and kind man. Thank you.": "I recommend, we were late for our plane and he helped us a lot! Nice drive and kind man. Thank you.",
"How much does a private transfer from Split Airport cost?": "Koliko košta privatni transfer sa Zračne luke Split?",
"The exact price depends on your pickup and drop-off address and the vehicle you choose. Enter your details in the booking form above for an instant, fixed price: tolls, fuel and meet-and-greet at arrivals are always included, with no hidden fees.": "Točna cijena ovisi o adresi polazišta i odredišta te o vozilu koje odaberete. Upišite podatke u obrazac za rezervaciju iznad i odmah dobivate fiksnu cijenu: cestarina, gorivo i doček u dolaznom terminalu uvijek su uključeni, bez skrivenih troškova.",
"Which destinations do you cover from Split Airport?": "Do kojih odredišta vozite sa Zračne luke Split?",
"We run private, fixed-price transfers from Split Airport to Split, Trogir, Omiš, Makarska, Šibenik, Zadar, Dubrovnik, Plitvice Lakes and every other major town and village along the Dalmatian coast.": "Vozimo privatne transfere po fiksnoj cijeni sa Zračne luke Split do Splita, Trogira, Omiša, Makarske, Šibenika, Zadra, Dubrovnika, Plitvičkih jezera i svih većih mjesta duž dalmatinske obale.",
"What happens if my flight is delayed?": "Što ako moj let kasni?",
"We monitor your flight number in real time, so your driver adjusts the pickup automatically. There is no extra charge for reasonable delays.": "Pratimo vaš let u stvarnom vremenu pa vozač sam prilagodi vrijeme preuzimanja. Za uobičajena kašnjenja ne naplaćujemo ništa dodatno.",
"Can I book a return transfer?": "Mogu li rezervirati povratni transfer?",
"Yes, select \"Return\" when booking to schedule both legs of your trip together, with a 5% discount on the total price.": "Da, pri rezervaciji odaberite \"Povratna\" i dogovorite obje vožnje odjednom, uz 5% popusta na ukupnu cijenu.",
"What vehicles can I choose from?": "Koja vozila mogu odabrati?",
"A Škoda Superb sedan (1–4 passengers), a Mercedes-Benz V-Class (1–7 passengers) or a Renault Trafic van (1–8 passengers), all at a fixed price per vehicle.": "Limuzinu Škoda Superb (1–4 putnika), Mercedes-Benz V-Class (1–7 putnika) ili kombi Renault Trafic (1–8 putnika), sve po fiksnoj cijeni po vozilu.",
"Are child seats available?": "Imate li dječje sjedalice?",
"Yes, child seats are provided free of charge on request, just mention it when booking.": "Da, dječje sjedalice su besplatne na zahtjev, samo to navedite pri rezervaciji.",
"How do I pay for my transfer?": "Kako se plaća transfer?",
"We accept both card and cash. The price is agreed and confirmed before you travel, so there are no surprises on the day.": "Primamo kartice i gotovinu. Cijena je dogovorena i potvrđena prije vožnje, tako da na dan vožnje nema iznenađenja.",
"Home": "Početna",
"Popular Destinations": "Popularna odredišta",
"Hotels": "Hoteli",
"Day Trips": "Izleti",
"Vehicles": "Vozila",
"Services": "Usluge",
"Blog": "Blog",
"About": "O nama",
"Contact": "Kontakt",
"EN": "HR",
"English": "English",
"Deutsch": "Deutsch",
"Svenska": "Svenska",
"Norsk": "Norsk",
"Open menu": "Otvori izbornik",
"Close menu": "Zatvori izbornik",
"×": "×",
"Booking": "Rezervacija",
"Routes": "Rute",
"Hotel Transfers": "Transferi do hotela",
"About Us": "O nama",
"Language": "Jezik",
"DE": "DE",
"SV": "SV",
"NO": "NO",
"Split Airport Transfers": "Taxi i transfer sa Zračne luke Split",
"Fixed-price private transfers from Split Airport across the Dalmatian coast.": "Privatni transferi sa Zračne luke Split po fiksnoj cijeni, duž cijele dalmatinske obale.",
"33+ Google Reviews": "33+ Google recenzija",
"Licensed Taxi": "Licencirani taxi prijevoz",
"Fixed Prices": "Fiksne cijene",
"Card & Cash": "Kartica i gotovina",
"Free Child Seats": "Besplatne dječje sjedalice",
"Prefer to chat?": "Radije biste pisali?",
"WhatsApp us": "Javite se na WhatsApp",
"Popular Routes": "Popularne rute",
"Where We Take You": "Kamo vozimo",
"View All Routes →": "Sve rute →",
"Split City Center / Ferry Port": "Split centar / trajektna luka",
"Podstrana": "Podstrana",
"Omiš": "Omiš",
"Makarska": "Makarska",
"Dubrovnik": "Dubrovnik",
"Plitvice Lakes": "Plitvička jezera",
"Zadar": "Zadar",
"Brela": "Brela",
"Our Vehicles": "Naša vozila",
"Three Vehicles, One Standard": "Tri vozila, isti standard",
"View All Vehicles →": "Sva vozila →",
"White Škoda Superb sedan used for private Split Airport transfers": "Bijela limuzina Škoda Superb za privatne transfere sa Zračne luke Split",
"White · Executive Sedan": "Bijela · poslovna limuzina",
"AC": "Klima",
"Black Mercedes-Benz V-Class van used for group airport transfers from Split": "Crni Mercedes-Benz V-Class za grupne transfere sa splitskog aerodroma",
"Black · Premium Van": "Crni · premium kombi",
"White Renault Trafic minibus used for larger group transfers from Split": "Bijeli kombi Renault Trafic za veće grupe iz Splita",
"White · Group Transfer": "Bijeli · grupni transfer",
"Clean & comfortable vehicles": "Čista i udobna vozila",
"AC in all vehicles": "Klima u svim vozilima",
"Plenty of luggage space": "Puno mjesta za prtljagu",
"Baby seats on request": "Sjedalice za bebe na zahtjev",
"Non smoking": "Nepušačka vozila",
"60 min": "60 min",
"Free Waiting at the Airport": "Besplatnog čekanja na aerodromu",
"Live": "Uživo",
"Flight Tracking": "Praćenje leta",
"Free": "Besplatno",
"Cancellation": "Otkazivanje",
"Straight to your hotel door": "Ravno do vrata hotela",
"Fixed-price transfers to the resorts and hotels guests ask for most.": "Transferi po fiksnoj cijeni do hotela i resorta koje gosti najčešće traže.",
"Amadria Park Šibenik (Solaris)": "Amadria Park Šibenik (Solaris)",
"Hotel Le Meridien Lav": "Hotel Le Meridien Lav",
"Radisson Blu Resort Split": "Radisson Blu Resort Split",
"Medora Auri, Podgora": "Medora Auri, Podgora",
"All hotel transfers →": "Svi transferi do hotela →",
"How It Works": "Kako funkcionira",
"From Booking to Arrival": "Od rezervacije do dolaska",
"Request Your Transfer": "Zatražite transfer",
"Enter your flight details, destination and passenger count: see the fixed price instantly, no obligation.": "Upišite podatke o letu, odredište i broj putnika i odmah vidite fiksnu cijenu, bez obveze.",
"Booking Request Received": "Primamo zahtjev",
"We'll confirm your transfer by email with pickup details.": "Transfer vam potvrđujemo e-mailom, s detaljima preuzimanja.",
"We Track Your Flight": "Pratimo vaš let",
"Live flight monitoring means your driver adjusts pickup time automatically if your flight is delayed.": "Let pratimo uživo pa vozač sam pomakne vrijeme preuzimanja ako let kasni.",
"Meet Your Driver": "Upoznajte vozača",
"Your driver waits at arrivals with a name board. Luggage assistance and a direct route to your address.": "Vozač vas čeka u dolaznom terminalu s vašim imenom na tabli, pomaže s prtljagom i vozi izravno do vaše adrese.",
"Testimonials": "Recenzije",
"What Our Customers Say": "Što kažu naši gosti",
"based on 33+ Google reviews": "na temelju 33+ Google recenzija",
"Read our Google reviews →": "Pročitajte Google recenzije →",
"“Ivan was so friendly and helpful. We were travelling with our little 9 month old and he really helped us and made sure all was ok. Gave us great recommendations too!”": "„Ivan je bio jako ljubazan i susretljiv. Putovali smo s bebom od 9 mjeseci, puno nam je pomogao i pazio da sve bude u redu. Dao nam je i odlične preporuke!”",
"Fiona Maher, Google review": "Fiona Maher, Google recenzija (prijevod)",
"“Ivan is an excellent driver and I would highly recommend him for your driving needs. He is safe, intuitive, friendly, helpful. His car is clean, smoke free, and he was early for pick up time.”": "„Ivan je izvrstan vozač i toplo ga preporučujem. Vozi sigurno, snalažljiv je, ljubazan i spreman pomoći. Auto mu je čist, bez mirisa dima, a na preuzimanje je stigao i ranije.”",
"Ben Huffman, Google review": "Ben Huffman, Google recenzija (prijevod)",
"“I recommend, we were late for our plane and he helped us a lot! Nice drive and kind man. Thank you.”": "„Preporučujem, kasnili smo na avion i puno nam je pomogao! Ugodna vožnja i drag čovjek. Hvala.”",
"Chaneze B., Google review": "Chaneze B., Google recenzija (prijevod)",
"FAQ": "Česta pitanja",
"Common Questions": "Česta pitanja",
"Need help or a custom offer?": "Trebate pomoć ili ponudu po mjeri?",
"Contact us on WhatsApp. We reply in minutes!": "Javite nam se na WhatsApp. Odgovaramo u nekoliko minuta!",
"See fixed prices": "Pogledaj fiksne cijene",
"Private transfers and tours across Croatia. Your journey, our priority.": "Privatni transferi i izleti diljem Hrvatske. Vaše putovanje, naša briga.",
"Instagram": "Instagram",
"TikTok": "TikTok",
"Google": "Google",
"Location": "Lokacija",
"Quick Links": "Brzi linkovi",
"Split Airport Taxi": "Taxi Split aerodrom",
"Split Airport → Split City Center / Ferry Port": "Zračna luka Split → Split centar / trajektna luka",
"Split Airport → Podstrana": "Zračna luka Split → Podstrana",
"Split Airport → Omiš": "Zračna luka Split → Omiš",
"Split Airport → Makarska": "Zračna luka Split → Makarska",
"Split Airport → Brela": "Zračna luka Split → Brela",
"All routes": "Sve rute",
"Split, Croatia": "Split, Hrvatska",
"© 2026 Airport Split Transfer. All rights reserved.": "© 2026 Airport Split Transfer. Sva prava pridržana.",
"Terms & Conditions": "Uvjeti poslovanja",
"Cookie Preferences": "Postavke kolačića",
}
