T = {
# split-airport-transfers
"Split Airport Taxi at a Fixed Price | Airport Split Transfer": "Taxi Zračna luka Split, cijene bez taksimetra | Airport Split Transfer",
"Private Split Airport taxi at a fixed price, no meter. English-speaking drivers, flight tracking and 24/7 pickups to Split, Trogir, Omiš, Makarska and more.": "Privatni taxi sa Zračne luke Split po fiksnoj cijeni, bez taksimetra. Praćenje leta i vožnje 0-24 do Splita, Trogira, Omiša, Makarske i dalje.",
"Airport Taxi": "Taxi aerodrom",
"How much does a taxi from Split Airport cost?": "Koliko košta taxi sa Zračne luke Split?",
"The exact price depends on your pickup and drop-off address and the vehicle you choose. Enter your details in our booking form for an instant, fixed price: tolls, fuel and meet-and-greet at arrivals are always included, with no hidden fees.": "Točna cijena ovisi o adresi polazišta i odredišta te o vozilu koje odaberete. Upišite podatke u obrazac za rezervaciju i odmah dobivate fiksnu cijenu: cestarina, gorivo i doček u dolaznom terminalu uvijek su uključeni, bez skrivenih troškova.",
"How long does it take to get from Split Airport to Split city center?": "Koliko traje vožnja od Zračne luke Split do centra Splita?",
"The drive from Split Airport to Split city center takes about 20–25 minutes under normal traffic conditions.": "Vožnja od Zračne luke Split do centra Splita traje oko 20 do 25 minuta u normalnom prometu.",
"Do you offer transfers to Trogir, Omiš, Makarska and other coastal towns?": "Vozite li i do Trogira, Omiša, Makarske i drugih mjesta na obali?",
"Yes. We run private, fixed-price transfers from Split Airport to Trogir, Omiš, Makarska, Šibenik, Zadar, Novalja and every other major town along the Dalmatian coast.": "Da. Vozimo privatne transfere po fiksnoj cijeni sa Zračne luke Split do Trogira, Omiša, Makarske, Šibenika, Zadra, Novalje i svih većih mjesta duž dalmatinske obale.",
"Is the price really fixed, with no hidden fees?": "Je li cijena stvarno fiksna, bez skrivenih troškova?",
"Yes. The price is agreed before you travel, based on the vehicle class rather than a taximeter, and already includes tolls, fuel and meet-and-greet at arrivals.": "Da. Cijena se dogovara prije vožnje, prema vrsti vozila, a ne prema taksimetru, i već uključuje cestarinu, gorivo i doček u dolaznom terminalu.",
"Can I book a return transfer from my hotel to Split Airport?": "Mogu li rezervirati i povratak od hotela do Zračne luke Split?",
"Yes, select \"Return\" when booking to schedule both legs of your trip together. 5% discount on return transfers.": "Da, pri rezervaciji odaberite \"Povratna\" i dogovorite obje vožnje odjednom. Na povratne transfere dobivate 5% popusta.",
"What vehicles are available for Split Airport transfers?": "Koja su vozila dostupna za transfere sa Zračne luke Split?",
"We offer a Škoda Superb sedan (1–4 passengers), a Mercedes-Benz V-Class (1–7 passengers) and a Renault Trafic van (1–8 passengers), all at a fixed price per vehicle.": "Nudimo limuzinu Škoda Superb (1–4 putnika), Mercedes-Benz V-Class (1–7 putnika) i kombi Renault Trafic (1–8 putnika), sve po fiksnoj cijeni po vozilu.",
"How do I book a Split Airport taxi online?": "Kako online rezervirati taxi sa Zračne luke Split?",
"Enter your pickup and drop-off address, choose your date, time and vehicle in the booking form on this page, and you'll see an instant fixed price, no account or deposit required to reserve.": "U obrazac na ovoj stranici upišite polazište i odredište, odaberite datum, vrijeme i vozilo i odmah ćete vidjeti fiksnu cijenu. Za rezervaciju ne trebate račun ni polog.",
"Hrvatski": "Hrvatski",
"HR": "HR",
"Private Airport Taxi": "Privatni taxi s aerodroma",
"Fixed-price private taxi from Split Airport to Split, Trogir, Omiš, Makarska and the whole Dalmatian coast: English-speaking drivers, flight tracking and 24/7 service.": "Privatni taxi sa Zračne luke Split po fiksnoj cijeni do Splita, Trogira, Omiša, Makarske i cijele dalmatinske obale: praćenje leta i usluga 0-24.",
"Why Choose Us": "Zašto mi",
"Split Airport Taxi Done Right": "Taxi s aerodroma kako treba",
"No meter, no hidden costs": "Bez taksimetra i skrivenih troškova",
"Pickup adjusts to delays": "Preuzimanje se prilagođava kašnjenju",
"24/7 Service": "Usluga 0-24",
"Every flight, day or night": "Svaki let, danju i noću",
"Free Cancellation": "Besplatno otkazivanje",
"Plans change, no penalty": "Planovi se mijenjaju, bez penala",
"Split Airport Taxi To Every Coastal Town": "Taxi s aerodroma do svakog mjesta na obali",
"Split": "Split",
"Trogir": "Trogir",
"Šibenik": "Šibenik",
"Novalja": "Novalja",
"Three Vehicles, One Fixed Price": "Tri vozila, jedna fiksna cijena",
"Meter-free and fixed in advance: ideal for solo travellers or couples who want a quick, quiet ride straight to their address.": "Bez taksimetra, cijena unaprijed dogovorena: idealno za samce i parove koji žele brzu i mirnu vožnju ravno do adrese.",
"Select Vehicle": "Odaberi vozilo",
"Extra legroom and leather seating for families or small groups who want a private-driver feel without the higher cost of a chauffeur service.": "Više mjesta za noge i kožna sjedala za obitelji i manje grupe koje žele osjećaj privatnog vozača bez cijene limuzinskog servisa.",
"The practical pick for wedding parties, sports teams and larger groups, plenty of room for people and bags in one taxi.": "Praktičan izbor za svatove, sportske ekipe i veće grupe, s puno mjesta za ljude i prtljagu u jednom vozilu.",
"View All Vehicles": "Sva vozila",
"“Great experience. Arrived ahead of time and charged a fair price to the airport. Plenty of space in the car for our luggage and got to the airport in time.”": "„Odlično iskustvo. Stigao je ranije i naplatio poštenu cijenu do aerodroma. Puno mjesta u autu za prtljagu i na aerodrom smo stigli na vrijeme.”",
"Karen Holland, Google Local Guide": "Karen Holland, Google Local Guide (prijevod)",
"“First class service, reliable, friendly, quick and affordable. Professional and quick drive taking care about the traffic and about passengers.”": "„Prvoklasna usluga, pouzdano, ljubazno, brzo i povoljno. Profesionalna i brza vožnja, uz brigu o prometu i o putnicima.”",
"Nikola Stosic, Google review": "Nikola Stosic, Google recenzija (prijevod)",
"“Excellent transfer service: the driver was professional, friendly and punctual, and the journey was smooth and comfortable. Communication was great throughout.”": "„Izvrstan transfer: vozač je bio profesionalan, ljubazan i točan, a vožnja ugodna i udobna. Komunikacija je cijelo vrijeme bila odlična.”",
"Zacker Zap, Google review": "Zacker Zap, Google recenzija (prijevod)",
"Split Airport Taxi: Common Questions": "Taxi Zračna luka Split: česta pitanja",
"Enter your pickup and drop-off address, choose your date, time and vehicle in the booking form below, and you'll see an instant fixed price, no account or deposit required to reserve.": "U obrazac ispod upišite polazište i odredište, odaberite datum, vrijeme i vozilo i odmah ćete vidjeti fiksnu cijenu. Za rezervaciju ne trebate račun ni polog.",
"Book Your Fixed-Price Split Airport Taxi": "Rezervirajte taxi s aerodroma po fiksnoj cijeni",
"Enter your route below for an instant quote: no hidden fees, no obligation.": "Upišite rutu i odmah dobivate cijenu: bez skrivenih troškova i bez obveze.",
"Split Airport → Šibenik": "Zračna luka Split → Šibenik",
"Split Airport → Zadar": "Zračna luka Split → Zadar",

# destinations
"Split Airport Transfers: All Destinations | Airport Split Transfer": "Transferi sa Zračne luke Split: sva odredišta | Airport Split Transfer",
"Browse every destination served by Airport Split Transfer from Split Airport, with fixed prices, distances and travel times.": "Sva odredišta do kojih vozimo sa Zračne luke Split, s fiksnim cijenama, udaljenostima i trajanjem vožnje.",
"Destinations": "Odredišta",
"How many destinations do you serve from Split Airport?": "Do koliko odredišta vozite sa Zračne luke Split?",
"Dozens: from Split itself to Dubrovnik and Plitvice Lakes National Park, plus smaller coastal villages and marinas. Use the search box above to find yours.": "Desetke: od samog Splita do Dubrovnika i Nacionalnog parka Plitvička jezera, uz manja mjesta na obali i marine. Svoje odredište pronađite u tražilici iznad.",
"Is the price the same in both directions?": "Je li cijena ista u oba smjera?",
"Yes. Each destination card above links to both directions, \"From Airport\" and \"To Airport\", priced the same way, based on the exact pickup and drop-off address.": "Da. Svaka kartica iznad vodi na oba smjera, \"S aerodroma\" i \"Na aerodrom\", a cijena se računa jednako, prema točnoj adresi polazišta i odredišta.",
"My destination isn't listed, can I still book a transfer?": "Mog odredišta nema na popisu, mogu li ipak rezervirati?",
"Yes. We cover most of the Dalmatian coast beyond what's listed here, contact us with your address for a quote.": "Da. Vozimo i do većine mjesta na dalmatinskoj obali kojih ovdje nema, pošaljite nam adresu i dobit ćete ponudu.",
"How is the exact price calculated?": "Kako se računa točna cijena?",
"The price is computed instantly from your precise pickup and drop-off address and chosen vehicle, enter the details in the booking form on the homepage for a fixed quote.": "Cijena se računa odmah, prema točnoj adresi polazišta i odredišta i odabranom vozilu. Upišite podatke u obrazac na početnoj stranici i dobit ćete fiksnu cijenu.",
"Can I search for my destination on this page?": "Mogu li na ovoj stranici potražiti svoje odredište?",
"Yes, type a town name into the search box above the destination cards to filter the list instantly.": "Da, upišite ime mjesta u tražilicu iznad kartica i popis će se odmah suziti.",
"Transfers Across the Dalmatian Coast": "Transferi duž dalmatinske obale",
"Fixed, all-inclusive one-way prices from Split Airport to every major destination on the coast. Select a destination for distance, travel time and answers to common questions.": "Fiksne cijene u jednom smjeru, sve uključeno, sa Zračne luke Split do svih većih odredišta na obali. Odaberite odredište za udaljenost, trajanje vožnje i odgovore na česta pitanja.",
"Search a destination…": "Potražite odredište…",
"No destinations match your search.": "Nijedno odredište ne odgovara pretrazi.",
"From Airport": "S aerodroma",
"To Airport": "Na aerodrom",
"Baška Voda": "Baška Voda",
"Vodice": "Vodice",
"Primošten": "Primošten",
"Kaštela": "Kaštela",
"More of the Coast": "Još obale",
"Smaller Villages & Marinas": "Manja mjesta i marine",
"Quieter coastal spots, sailing bases and hamlets along the same routes: every one a private, fixed-price transfer from Split Airport.": "Mirnija mjesta na obali, charter baze i zaseoci na istim rutama: do svakog privatni transfer sa Zračne luke Split po fiksnoj cijeni.",
"Rogoznica": "Rogoznica",
"Ražanj": "Ražanj",
"Grebaštica": "Grebaštica",
"Vinišće": "Vinišće",
"Seget Donji": "Seget Donji",
"Pisak": "Pisak",
"Marušići": "Marušići",
"Promajna": "Promajna",
"Tučepi": "Tučepi",
"Živogošće": "Živogošće",
"Podgora": "Podgora",
"Murter": "Murter",
"Biograd na Moru": "Biograd na Moru",
"ACI Marina Split": "ACI Marina Split",
"ACI Marina Trogir": "ACI Marina Trogir",
"Marina Baotić": "Marina Baotić",
"Marina Kaštela": "Marina Kaštela",
"Marina Agana": "Marina Agana",
"Marina Mandalina": "Marina Mandalina",
"Marina Dalmacija": "Marina Dalmacija",
"Marina Frapa": "Marina Frapa",
"Marina Kornati": "Marina Kornati",
"My destination isn't listed: can I still book a transfer?": "Mog odredišta nema na popisu: mogu li ipak rezervirati?",

# fleet
"Our Fleet: Škoda Superb, V-Class, Trafic | Airport Split Transfer": "Vozila: Škoda Superb, V-Class, Trafic | Airport Split Transfer",
"Explore the Airport Split Transfer fleet: Škoda Superb executive sedan, Mercedes-Benz V-Class premium van, and Renault Trafic for groups.": "Naša vozila: poslovna limuzina Škoda Superb, premium kombi Mercedes-Benz V-Class i Renault Trafic za grupe.",
"Fleet": "Vozila",
"What's the difference between the Sedan, Business Van and Van?": "Koja je razlika između limuzine, poslovnog kombija i kombija?",
"The Sedan (Škoda Superb) suits 1–4 passengers, the Business Van (Mercedes-Benz V-Class) suits 1–7 with a more premium interior, and the Van (Renault Trafic) suits 1–8 for larger groups. All three include air conditioning and a professional driver.": "Limuzina (Škoda Superb) je za 1–4 putnika, poslovni kombi (Mercedes-Benz V-Class) za 1–7 putnika uz luksuzniju unutrašnjost, a kombi (Renault Trafic) za 1–8 putnika i veće grupe. Sva tri imaju klimu i profesionalnog vozača.",
"How much luggage fits in each vehicle?": "Koliko prtljage stane u koje vozilo?",
"The Sedan comfortably fits 3 large suitcases, the Business Van 7, and the Van 8, plenty of room for carry-on bags and beach gear as well.": "U limuzinu udobno stanu 3 velika kofera, u poslovni kombi 7, a u kombi 8, uz dovoljno mjesta i za ručnu prtljagu i opremu za plažu.",
"Can I choose a specific vehicle when I book?": "Mogu li pri rezervaciji odabrati određeno vozilo?",
"Yes, select your preferred vehicle directly on this page or in the booking form, and the price updates instantly.": "Da, odaberite vozilo na ovoj stranici ili u obrascu za rezervaciju i cijena će se odmah osvježiti.",
"Are child seats available in all vehicles?": "Ima li dječjih sjedalica u svim vozilima?",
"Yes, child seats are available free of charge on request in any of the three vehicles.": "Da, dječje sjedalice su besplatne na zahtjev u sva tri vozila.",
"Are the prices shown on this page final?": "Jesu li cijene na ovoj stranici konačne?",
"They're sample \"from\" prices for common routes. The exact price depends on your precise pickup and drop-off address: enter your details in the booking form for an instant, fixed quote.": "To su okvirne cijene \"od\" za česte rute. Točna cijena ovisi o adresi polazišta i odredišta: upišite podatke u obrazac za rezervaciju i odmah dobivate fiksnu cijenu.",
"Is the Van suitable for a group with a lot of luggage?": "Je li kombi dobar za grupu s puno prtljage?",
"Yes, the Renault Trafic is built for larger groups such as wedding parties and families, with plenty of space for luggage alongside 8 passengers.": "Da, Renault Trafic je napravljen za veće grupe poput svatova i obitelji, s puno mjesta za prtljagu uz 8 putnika.",
"The Fleet": "Vozila",
"Vehicles for Every Journey": "Vozila za svako putovanje",
"Three vehicle classes, one standard of service. Every car and van is late-model, cleaned between every transfer and driven by a licensed professional chauffeur.": "Tri klase vozila, isti standard usluge. Sva su vozila novijeg godišta, čiste se nakon svake vožnje, a vozi ih licencirani profesionalni vozač.",
"Our vehicles": "Naša vozila",
"An elegant sedan for solo travellers, couples and business trips: quiet, comfortable and quick through traffic.": "Elegantna limuzina za samce, parove i poslovna putovanja: tiha, udobna i brza kroz promet.",
"Sample route": "Primjer rute",
"From": "Od",
"Select Sedan": "Odaberi limuzinu",
"The flagship of the fleet: leather seating, cabin space and a private-driver feel for families and small groups.": "Najbolje vozilo u ponudi: kožna sjedala, puno prostora i osjećaj privatnog vozača za obitelji i manje grupe.",
"Select Business Van": "Odaberi poslovni kombi",
"Built for groups: wedding parties, teams and larger families travelling together with plenty of luggage.": "Napravljen za grupe: svatove, ekipe i veće obitelji koje putuju zajedno s puno prtljage.",
"Select Van": "Odaberi kombi",

# services
"Services: Airport, Direct and Group Transfers | Airport Split Transfer": "Usluge: aerodromski, izravni i grupni transferi | Airport Split Transfer",
"Private airport transfers, point-to-point rides, return trips, group and wedding transfers, and hourly hire across the Dalmatian coast.": "Privatni transferi s aerodroma, izravne vožnje između mjesta, povratne vožnje, grupni transferi i svatovi te najam vozila s vozačem po satu duž dalmatinske obale.",
"What transfer services do you offer besides airport pickups?": "Koje usluge nudite osim preuzimanja na aerodromu?",
"Airport arrivals and departures, point-to-point transfers between towns, return transfers, group and wedding transfers, and hourly or full-day vehicle hire.": "Dolaske i odlaske s aerodroma, izravne transfere između mjesta, povratne transfere, grupne transfere i svatove te najam vozila s vozačem na sat ili cijeli dan.",
"Do you offer transfers between two towns that don't involve the airport?": "Vozite li i između dva mjesta, bez aerodroma?",
"Yes, direct point-to-point transfers are available between any two towns along the coast, such as Split to Makarska or Šibenik to Zadar.": "Da, vozimo izravno između bilo koja dva mjesta na obali, na primjer Split–Makarska ili Šibenik–Zadar.",
"Is there a discount for booking a return transfer?": "Ima li popusta za povratni transfer?",
"Yes, return transfers booked together receive a 5% discount on the total price.": "Da, za povratne transfere rezervirane zajedno dobivate 5% popusta na ukupnu cijenu.",
"Can you arrange transport for a wedding or large group?": "Možete li organizirati prijevoz za svatove ili veću grupu?",
"Yes, we can combine the Renault Trafic van with multiple Mercedes-Benz V-Class vehicles to move wedding parties, teams or larger families together.": "Da, kombiniramo kombi Renault Trafic s više vozila Mercedes-Benz V-Class kako bi svatovi, ekipe ili veće obitelji putovali zajedno.",
"Do you offer hourly or full-day hire for touring?": "Može li se vozilo s vozačem unajmiti na sat ili cijeli dan?",
"Yes, a vehicle and driver can be booked at your disposal for touring, business itineraries or multi-stop day trips. Contact us for a custom quote.": "Da, vozilo s vozačem može biti vama na raspolaganju za razgledavanje, poslovne obaveze ili izlete s više stajanja. Javite nam se za ponudu.",
"How far in advance should I book?": "Koliko unaprijed trebam rezervirati?",
"Standard transfers can be booked instantly online, any time. For group, wedding or custom itineraries, contact us a few days ahead so we can arrange the right vehicles.": "Obični transferi mogu se rezervirati online odmah, u bilo koje doba. Za grupe, svatove ili posebne planove javite nam se nekoliko dana ranije da osiguramo prava vozila.",
"Private Transfer Services": "Usluge privatnog prijevoza",
"From a single airport pickup to multi-day itineraries, every service is built around a private vehicle, a fixed price and a professional driver.": "Od jednog preuzimanja na aerodromu do višednevnih planova, svaka usluga uključuje privatno vozilo, fiksnu cijenu i profesionalnog vozača.",
"Airport Arrivals": "Dolasci na aerodrom",
"Your driver tracks your flight and waits at arrivals with a name board, ready to help with luggage from the terminal to the car.": "Vozač prati vaš let i čeka vas u dolaznom terminalu s imenom na tabli te pomaže s prtljagom od terminala do auta.",
"Airport Departures": "Odlasci na aerodrom",
"Scheduled pickup from your address timed to your flight, with a buffer built in for check-in and security.": "Preuzimanje na vašoj adresi prema vremenu leta, uz dovoljno vremena za prijavu na let i sigurnosnu kontrolu.",
"Point-to-Point Transfers": "Izravni transferi",
"Direct transfers between towns along the coast: Split to Makarska, Šibenik to Zadar, or any route in between.": "Izravne vožnje između mjesta na obali: Split–Makarska, Šibenik–Zadar ili bilo koja ruta između.",
"Return Transfers": "Povratni transferi",
"Book both legs of your trip together, with your return pickup pre-scheduled. 5% discount on return transfers, no surprises.": "Rezervirajte obje vožnje odjednom, s unaprijed dogovorenim povratkom. 5% popusta na povratne transfere, bez iznenađenja.",
"Group & Wedding Transfers": "Grupni transferi i svatovi",
"The Renault Trafic and multiple V-Class vehicles can be combined for wedding parties, teams and larger groups travelling together.": "Renault Trafic i više vozila V-Class mogu se kombinirati za svatove, ekipe i veće grupe koje putuju zajedno.",
"Hourly & Full-Day Hire": "Najam na sat ili cijeli dan",
"A vehicle and driver at your disposal for touring, business itineraries or multi-stop day trips, contact us for a custom quote.": "Vozilo s vozačem vama na raspolaganju za razgledavanje, poslovne obaveze ili izlete s više stajanja, javite nam se za ponudu.",
"Who we drive": "Koga vozimo",
"Transfers made for how you travel": "Transferi prilagođeni vašem putovanju",
"Families with kids": "Obitelji s djecom",
"Free child seats, room for pushchairs and no shared stops after a long flight.": "Besplatne dječje sjedalice, mjesto za kolica i bez usputnih stajanja nakon dugog leta.",
"Groups and events": "Grupe i događaji",
"One van for up to 8 people and their bags, several vehicles for bigger groups.": "Jedan kombi za do 8 osoba s prtljagom, više vozila za veće grupe.",
"Cruise and ferry passengers": "Putnici s kruzera i trajekta",
"From Split port to the airport or your hotel, with the meeting point agreed before the day.": "Od luke Split do aerodroma ili hotela, uz mjesto susreta dogovoreno unaprijed.",
"Business travellers": "Poslovni putnici",
"Company invoice on request, a fixed price agreed in advance and flight tracking for every pickup.": "R1 račun na firmu, fiksna cijena dogovorena unaprijed i praćenje leta kod svakog preuzimanja.",
"No hidden costs": "Bez skrivenih troškova",
"Door to Door Service": "Od vrata do vrata",
"We take you to your address": "Vozimo vas do vaše adrese",
"Local & Reliable": "Lokalni i pouzdani",
"Based in Split": "Iz Splita i Kaštela",
"Years of Experience": "Godine iskustva",
"Local knowledge of every route": "Poznajemo svaku rutu",
"Safe & Insured": "Sigurno i osigurano",
"Your safety is our priority": "Vaša sigurnost nam je na prvom mjestu",
"Ready to Book?": "Spremni za rezervaciju?",

# about
"About Us | Airport Split Transfer": "O nama | Airport Split Transfer",
"Airport Split Transfer operates private, fixed-price airport transfers between Split Airport and destinations across the Dalmatian coast.": "Airport Split Transfer vozi privatne transfere po fiksnoj cijeni između Zračne luke Split i odredišta duž dalmatinske obale.",
"Who operates Airport Split Transfer?": "Tko stoji iza Airport Split Transfera?",
"Airport Split Transfer is operated by De Niro, obrt za prijevoz, a licensed private transport business based in Kaštela, next to Split Airport.": "Airport Split Transfer vodi De Niro, obrt za prijevoz, licencirani prijevoznik sa sjedištem u Kaštelima.",
"Are your drivers licensed and insured?": "Jesu li vaši vozači licencirani i osigurani?",
"Yes. Every driver is a licensed professional, and all vehicles are fully insured.": "Da. Svaki vozač je licencirani profesionalac, a sva su vozila potpuno osigurana.",
"Is this a shared shuttle or a private vehicle?": "Je li to zajednički shuttle ili privatno vozilo?",
"Every transfer is a single private vehicle booked for your party only, never a shared shuttle with other passengers.": "Svaki transfer je privatno vozilo samo za vas i vaše društvo, nikad zajednički shuttle s drugim putnicima.",
"What languages do your drivers speak?": "Koje jezike govore vaši vozači?",
"All drivers speak English, in addition to Croatian.": "Svi vozači uz hrvatski govore i engleski.",
"Do you only operate airport transfers?": "Vozite li samo aerodromske transfere?",
"No. Alongside Split Airport transfers, we also run point-to-point transfers between towns, private day trips, and hourly or full-day vehicle hire, see our Services page for details.": "Ne. Uz transfere sa Zračne luke Split vozimo i izravno između mjesta, privatne jednodnevne izlete, a vozilo s vozačem može se unajmiti i na sat ili cijeli dan. Više na stranici Usluge.",
"Which areas do you cover?": "Koja područja pokrivate?",
"We cover the Dalmatian coast from Split itself all the way to Dubrovnik, including Trogir, Omiš, Makarska, Šibenik, Zadar and Plitvice Lakes National Park.": "Pokrivamo dalmatinsku obalu od Splita sve do Dubrovnika, uključujući Trogir, Omiš, Makarsku, Šibenik, Zadar i Nacionalni park Plitvička jezera.",
"A Private Transfer, Done Properly": "Privatni transfer, kako treba",
"Airport Split Transfer was built around a simple idea: the first and last hour of a trip should feel as good as the rest of it.": "Airport Split Transfer nastao je iz jednostavne ideje: prvi i zadnji sat putovanja trebaju biti jednako ugodni kao i ostatak puta.",
"We operate private, fixed-price transfers between Split Airport and destinations across the Dalmatian coast: from the old town of Split itself to Dubrovnik, three and a half hours south. Every transfer is a single private vehicle for your party, not a shared shuttle.": "Vozimo privatne transfere po fiksnoj cijeni između Zračne luke Split i odredišta duž dalmatinske obale: od splitske stare jezgre do Dubrovnika, tri i pol sata južnije. Svaki transfer je privatno vozilo samo za vas, a ne zajednički shuttle.",
"Our drivers are licensed professionals who know the coast road, the ferry timetables and the fastest way around Split's old town traffic. Every flight is tracked in real time, so a delay on your end never means a missed pickup on ours.": "Naši vozači su licencirani profesionalci koji poznaju jadransku magistralu, red vožnje trajekata i najbrži put kroz splitske gužve. Svaki let pratimo u stvarnom vremenu pa kašnjenje leta nikad ne znači propušteno preuzimanje.",
"The fleet is maintained to a consistent standard across all three vehicle classes, the Škoda Superb, the Mercedes-Benz V-Class and the Renault Trafic, so the level of care is the same whether you are travelling alone or with a group of eight.": "Sva tri vozila, Škoda Superb, Mercedes-Benz V-Class i Renault Trafic, održavamo po istom standardu, tako da je razina brige ista putujete li sami ili u grupi od osmero.",
"Availability": "Dostupnost",
"Fixed": "Fiksna",
"Upfront Pricing": "Cijena unaprijed",
"Dalmatian Destinations": "Odredišta u Dalmaciji",
"No. Alongside Split Airport transfers, we also run point-to-point transfers between towns, private day trips, and hourly or full-day vehicle hire, see our": "Ne. Uz transfere sa Zračne luke Split vozimo i izravno između mjesta, privatne jednodnevne izlete, a vozilo s vozačem može se unajmiti i na sat ili cijeli dan. Više na stranici",
"page for details.": ".",

# contact
"Contact Us | Airport Split Transfer": "Kontakt | Airport Split Transfer",
"Contact Airport Split Transfer for airport transfers, group bookings and custom itineraries across Split and the Dalmatian coast.": "Javite se Airport Split Transferu za aerodromske transfere, grupne rezervacije i posebne planove u Splitu i duž dalmatinske obale.",
"How quickly will I get a reply?": "Koliko brzo odgovarate?",
"We reply within a few minutes during the day, and within the hour overnight.": "Danju odgovaramo unutar nekoliko minuta, a noću unutar sat vremena.",
"What's the fastest way to reach you?": "Kako vas najbrže mogu dobiti?",
"WhatsApp usually gets the quickest response. You can also call, email, or use the form on this page.": "Najbrže odgovaramo na WhatsApp. Možete i nazvati, poslati e-mail ili ispuniti obrazac na ovoj stranici.",
"Can I request a custom quote or itinerary through this form?": "Mogu li preko ovog obrasca zatražiti posebnu ponudu?",
"Yes, group bookings, wedding transfers and custom multi-stop itineraries can all be arranged this way. For a standard one-way or return transfer, the instant booking form on the homepage is faster.": "Da, ovako se mogu dogovoriti grupne rezervacije, svatovi i vožnje s više stajanja. Za običan transfer u jednom smjeru ili povratni brži je obrazac za rezervaciju na početnoj stranici.",
"Do you have a walk-in office I can visit?": "Imate li ured koji mogu posjetiti?",
"We're based in Split and Kaštela and handle bookings directly by phone, WhatsApp and email rather than a walk-in office, this keeps us available 24/7 wherever you are.": "Nalazimo se u Splitu i Kaštelima, a rezervacije primamo izravno telefonom, WhatsAppom i e-mailom, bez ureda za stranke. Tako smo dostupni 0-24 gdje god bili.",
"What should I include in my message?": "Što trebam napisati u poruci?",
"Your route, travel dates, passenger count and flight number (if relevant) help us reply with an accurate answer straight away.": "Ruta, datumi putovanja, broj putnika i broj leta (ako je relevantno) pomažu nam da odmah odgovorimo točno.",
"Get in Touch": "Javite nam se",
"Questions about a route, a group booking or a custom itinerary? Reach us directly, any time.": "Imate pitanje o ruti, grupnoj rezervaciji ili posebnom planu? Javite nam se izravno, u bilo koje doba.",
"Send a Message": "Pošaljite poruku",
"Subject": "Predmet",
"Message": "Poruka",
"By sending this message, you agree to our": "Slanjem poruke prihvaćate",
"Send Message": "Pošalji poruku",
"Message Sent": "Poruka je poslana",
"Thank you. We've received your message and will reply shortly.": "Hvala. Primili smo vašu poruku i uskoro odgovaramo.",
"Direct Contact": "Izravni kontakt",
"Base": "Sjedište",
"Google Rating": "Google ocjena",
"★ 5.0 (35+ reviews)": "★ 5.0 (35+ recenzija)",
}
