T = {
# privacy
"Privacy Policy | Airport Split Transfer": "Pravila privatnosti | Airport Split Transfer",
"How Airport Split Transfer / Taxi De Niro Split collects, uses and protects your personal data under the GDPR when you book a private transfer in Croatia.": "Kako Airport Split Transfer / Taxi De Niro Split prikuplja, koristi i štiti vaše osobne podatke prema GDPR-u kada rezervirate privatni transfer u Hrvatskoj.",
"Legal": "Pravne informacije",
"Last updated: 4 October 2026": "Zadnja izmjena: 4. listopada 2026.",
"This policy explains how we handle your personal data when you visit airportsplittransfer.com, request a transfer or day trip, or contact us. We process personal data in line with the EU General Data Protection Regulation (GDPR) and the Croatian Act on the Implementation of the GDPR.": "Ova pravila objašnjavaju kako postupamo s vašim osobnim podacima kada posjetite airportsplittransfer.com, zatražite transfer ili izlet ili nam se javite. Osobne podatke obrađujemo u skladu s Općom uredbom o zaštiti podataka (GDPR) i Zakonom o provedbi Opće uredbe o zaštiti podataka.",
"1. Who is responsible for your data": "1. Tko je odgovoran za vaše podatke",
"The data controller is:": "Voditelj obrade je:",
"Airport Split Transfer / Taxi De Niro Split": "Airport Split Transfer / Taxi De Niro Split",
"Put Vele Meje 12, 21212 Kaštel Sućurac, Croatia": "Put Vele Meje 12, 21212 Kaštel Sućurac, Hrvatska",
"OIB: 76407755281": "OIB: 76407755281",
"Email:": "E-mail:",
"Phone / WhatsApp:": "Telefon / WhatsApp:",
"For any question about your data or to exercise your rights, write to us at the email address above.": "Za sva pitanja o vašim podacima ili za ostvarivanje svojih prava pišite nam na gornju e-mail adresu.",
"2. What data we collect": "2. Koje podatke prikupljamo",
"When you request a transfer or day trip": "Kada zatražite transfer ili izlet",
", we collect the details you enter in the booking form:": ", prikupljamo podatke koje upišete u obrazac za rezervaciju:",
"full name, email address and phone number;": "ime i prezime, e-mail adresu i broj telefona;",
"pickup and drop-off address (including map coordinates when you pick an address suggestion), date and time;": "adresu polazišta i odredišta (uključujući koordinate na karti kada odaberete predloženu adresu), datum i vrijeme;",
"return date and time, flight number, number of passengers and suitcases, chosen vehicle and quoted price;": "datum i vrijeme povratka, broj leta, broj putnika i kofera, odabrano vozilo i izračunatu cijenu;",
"any notes you add, for example child seats or special requests;": "napomene koje dodate, na primjer dječje sjedalice ili posebne zahtjeve;",
"the website language you booked in.": "jezik stranice na kojem ste rezervirali.",
"When you contact us": "Kada nam se javite",
"by email, phone or WhatsApp, we receive your contact details and the content of your message.": "e-mailom, telefonom ili WhatsAppom, dobivamo vaše kontakt podatke i sadržaj poruke.",
"When you browse the website": "Kada pregledavate stranicu",
", our hosting provider automatically records technical data such as IP address, browser type and time of access, which is needed to deliver the site securely. Analytics data is collected only if you consent to it (see section 7).": ", naš pružatelj usluge smještaja stranice automatski bilježi tehničke podatke poput IP adrese, vrste preglednika i vremena pristupa, koji su potrebni za sigurno prikazivanje stranice. Analitičke podatke prikupljamo samo uz vaš pristanak (vidi točku 7).",
"We do not ask for special categories of data. Please do not include health or other sensitive information in the notes field unless it is needed for your transfer (for example, a wheelchair).": "Ne tražimo posebne kategorije podataka. Molimo vas da u napomenu ne upisujete podatke o zdravlju ni druge osjetljive podatke osim ako su potrebni za transfer (na primjer, invalidska kolica).",
"3. Why we use your data and on what legal basis": "3. Zašto koristimo vaše podatke i na kojoj pravnoj osnovi",
"To arrange and carry out your transfer": "Za dogovor i obavljanje transfera",
"confirming the booking, planning the pickup, tracking your flight, contacting you on the day and sending the confirmation email. Legal basis: performance of a contract and steps before entering into it (Art. 6(1)(b) GDPR).": "potvrda rezervacije, planiranje preuzimanja, praćenje leta, kontakt na dan vožnje i slanje e-maila potvrde. Pravna osnova: izvršenje ugovora i radnje prije sklapanja ugovora (čl. 6. st. 1. t. (b) GDPR-a).",
"To answer your questions": "Za odgovore na vaša pitanja",
"sent by email, phone or WhatsApp. Legal basis: Art. 6(1)(b) GDPR, or our legitimate interest in replying to enquiries (Art. 6(1)(f) GDPR).": "poslana e-mailom, telefonom ili WhatsAppom. Pravna osnova: čl. 6. st. 1. t. (b) GDPR-a ili naš legitimni interes da odgovorimo na upite (čl. 6. st. 1. t. (f) GDPR-a).",
"To keep accounting and tax records": "Za vođenje računovodstvene i porezne evidencije",
"of completed services. Legal basis: legal obligation (Art. 6(1)(c) GDPR).": "o obavljenim uslugama. Pravna osnova: pravna obveza (čl. 6. st. 1. t. (c) GDPR-a).",
"To keep the website secure and working": "Za sigurnost i ispravan rad stranice",
", and to prevent misuse of the booking form. Legal basis: legitimate interest (Art. 6(1)(f) GDPR).": " te za sprječavanje zlouporabe obrasca za rezervaciju. Pravna osnova: legitimni interes (čl. 6. st. 1. t. (f) GDPR-a).",
"To understand how the website is used": "Za razumijevanje kako se stranica koristi",
"through Google Analytics. Legal basis: your consent (Art. 6(1)(a) GDPR), which you can withdraw at any time.": "putem Google Analyticsa. Pravna osnova: vaš pristanak (čl. 6. st. 1. t. (a) GDPR-a), koji možete povući u bilo kojem trenutku.",
"We do not use your data for automated decision-making or profiling, and we do not sell it.": "Vaše podatke ne koristimo za automatizirano donošenje odluka ni izradu profila i ne prodajemo ih.",
"4. Who receives your data": "4. Tko prima vaše podatke",
"Your data is seen only by the people who need it to deliver your transfer. Our team and the driver assigned to your booking. We also use these service providers, who process data on our behalf under data processing agreements:": "Vaše podatke vide samo osobe kojima su potrebni za obavljanje transfera: naš tim i vozač dodijeljen vašoj rezervaciji. Koristimo i sljedeće pružatelje usluga, koji podatke obrađuju u naše ime na temelju ugovora o obradi podataka:",
"Netlify, Inc.": "Netlify, Inc.",
"website hosting and receipt of booking form submissions;": "smještaj stranice i primanje poslanih obrazaca za rezervaciju;",
"Resend": "Resend",
"delivery of booking confirmation emails;": "slanje e-mailova s potvrdom rezervacije;",
"Google Maps address suggestions and distance calculation when you type an address in the booking form and Google Analytics (only with your consent);": "prijedlozi adresa i izračun udaljenosti preko Google Mapsa kada upisujete adresu u obrazac za rezervaciju te Google Analytics (samo uz vaš pristanak);",
"WhatsApp (Meta)": "WhatsApp (Meta)",
"only if you choose to contact us on WhatsApp.": "samo ako nam se odlučite javiti na WhatsApp.",
"We may disclose data to public authorities where the law requires it.": "Podatke možemo dati tijelima javne vlasti kada to zakon zahtijeva.",
"5. Transfers outside the EU": "5. Prijenos izvan EU",
"Some of the providers above are based in the United States. Where data leaves the European Economic Area, it is protected by the EU–U.S. Data Privacy Framework or by the European Commission's Standard Contractual Clauses.": "Neki od navedenih pružatelja usluga nalaze se u Sjedinjenim Američkim Državama. Kada podaci napuste Europski gospodarski prostor, zaštićeni su Okvirom za privatnost podataka EU-a i SAD-a ili standardnim ugovornim klauzulama Europske komisije.",
"6. How long we keep your data": "6. Koliko dugo čuvamo podatke",
"Booking data is kept for as long as needed to carry out the transfer and handle any follow-up questions or complaints, and for no longer than 24 months after the transfer date.": "Podatke o rezervaciji čuvamo onoliko koliko je potrebno za obavljanje transfera i rješavanje naknadnih pitanja ili prigovora, a najdulje 24 mjeseca od datuma transfera.",
"Where a booking is part of our accounting records, those records are kept for the period required by Croatian accounting and tax law.": "Ako je rezervacija dio naše računovodstvene evidencije, ta se evidencija čuva u roku koji propisuju hrvatski računovodstveni i porezni propisi.",
"Messages sent to us are kept for as long as needed to deal with your enquiry.": "Poruke koje nam pošaljete čuvamo onoliko koliko je potrebno da riješimo vaš upit.",
"Analytics data is kept for no longer than 14 months.": "Analitičke podatke čuvamo najdulje 14 mjeseci.",
"7. Cookies": "7. Kolačići",
"We use a small number of cookies:": "Koristimo mali broj kolačića:",
"region": "region",
"a necessary cookie that records only whether you are visiting from the EU/EEA/UK, so we know whether to show the cookie banner (kept for 30 days);": "nužni kolačić koji bilježi samo dolazite li iz EU/EGP-a/UK-a, kako bismo znali trebamo li prikazati obavijest o kolačićima (čuva se 30 dana);",
"klaro-consent": "klaro-consent",
"a necessary cookie that remembers your cookie choice (kept for 12 months);": "nužni kolačić koji pamti vaš izbor kolačića (čuva se 12 mjeseci);",
"_ga, _ga_*": "_ga, _ga_*",
"Google Analytics cookies, set only if you accept analytics.": "kolačići Google Analyticsa, postavljaju se samo ako prihvatite analitiku.",
"You can change your choice at any time with the “Cookie Preferences” link at the bottom of every page.": "Svoj izbor možete promijeniti u bilo kojem trenutku putem poveznice „Postavke kolačića” na dnu svake stranice.",
"8. Your rights": "8. Vaša prava",
"Under the GDPR you have the right to:": "Prema GDPR-u imate pravo:",
"access the personal data we hold about you and receive a copy;": "na pristup osobnim podacima koje imamo o vama i na njihovu kopiju;",
"have inaccurate data corrected;": "na ispravak netočnih podataka;",
"have your data erased where there is no legal reason for us to keep it;": "na brisanje podataka kada ih nemamo zakonskog razloga čuvati;",
"restrict or object to processing based on our legitimate interest;": "na ograničenje obrade ili prigovor na obradu koja se temelji na našem legitimnom interesu;",
"receive your data in a portable format;": "na prenosivost podataka;",
"withdraw your consent at any time, without affecting processing carried out before the withdrawal.": "povući pristanak u bilo kojem trenutku, bez utjecaja na obradu provedenu prije povlačenja.",
"To use any of these rights, email": "Za ostvarivanje bilo kojeg od ovih prava pišite na",
". We reply within one month.": ". Odgovaramo u roku od mjesec dana.",
"You also have the right to lodge a complaint with the Croatian supervisory authority: Agencija za zaštitu osobnih podataka (AZOP), Selska cesta 136, 10000 Zagreb,": "Imate i pravo podnijeti prigovor nadzornom tijelu: Agencija za zaštitu osobnih podataka (AZOP), Selska cesta 136, 10000 Zagreb,",
"azop.hr": "azop.hr",
"9. Security": "9. Sigurnost",
"The website is served only over encrypted HTTPS connections, and access to booking data is limited to the people who need it to deliver your transfer.": "Stranica se prikazuje isključivo preko šifrirane HTTPS veze, a pristup podacima o rezervacijama imaju samo osobe kojima su potrebni za obavljanje transfera.",
"10. Changes to this policy": "10. Izmjene ovih pravila",
"We may update this policy when our services or the law change. The date at the top of the page shows when it was last updated.": "Pravila možemo izmijeniti kada se promijene naše usluge ili propisi. Datum na vrhu stranice pokazuje kada su zadnji put izmijenjena.",

# terms
"Terms & Conditions | Airport Split Transfer": "Uvjeti poslovanja | Airport Split Transfer",
"Booking, cancellation, refund, waiting time and liability terms for private transfers and day trips with Airport Split Transfer / Taxi De Niro Split in Croatia.": "Uvjeti rezervacije, otkazivanja, povrata novca, čekanja i odgovornosti za privatne transfere i izlete s Airport Split Transfer / Taxi De Niro Split.",
"Last updated: 5 October 2026": "Zadnja izmjena: 5. listopada 2026.",
"These terms apply to every private transfer and day trip booked through airportsplittransfer.com, by email, by phone or on WhatsApp. By sending a booking request you accept these terms.": "Ovi uvjeti vrijede za svaki privatni transfer i izlet rezerviran preko airportsplittransfer.com, e-mailom, telefonom ili WhatsAppom. Slanjem zahtjeva za rezervaciju prihvaćate ove uvjete.",
"1. About us": "1. O nama",
"We provide private passenger transport with a driver in Croatia: airport transfers, point-to-point transfers and private day trips.": "Obavljamo privatni prijevoz putnika s vozačem u Hrvatskoj: aerodromske transfere, izravne transfere između mjesta i privatne izlete.",
"2. Booking and confirmation": "2. Rezervacija i potvrda",
"Submitting the booking form sends us a booking request. The booking is confirmed once we send you a confirmation by email with your pickup details.": "Slanjem obrasca šaljete nam zahtjev za rezervaciju. Rezervacija je potvrđena kada vam pošaljemo potvrdu e-mailom s detaljima preuzimanja.",
"Please check that your name, phone number, email, addresses, date, time and flight number are correct. We plan the transfer on the details you give us.": "Molimo provjerite jesu li ime, broj telefona, e-mail, adrese, datum, vrijeme i broj leta točni. Transfer planiramo prema podacima koje nam date.",
"For airport pickups, please add your flight number so we can follow your actual landing time.": "Za preuzimanje na aerodromu upišite broj leta kako bismo mogli pratiti stvarno vrijeme slijetanja.",
"No account and no deposit are needed to book.": "Za rezervaciju ne trebate korisnički račun ni polog.",
"3. Prices and payment": "3. Cijene i plaćanje",
"Prices are fixed per vehicle, not per person, and are shown before you book. They include the driver, fuel, road tolls, meet and greet at arrivals, and child seats on request.": "Cijene su fiksne po vozilu, a ne po osobi, i prikazane su prije rezervacije. Uključuju vozača, gorivo, cestarinu, doček u dolaznom terminalu i dječje sjedalice na zahtjev.",
"A return transfer booked together with the outbound transfer includes an automatic 5% discount on the total price.": "Povratni transfer rezerviran zajedno s polaznim automatski dobiva 5% popusta na ukupnu cijenu.",
"Extra stops, route changes requested on the day, or waiting beyond what is included may be charged extra. We will always tell you the amount first.": "Dodatna stajanja, promjene rute zatražene na dan vožnje ili čekanje dulje od uključenog mogu se dodatno naplatiti. Iznos vam uvijek kažemo unaprijed.",
"Day trips have a fixed price for the whole day. National park entrance tickets, boat trips, food and drinks are not included.": "Izleti imaju fiksnu cijenu za cijeli dan. Ulaznice za nacionalne parkove, vožnje brodom, hrana i piće nisu uključeni.",
"Unless a different payment method has been agreed in advance, payment is made to the driver on the day of the transfer.": "Ako unaprijed nije dogovoren drugi način plaćanja, plaća se vozaču na dan transfera.",
"4. Waiting time and flight delays": "4. Čekanje i kašnjenje leta",
"Airport pickups:": "Preuzimanje na aerodromu:",
"we track your flight and adjust the pickup to your actual landing time. Flight delays are not charged extra when your flight number was provided. Your driver waits for you in the arrivals hall, and the first 60 minutes after your actual landing time are free of charge.": "pratimo vaš let i preuzimanje prilagođavamo stvarnom vremenu slijetanja. Kašnjenje leta ne naplaćujemo dodatno ako ste upisali broj leta. Vozač vas čeka u dolaznom terminalu, a prvih 60 minuta nakon stvarnog slijetanja je besplatno.",
"Pickups from an address": "Preuzimanje na adresi",
"(hotel, apartment, port): the driver waits up to 15 minutes after the booked time free of charge.": "(hotel, apartman, luka): vozač besplatno čeka do 15 minuta nakon dogovorenog vremena.",
"If your flight is cancelled or rebooked, let us know as soon as possible and we will move your transfer to the new time where possible, at no extra cost.": "Ako vam je let otkazan ili premješten, javite nam što prije i transfer ćemo, kada je moguće, premjestiti na novo vrijeme bez dodatnih troškova.",
"5. Changes and cancellations by you": "5. Vaše izmjene i otkazivanje",
"Cancellation is always free of charge. You can cancel your booking at any time before pickup by email, phone or WhatsApp, with no cancellation fee.": "Otkazivanje je uvijek besplatno. Rezervaciju možete otkazati u bilo kojem trenutku prije preuzimanja e-mailom, telefonom ili WhatsAppom, bez naknade.",
"Changes to the date, time, addresses or vehicle are also free of charge, subject to availability. Please let us know as early as possible, especially on the day of travel.": "Izmjene datuma, vremena, adresa ili vozila također su besplatne, ovisno o raspoloživosti. Javite nam što ranije, osobito na dan putovanja.",
"No-show:": "Nedolazak:",
"if you do not arrive at the pickup point and cannot be reached by phone or WhatsApp after the waiting time, the driver may leave and the booking is closed. If your plans change, please cancel instead so the driver is not sent out.": "ako ne dođete na mjesto preuzimanja i nakon vremena čekanja niste dostupni telefonom ni WhatsAppom, vozač može otići, a rezervacija se zatvara. Ako vam se planovi promijene, molimo otkažite rezervaciju da vozač ne bi uzalud išao.",
"6. Changes and cancellations by us": "6. Naše izmjene i otkazivanje",
"If we cannot carry out a confirmed transfer, for example because of a vehicle breakdown, we will arrange an equivalent vehicle at no extra cost. If that is not possible, we will cancel the booking and refund in full anything you have paid in advance.": "Ako ne možemo obaviti potvrđeni transfer, na primjer zbog kvara vozila, osigurat ćemo jednakovrijedno vozilo bez dodatnih troškova. Ako to nije moguće, otkazat ćemo rezervaciju i u cijelosti vratiti sve što ste platili unaprijed.",
"7. Refunds": "7. Povrat novca",
"If you paid in advance, you receive a full refund whenever you cancel, and also if we cancel the booking.": "Ako ste platili unaprijed, dobivate puni povrat kad god otkažete, kao i ako mi otkažemo rezervaciju.",
"Refunds are made to the original payment method within 14 days.": "Povrat se izvršava na izvorni način plaćanja u roku od 14 dana.",
"8. Passengers, luggage and children": "8. Putnici, prtljaga i djeca",
"Please book the correct number of passengers and suitcases. Vehicle capacity: Škoda Superb 1–4 passengers, Mercedes-Benz V-Class 1–7 passengers, Renault Trafic 1–8 passengers.": "Molimo rezervirajte točan broj putnika i kofera. Kapacitet vozila: Škoda Superb 1–4 putnika, Mercedes-Benz V-Class 1–7 putnika, Renault Trafic 1–8 putnika.",
"Let us know in advance about oversized items such as bicycles, surfboards, golf bags or wheelchairs. If the luggage does not fit the booked vehicle, a larger vehicle may be needed at the matching price.": "Unaprijed nam javite za veće predmete poput bicikla, dasaka za surf, golf torbi ili invalidskih kolica. Ako prtljaga ne stane u rezervirano vozilo, može biti potrebno veće vozilo po odgovarajućoj cijeni.",
"Child seats are free of charge and must be requested when booking. Children must travel in a suitable child seat as required by Croatian law.": "Dječje sjedalice su besplatne i treba ih zatražiti pri rezervaciji. Djeca moraju putovati u odgovarajućoj dječjoj sjedalici, kako propisuje hrvatski zakon.",
"Seat belts must be worn. Smoking, including e-cigarettes, is not allowed in our vehicles.": "Vezanje sigurnosnim pojasom je obvezno. Pušenje, uključujući e-cigarete, nije dopušteno u našim vozilima.",
"The driver may refuse to carry passengers whose behaviour puts the safety of the journey at risk. Cleaning costs for serious soiling of the vehicle may be charged.": "Vozač može odbiti prijevoz putnika čije ponašanje ugrožava sigurnost vožnje. Troškovi čišćenja kod jačeg onečišćenja vozila mogu se naplatiti.",
"9. Day trips": "9. Izleti",
"Day trips are private round trips: your driver takes you to the destination, waits, and brings you back the same day.": "Izleti su privatne vožnje u oba smjera: vozač vas vozi do odredišta, čeka vas i vraća istog dana.",
"The suggested itinerary is flexible and agreed with your driver. Park opening times, closures and ticket rules are set by the national parks, not by us.": "Predloženi plan je fleksibilan i dogovarate ga s vozačem. Radno vrijeme parkova, zatvaranja i pravila za ulaznice određuju nacionalni parkovi, a ne mi.",
"10. Liability": "10. Odgovornost",
"Our vehicles are licensed for passenger transport and insured as required by Croatian law.": "Naša vozila imaju dozvolu za prijevoz putnika i osigurana su kako propisuje hrvatski zakon.",
"We plan every transfer with enough time, but we are not responsible for delays caused by traffic, weather, road closures, border or police checks, accidents involving third parties, or other events outside our control.": "Svaki transfer planiramo s dovoljno vremena, ali ne odgovaramo za kašnjenja zbog prometa, vremenskih uvjeta, zatvorenih cesta, graničnih ili policijskih kontrola, nesreća u kojima sudjeluju treće osobe ili drugih okolnosti na koje ne možemo utjecati.",
"For departures, please choose a pickup time that leaves enough margin for your flight or ferry. We are not liable for a missed flight, ferry or connection caused by circumstances outside our control or by a pickup time chosen with too little margin.": "Za odlaske odaberite vrijeme preuzimanja s dovoljno rezerve do leta ili trajekta. Ne odgovaramo za propušten let, trajekt ili presjedanje zbog okolnosti na koje ne možemo utjecati ili zbog vremena preuzimanja odabranog s premalo rezerve.",
"Where we are liable, our liability is limited to the price of the booked service, except for death or personal injury, or damage caused intentionally or through gross negligence, where the law does not allow liability to be limited.": "Kada odgovaramo, naša je odgovornost ograničena na cijenu rezervirane usluge, osim za smrt ili tjelesnu ozljedu te štetu prouzročenu namjerno ili krajnjom nepažnjom, gdje zakon ne dopušta ograničenje odgovornosti.",
"Please take your belongings with you. We keep items found in our vehicles and will help you get them back, but we are not responsible for valuables left in the vehicle.": "Molimo ponesite svoje stvari. Predmete pronađene u vozilima čuvamo i pomoći ćemo vam da ih dobijete natrag, ali ne odgovaramo za vrijednosti ostavljene u vozilu.",
"11. Complaints and applicable law": "11. Prigovori i mjerodavno pravo",
"If something was not right, please tell us as soon as possible at": "Ako nešto nije bilo u redu, javite nam što prije na",
". We reply to complaints within 15 days.": ". Na prigovore odgovaramo u roku od 15 dana.",
"These terms are governed by Croatian law. This does not affect the rights you have as a consumer under the mandatory law of the country where you live.": "Na ove uvjete primjenjuje se hrvatsko pravo. To ne utječe na prava koja kao potrošač imate prema prisilnim propisima zemlje u kojoj živite.",
"Passenger transport booked for a specific date is not covered by the 14-day right of withdrawal for distance contracts. Our free cancellation policy in section 5 applies instead.": "Na prijevoz putnika rezerviran za određeni datum ne primjenjuje se pravo na jednostrani raskid ugovora sklopljenog na daljinu u roku od 14 dana. Umjesto toga vrijedi naše besplatno otkazivanje iz točke 5.",
"12. Personal data": "12. Osobni podaci",
"How we use your personal data is explained in our": "Kako koristimo vaše osobne podatke objašnjeno je u dokumentu",
}
