T = {
# services/ audience pages (phase 2)
"Business Transfers from Split Airport | Airport Split Transfer": "Poslovni transferi sa Zračne luke Split | Airport Split Transfer",
"Private business transfers from Split Airport: company invoice on request, flight tracking, Škoda Superb or Mercedes V-Class, fixed price agreed in advance.": "Privatni poslovni transferi sa Zračne luke Split: R1 račun na firmu, praćenje leta, Škoda Superb ili Mercedes V-Class i fiksna cijena dogovorena unaprijed.",
"Can I get an invoice for my company?": "Mogu li dobiti račun na firmu?",
"Yes. Give us the company name, address and tax number when you book, and we issue the invoice in the company's name after the ride. Croatian companies receive an R1 invoice.": "Da. Pri rezervaciji nam pošaljite naziv tvrtke, adresu i OIB, a račun na tvrtku izdajemo nakon vožnje. Hrvatske tvrtke dobivaju R1 račun.",
"Which car is best for a business trip?": "Koje je vozilo najbolje za poslovni put?",
"The Škoda Superb for up to 4 people. For a team or clients, the Mercedes V-Class seats up to 7 in a premium cabin.": "Škoda Superb za do 4 osobe. Za tim ili klijente Mercedes V-Class prima do 7 osoba u luksuznijoj kabini.",
"Can the driver wait during a meeting and take us back?": "Može li vozač čekati za vrijeme sastanka i vratiti nas?",
"Yes. A car and driver can be booked by the hour or for the full day. Contact us with your plan for a quote.": "Da. Vozilo s vozačem može se rezervirati na sat ili za cijeli dan. Pošaljite nam plan i dobit ćete ponudu.",
"What if my flight is delayed?": "Što ako mi let kasni?",
"We follow your flight number and adjust the pickup. The first 60 minutes after landing are free.": "Pratimo vaš let i prilagođavamo preuzimanje. Prvih 60 minuta nakon slijetanja je besplatno.",
"Can I pay by card?": "Mogu li platiti karticom?",
"Yes, card and cash are both accepted, and the price is fixed when you book.": "Da, primamo i kartice i gotovinu, a cijena je fiksna od trenutka rezervacije.",
"Business transfers from Split Airport": "Poslovni transferi sa Zračne luke Split",
"Landing for a meeting, a conference or a site visit? Your driver is waiting in arrivals, the price is fixed in advance, and you get an invoice made out to your company.": "Slijećete na sastanak, konferenciju ili obilazak terena? Vozač vas čeka u dolaznom terminalu, cijena je dogovorena unaprijed, a dobivate račun na svoju tvrtku.",
"Company invoice": "R1 račun",
"on request": "na zahtjev",
"Fixed price": "Fiksna cijena",
"agreed in advance": "dogovorena unaprijed",
"Live@@split-airport-business-transfers.html": "Praćenje",
"flight tracking": "leta uživo",
"Card or cash": "Kartica ili gotovina",
"Made for work trips": "Prilagođeno poslovnim putovanjima",
"Add your company's name, address and tax number in the notes when you book, and after the ride we issue the invoice in the company's name. Croatian companies get a standard R1 invoice. You can pay by card or in cash, and the price does not change on the day.": "Pri rezervaciji u napomenu upišite naziv tvrtke, adresu i OIB, a nakon vožnje izdajemo račun na tvrtku. Hrvatske tvrtke dobivaju uobičajeni R1 račun. Platiti možete karticom ili gotovinom, a cijena se na dan vožnje ne mijenja.",
"The Škoda Superb is a quiet executive sedan for up to 4 people. For a team or a client group, the Mercedes V-Class seats up to 7 in a premium cabin, with room for luggage and equipment.": "Škoda Superb je tiha poslovna limuzina za do 4 osobe. Za tim ili grupu klijenata Mercedes V-Class prima do 7 osoba u luksuznijoj kabini, uz mjesta za prtljagu i opremu.",
"We follow your flight, and the first 60 minutes after landing are free, so a delay or a slow passport line costs you nothing. For a day of meetings in Split, Trogir or Šibenik, a car and driver can stay with you by the hour or for the whole day.": "Pratimo vaš let, a prvih 60 minuta nakon slijetanja je besplatno, pa vas kašnjenje ili spora granična kontrola ne koštaju ništa. Za dan pun sastanaka u Splitu, Trogiru ili Šibeniku vozilo s vozačem može ostati s vama na sat ili cijeli dan.",
"How it works": "Kako funkcionira",
"Book": "Rezervirajte",
"Tap the button and add your company details in the notes.": "Kliknite gumb i u napomenu upišite podatke tvrtke.",
"We follow your flight": "Pratimo vaš let",
"If you land early or late, your driver knows and adjusts.": "Ako sletite ranije ili kasnije, vozač to zna i prilagodi se.",
"Met in arrivals": "Doček u dolaznom terminalu",
"Your driver waits with a name board and helps with the bags.": "Vozač vas čeka s imenom na tabli i pomaže s prtljagom.",
"Straight to your meeting": "Ravno na sastanak",
"No other passengers and no shared stops.": "Bez drugih putnika i bez usputnih stajanja.",
"See": "Pogledajte",
"all our services": "sve naše usluge",
", including hourly and full-day hire, or our": ", uključujući najam na sat i cijeli dan, ili naše",
"hotel transfers": "transfere do hotela",
"Questions": "Pitanja",

"Split Airport Transfer with Kids | Airport Split Transfer": "Transfer sa Zračne luke Split s djecom | Airport Split Transfer",
"Private transfer from Split Airport for families: free child seats on request, no shared stops, room for pushchairs, fixed price per vehicle.": "Privatni transfer sa Zračne luke Split za obitelji: besplatne dječje sjedalice na zahtjev, bez usputnih stajanja, mjesta za kolica i fiksna cijena po vozilu.",
"Are child seats really free?": "Jesu li dječje sjedalice stvarno besplatne?",
"Yes. Baby and child seats are free on request in all three vehicles. Tell us how many children are travelling and how old they are when you book.": "Da. Sjedalice za bebe i djecu besplatne su na zahtjev u sva tri vozila. Pri rezervaciji nam napišite koliko djece putuje i koliko imaju godina.",
"Which vehicle is best for a family?": "Koje je vozilo najbolje za obitelj?",
"Up to 4 people with normal luggage fit in the Škoda Superb. With a pushchair, a travel cot or more than three suitcases, take the Mercedes V-Class (up to 7) or the Renault Trafic (up to 8).": "Do 4 osobe s uobičajenom prtljagom stanu u Škodu Superb. S kolicima, putnim krevetićem ili više od tri kofera uzmite Mercedes V-Class (do 7 osoba) ili Renault Trafic (do 8 osoba).",
"What if our flight is late?": "Što ako nam let kasni?",
"We follow your flight number, so the driver adjusts to the real landing time. The first 60 minutes after landing are free.": "Pratimo vaš let pa se vozač prilagođava stvarnom vremenu slijetanja. Prvih 60 minuta nakon slijetanja je besplatno.",
"Do children pay extra?": "Plaćaju li djeca dodatno?",
"No. The price is per vehicle and fixed when you book, with tolls, fuel and meet and greet included.": "Ne. Cijena je po vozilu i fiksna od trenutka rezervacije, a uključuje cestarinu, gorivo i doček.",
"Can we book the ride back to the airport too?": "Možemo li rezervirati i povratak na aerodrom?",
"Yes. Choose \"Return\" in the form to book both legs together and get 5% off the total.": "Da. U obrascu odaberite \"Povratna\", rezervirajte obje vožnje odjednom i dobijte 5% popusta na ukupnu cijenu.",
"Families with children": "Obitelji s djecom",
"Split Airport transfers for families with kids": "Transferi sa Zračne luke Split za obitelji s djecom",
"After a flight with small children, the last thing you need is a taxi queue or a bus change. Your driver meets you in arrivals, the child seats are already fitted, and you go straight to your door.": "Nakon leta s malom djecom zadnje što vam treba je red za taksi ili presjedanje na autobus. Vozač vas dočeka u dolaznom terminalu, dječje sjedalice su već postavljene i vozite se ravno do vrata.",
"Free@@split-airport-transfer-with-kids.html": "Besplatne",
"child seats on request": "dječje sjedalice na zahtjev",
"free waiting at the airport": "besplatnog čekanja na aerodromu",
"per vehicle, not per person": "po vozilu, a ne po osobi",
"Vans for families of up to": "Kombiji za obitelji do",
"What we take care of": "Za što se mi brinemo",
"Child seats are free and fitted before you get in. When you book, add the number of children and their ages in the notes, so the driver brings the right seats. Croatian law requires a suitable seat for young children, and we always follow it.": "Dječje sjedalice su besplatne i postavljene prije nego što uđete. Pri rezervaciji u napomenu upišite broj djece i njihovu dob kako bi vozač donio prave sjedalice. Hrvatski zakon propisuje odgovarajuću sjedalicu za malu djecu i mi ga se uvijek držimo.",
"Pushchairs, travel cots and your own car seats go in the boot with the suitcases. With a lot of luggage, choose the Mercedes V-Class or the Renault Trafic. The price is per vehicle, so the extra space does not mean paying per head.": "Kolica, putni krevetići i vaše autosjedalice idu u prtljažnik s koferima. S puno prtljage odaberite Mercedes V-Class ili Renault Trafic. Cijena je po vozilu, pa dodatni prostor ne znači plaćanje po osobi.",
"Flights with children are often late, and passport control can be slow. We follow your flight, and the first 60 minutes after landing are free, so nobody has to rush.": "Letovi s djecom često kasne, a granična kontrola zna biti spora. Pratimo vaš let, a prvih 60 minuta nakon slijetanja je besplatno, pa nitko ne mora žuriti.",
"“We were travelling with our little 9 month old and he really helped us and made sure all was ok.”": "„Putovali smo s bebom od 9 mjeseci, puno nam je pomogao i pazio da sve bude u redu.”",
"Tap the button, enter your address and add the children's ages in the notes.": "Kliknite gumb, upišite adresu i u napomenu dodajte dob djece.",
"Your driver waits with a name board and helps with the bags and the pushchair.": "Vozač vas čeka s imenom na tabli i pomaže s prtljagom i kolicima.",
"Straight to your door": "Ravno do vrata",
"No other passengers. Child seats are ready in the car.": "Bez drugih putnika. Dječje sjedalice već su u autu.",
"Planning a day out with the kids? See our": "Planirate izlet s djecom? Pogledajte naše",
"private day trips": "privatne jednodnevne izlete",
"to Krka and Plitvice, or": "do Krke i Plitvica ili",
"compare the vehicles": "usporedite vozila",

"Group Transfers from Split Airport | Airport Split Transfer": "Grupni transferi sa Zračne luke Split | Airport Split Transfer",
"Private group transfers from Split Airport: one van for up to 8 people and their bags, several vehicles for bigger groups, fixed price per vehicle.": "Privatni grupni transferi sa Zračne luke Split: jedan kombi za do 8 osoba s prtljagom, više vozila za veće grupe i fiksna cijena po vozilu.",
"How many people fit in one vehicle?": "Koliko osoba stane u jedno vozilo?",
"Up to 8 in the Renault Trafic and up to 7 in the Mercedes V-Class, each with room for one suitcase per person. The Škoda Superb takes up to 4.": "Do 8 u Renault Trafic i do 7 u Mercedes V-Class, svaki s mjestom za jedan kofer po osobi. Škoda Superb prima do 4 osobe.",
"We are more than 8. Can you take everyone?": "Ima nas više od 8. Možete li prevesti sve?",
"Yes, we combine several vehicles. Contact us a few days ahead so we can arrange them.": "Da, kombiniramo više vozila. Javite nam se nekoliko dana ranije da ih organiziramo.",
"Is the price per person?": "Je li cijena po osobi?",
"No, per vehicle, with tolls, fuel and meet and greet included. Divide it by the number of people in the van to see each share.": "Ne, po vozilu, s uključenom cestarinom, gorivom i dočekom. Podijelite je s brojem osoba u kombiju i vidjet ćete koliko plaća svatko.",
"Do you do weddings and events?": "Vozite li svatove i događaje?",
"Yes, group and wedding transfers are part of what we do. Send us the date, the places and the number of guests and we will send you a quote.": "Da, grupni transferi i svatovi dio su onoga što radimo. Pošaljite nam datum, mjesta i broj gostiju i poslat ćemo vam ponudu.",
"Can we book the return at the same time?": "Možemo li odmah rezervirati i povratak?",
"Group transfers from Split Airport": "Grupni transferi sa Zračne luke Split",
"Travelling as six, eight or twenty? Instead of splitting into taxis and losing each other at arrivals, the whole group travels together with the luggage, at a fixed price per vehicle.": "Putujete u šestero, osmero ili dvadesetero? Umjesto da se razdvojite po taksijima i gubite u dolaznom terminalu, cijela grupa putuje zajedno s prtljagom, po fiksnoj cijeni po vozilu.",
"Up to": "Do",
"people per van": "osoba po kombiju",
"Room for": "Mjesta za",
"suitcases": "kofera",
"Several vehicles": "Više vozila",
"for bigger groups": "za veće grupe",
"per vehicle": "po vozilu",
"One van instead of two taxis": "Jedan kombi umjesto dva taksija",
"The Renault Trafic takes up to 8 passengers and 8 suitcases, and the Mercedes V-Class up to 7 with 7 suitcases. You pay for the vehicle, not per seat, so the fuller it is, the less each person pays. A group of eight going from the airport to Makarska pays about €23 each.": "Renault Trafic prima do 8 putnika i 8 kofera, a Mercedes V-Class do 7 putnika i 7 kofera. Plaćate vozilo, a ne sjedalo, pa što je vozilo punije, svatko plaća manje. Grupa od osmero od aerodroma do Makarske plaća oko 23 € po osobi.",
"For bigger groups, such as a wedding party, a sports team or a company trip, we combine several vehicles so everyone arrives together. Contact us a few days ahead on WhatsApp or by email with the group size and flights, and we will arrange the right vehicles.": "Za veće grupe, poput svatova, sportske ekipe ili tvrtke na putu, kombiniramo više vozila da svi stignu zajedno. Javite nam se nekoliko dana ranije na WhatsApp ili e-mailom s brojem osoba i letovima i organizirat ćemo prava vozila.",
"Friends' weekends, birthdays and families travelling together all work the same way: one meeting point in arrivals, one driver per vehicle, and nobody left waiting for the next taxi.": "Vikendi s prijateljima, rođendani i obitelji koje putuju zajedno funkcioniraju jednako: jedno mjesto susreta u dolaznom terminalu, jedan vozač po vozilu i nitko ne čeka sljedeći taksi.",
"Book or message us": "Rezervirajte ili nam pišite",
"Up to 8 people: book online. More than that: send us the group size and flights.": "Do 8 osoba: rezervirajte online. Više od toga: pošaljite nam broj osoba i letove.",
"We follow the flight": "Pratimo let",
"Your driver waits with a name board and helps load the bags.": "Vozač vas čeka s imenom na tabli i pomaže utovariti prtljagu.",
"Straight to the address": "Ravno do adrese",
"See the": "Pogledajte",
"Mercedes V-Class and Renault Trafic": "Mercedes V-Class i Renault Trafic",
", or read": " ili pročitajte",
"which van suits your group": "koji kombi odgovara vašoj grupi",

"Split Cruise and Ferry Port Transfers | Airport Split Transfer": "Transferi iz splitske luke za kruzere i trajekte | Airport Split Transfer",
"Private transfer from Split cruise and ferry port to Split Airport or your hotel: about 25 to 30 minutes to the airport, fixed price per vehicle.": "Privatni transfer iz splitske luke za kruzere i trajekte do Zračne luke Split ili hotela: oko 25 do 30 minuta do aerodroma, fiksna cijena po vozilu.",
"How long is the drive from Split port to the airport?": "Koliko traje vožnja od splitske luke do aerodroma?",
"About 25 to 30 minutes for roughly 20 km. Allow more time on summer Saturdays.": "Oko 25 do 30 minuta za otprilike 20 km. Ljeti subotom računajte na više vremena.",
"Where do we meet the driver at the port?": "Gdje nas vozač čeka u luci?",
"We agree the exact meeting point with you before the day, depending on where your ship or ferry comes in.": "Točno mjesto susreta dogovaramo s vama unaprijed, ovisno o tome gdje pristaje vaš brod ili trajekt.",
"What if our ferry is late?": "Što ako nam trajekt kasni?",
"Tell us which ferry or catamaran you are on. If it is running late, message us on WhatsApp and we adjust the pickup.": "Javite nam kojim trajektom ili katamaranom dolazite. Ako kasni, pišite nam na WhatsApp i prilagodit ćemo preuzimanje.",
"Can you take us from the airport to the port?": "Možete li nas odvesti od aerodroma do luke?",
"Yes. Use the port as your destination when you book and add your ferry or check-in time, so we can plan a safe arrival.": "Da. Pri rezervaciji upišite luku kao odredište i dodajte vrijeme trajekta ili ukrcaja kako bismo planirali dolazak s dovoljno vremena.",
"No, per vehicle and fixed when you book, with tolls and fuel included.": "Ne, po vozilu i fiksna od trenutka rezervacije, s uključenom cestarinom i gorivom.",
"Transfers from Split cruise and ferry port": "Transferi iz splitske luke za kruzere i trajekte",
"Coming off a cruise ship, or off the ferry from Hvar or Brač, with suitcases? We take you from the port in Split straight to the airport, your hotel or anywhere on the coast, at a fixed price.": "Silazite s kruzera ili s trajekta s Hvara ili Brača s koferima? Vozimo vas iz splitske luke ravno na aerodrom, do hotela ili bilo kamo na obali, po fiksnoj cijeni.",
"About@@split-port-transfers.html": "Oko",
"to the airport": "do aerodroma",
"25 to 30 min": "25 do 30 min",
"Vans for up to": "Kombiji za najviše",
"From the port to the airport": "Od luke do aerodroma",
"Split's port sits right next to the old town. Ferries and catamarans from the islands come in here, and cruise ships berth or anchor along the harbour. The airport is about 20 km away, usually 25 to 30 minutes by car, and longer on summer Saturdays when the island traffic peaks.": "Splitska luka nalazi se odmah uz staru jezgru. Ovdje pristaju trajekti i katamarani s otoka, a kruzeri se vežu ili sidre uz lučki bazen. Aerodrom je udaljen oko 20 km, obično 25 do 30 minuta vožnje, a ljeti subotom, kad je promet prema otocima najgušći, i dulje.",
"Ports are busy in summer, so we agree the exact meeting point with you before the day. Add your ship or ferry and the time you expect to be off in the notes when you book. If the ferry is running late, send us a message on WhatsApp and we adjust the pickup.": "Ljeti je luka prepuna, pa točno mjesto susreta dogovaramo s vama unaprijed. Pri rezervaciji u napomenu upišite brod ili trajekt i vrijeme kad očekujete iskrcaj. Ako trajekt kasni, pošaljite nam poruku na WhatsApp i prilagodit ćemo preuzimanje.",
"Going the other way? We also drive from Split Airport or your hotel to the port, timed to your ferry or cruise check-in.": "Idete u suprotnom smjeru? Vozimo i od Zračne luke Split ili hotela do luke, prema vremenu trajekta ili ukrcaja na kruzer.",
"Book a transfer to the port": "Rezervirajte transfer do luke",
"Tap the button. The port is already filled in as your pickup.": "Kliknite gumb. Luka je već upisana kao polazište.",
"Tell us your ship or ferry": "Javite nam brod ili trajekt",
"Add it to the notes, with the time you expect to be off.": "Upišite ga u napomenu, s vremenom kad očekujete iskrcaj.",
"We agree the meeting point": "Dogovaramo mjesto susreta",
"Before the day, so you know exactly where to go.": "Unaprijed, da točno znate kamo ići.",
"Straight to the airport": "Ravno na aerodrom",
"Staying in Split first? See": "Prvo ostajete u Splitu? Pogledajte",
"transfers to Split city": "transfere do centra Splita",
"and our": "i naše",
}
