T = {
# day-trips.html
"Private Day Trips from Split: Plitvice, Krka | Airport Split Transfer": "Privatni izleti iz Splita: Plitvice i Krka | Airport Split Transfer",
"Private day trips from Split with an English-speaking driver: Plitvice Lakes, Krka National Park and fully custom excursions.": "Privatni jednodnevni izleti iz Splita s vozačem: Plitvička jezera, Nacionalni park Krka i izleti po vašoj želji.",
"Plitvice Lakes Day Trip": "Izlet na Plitvička jezera",
"Krka National Park Day Trip": "Izlet u Nacionalni park Krka",
"Are the day trips private or shared with other tourists?": "Jesu li izleti privatni ili s drugim turistima?",
"Fully private. Every day trip is a single vehicle and driver for your group only, never a shared shuttle.": "Potpuno privatni. Svaki izlet je jedno vozilo s vozačem samo za vašu grupu, nikad zajednički prijevoz.",
"What's included in the day trip price?": "Što je uključeno u cijenu izleta?",
"A private vehicle, an English-speaking driver, and a fixed price for the whole day, the driver waits at the park for your return leg.": "Privatno vozilo, vozač i fiksna cijena za cijeli dan; vozač vas čeka kod parka za povratak.",
"Are national park entrance tickets included?": "Jesu li uključene ulaznice za nacionalni park?",
"No. Entrance tickets and food are not included in the transfer price and are paid separately on the day. Fuel, tolls and parking at the park are included.": "Ne. Ulaznice i hrana nisu uključeni u cijenu prijevoza i plaćaju se zasebno na dan izleta. Gorivo, cestarina i parking kod parka su uključeni.",
"How long do the Plitvice and Krka trips take?": "Koliko traju izleti na Plitvice i Krku?",
"Plitvice Lakes is a 10–12 hour round trip; Krka National Park, being closer to Split, is 8–10 hours.": "Izlet na Plitvička jezera traje 10 do 12 sati u oba smjera, a na Krku, koja je bliže Splitu, 8 do 10 sati.",
"Can you organize a custom day trip somewhere else?": "Možete li organizirati izlet negdje drugdje?",
"Yes, we arrange fully private custom tours to Dubrovnik, Trogir, Omiš, Mostar and other destinations. Contact us with your itinerary.": "Da, organiziramo potpuno privatne izlete po želji u Dubrovnik, Trogir, Omiš, Mostar i druga odredišta. Pošaljite nam svoj plan.",
"Private Excursions from Split": "Privatni izleti iz Splita",
"Private Day Trips from Split": "Privatni jednodnevni izleti iz Splita",
"Discover Croatia comfortably with private excursions, flexible pickup and an English-speaking driver.": "Upoznajte Hrvatsku udobno, uz privatne izlete, fleksibilno vrijeme polaska i iskusnog vozača.",
"Turquoise cascading lakes and waterfalls at Plitvice Lakes National Park": "Tirkizna jezera i slapovi u Nacionalnom parku Plitvička jezera",
"Most Popular": "Najpopularnije",
"Day trips": "Izleti",
"10–12 hours": "10–12 sati",
"Croatia's oldest and largest national park, made famous by 16 terraced lakes connected by waterfalls and wooden walking trails through untouched forest.": "Najstariji i najveći nacionalni park u Hrvatskoj, poznat po 16 kaskadnih jezera povezanih slapovima i drvenim stazama kroz netaknutu šumu.",
"UNESCO World Heritage": "UNESCO svjetska baština",
"16 turquoise lakes": "16 tirkiznih jezera",
"Wooden walking trails": "Drvene pješačke staze",
"Private return transfer": "Privatni prijevoz u oba smjera",
"Book This Trip": "Rezerviraj izlet",
"Skradinski Buk waterfalls cascading into the river at Krka National Park": "Slapovi Skradinskog buka u Nacionalnom parku Krka",
"Nature Escape": "Bijeg u prirodu",
"8–10 hours": "8–10 sati",
"Closer to Split than Plitvice, Krka's Skradinski Buk waterfalls and riverside walking trails make for a relaxed, flexible day surrounded by nature.": "Bliže Splitu od Plitvica, Skradinski buk i staze uz rijeku Krku nude opušten i fleksibilan dan u prirodi.",
"Skradinski Buk waterfalls": "Slapovi Skradinskog buka",
"Beautiful nature": "Prekrasna priroda",
"Optional boat ride": "Vožnja brodom po želji",
"Flexible itinerary": "Fleksibilan plan",
"Tailored For You": "Po vašoj mjeri",
"Custom Private Tours": "Privatni izleti po želji",
"Want to visit Dubrovnik, Trogir, Omiš, Mostar or another destination? We organise fully private day trips tailored to your itinerary. Contact us and we'll create a custom tour for you.": "Želite posjetiti Dubrovnik, Trogir, Omiš, Mostar ili neko drugo odredište? Organiziramo potpuno privatne izlete prema vašem planu. Javite nam se i složit ćemo izlet za vas.",
"Request a Custom Tour": "Zatražite izlet po želji",
"Custom Tour Request": "Upit za izlet po želji",

# krka
"Krka Day Trip from Split, Private Tour | Airport Split Transfer": "Izlet na Krku iz Splita, privatni prijevoz | Airport Split Transfer",
"Private day trip from Split to Krka National Park with an English-speaking driver. See Skradinski Buk waterfalls, fixed price, flexible 8-10 hour itinerary.": "Privatni izlet iz Splita u Nacionalni park Krka s vozačem. Skradinski buk, fiksna cijena i fleksibilan plan od 8 do 10 sati.",
"Krka National Park Day Trip from Split": "Izlet iz Splita u Nacionalni park Krka",
"A private, flexible day excursion from Split to Krka National Park with an English-speaking driver, round-trip transfer and time to explore the Skradinski Buk waterfalls.": "Privatni i fleksibilni jednodnevni izlet iz Splita u Nacionalni park Krka s vozačem, prijevozom u oba smjera i vremenom za obilazak Skradinskog buka.",
"Hotel Pickup in Split": "Preuzimanje u hotelu u Splitu",
"Skradinski Buk waterfalls, riverside walking trails and optional boat trip to Visovac Island.": "Slapovi Skradinskog buka, staze uz rijeku i vožnja brodom do otočića Visovca po želji.",
"Return Transfer to Split": "Povratak u Split",
"How long does the Krka National Park day trip take?": "Koliko traje izlet u Nacionalni park Krka?",
"The full round trip from Split takes approximately 8–10 hours, including 3–4 hours to explore the park. Krka is closer to Split than Plitvice Lakes, which makes for a slightly more relaxed day.": "Cijeli izlet iz Splita traje otprilike 8 do 10 sati, od čega 3 do 4 sata obilazite park. Krka je bliže Splitu od Plitvičkih jezera, pa je dan nešto opušteniji.",
"What is included in the price?": "Što je uključeno u cijenu?",
"Your private vehicle, English-speaking driver, all fuel and tolls, and hotel/accommodation pickup and drop-off in Split are included. Krka National Park entrance tickets, and the optional Visovac Island boat trip, are purchased separately at the park.": "Uključeni su privatno vozilo, vozač, gorivo i cestarina te preuzimanje i povratak do hotela ili smještaja u Splitu. Ulaznice za Nacionalni park Krka i vožnja brodom do Visovca po želji kupuju se zasebno u parku.",
"Can I swim at Krka National Park?": "Može li se kupati u Nacionalnom parku Krka?",
"Swimming at Skradinski Buk has not been permitted since 2021, as part of the park's conservation efforts. You can still get close to the falls on the wooden boardwalks, and swimming remains possible at some other points along the Krka river outside the protected area.": "Kupanje na Skradinskom buku nije dopušteno od 2021., radi zaštite parka. Slapovima se i dalje možete približiti drvenim stazama, a kupati se može na nekim drugim mjestima uz rijeku Krku izvan zaštićenog područja.",
"Is Krka a good alternative to Plitvice Lakes?": "Je li Krka dobra zamjena za Plitvička jezera?",
"Krka is closer to Split, generally quieter, and centres on one spectacular waterfall system rather than a chain of lakes, a good choice if you'd like a shorter day or have already visited Plitvice. Many guests who have time for both say the two parks feel genuinely different rather than repetitive.": "Krka je bliže Splitu, obično mirnija i usmjerena na jedan spektakularan sustav slapova umjesto niza jezera, pa je dobar izbor ako želite kraći dan ili ste Plitvice već vidjeli. Mnogi gosti koji stignu oba parka kažu da su stvarno različiti, a ne slični.",
"Is the boat ride to Visovac Island included?": "Je li uključena vožnja brodom do Visovca?",
"The Visovac Island boat trip is optional and booked separately at the park, usually departing from Skradin. Let your driver know in advance if you'd like time built into your day for it.": "Vožnja brodom do Visovca nije obvezna i plaća se zasebno u parku, a brodovi obično polaze iz Skradina. Javite vozaču unaprijed ako želite da u planu dana ostane vremena za nju.",
"Skradinski Buk waterfalls cascading through Krka National Park": "Slapovi Skradinskog buka u Nacionalnom parku Krka",
"Split → Krka National Park": "Split → Nacionalni park Krka",
"Private Day Trip to Krka National Park": "Privatni izlet u Nacionalni park Krka",
"8–10 hrs": "8–10 h",
"Round Trip Duration": "Trajanje izleta",
"~85 km": "~85 km",
"Each Way": "U jednom smjeru",
"Private": "Privatno",
"Just Your Group": "Samo vaša grupa",
"Closer Than Plitvice": "Bliže od Plitvica",
"Overview": "Ukratko",
"Waterfalls, Without the Long Drive": "Slapovi bez duge vožnje",
"Krka National Park is built around the Krka River as it drops through a series of travertine cascades, the largest and most famous being Skradinski Buk, a wide curtain of waterfalls reached by wooden boardwalks that wind through the forest and along the water's edge. At under half the driving distance of Plitvice Lakes, Krka makes for a noticeably more relaxed day: less time in the car, more time actually at the park, and still home the same afternoon with energy left over. The riverside town of Skradin, where most visits begin, adds a pleasant stop in its own right, a small stone-built harbour town worth a slow coffee before or after the walk. For visitors short on time, or anyone who's already done the longer trip to Plitvice, Krka is consistently the easier, more flexible choice without giving up the “Croatian waterfalls” experience people come here for.": "Nacionalni park Krka nastao je oko rijeke Krke, koja se spušta nizom sedrenih slapova. Najveći i najpoznatiji je Skradinski buk, široka zavjesa slapova do koje vode drvene staze kroz šumu i uz samu vodu. S manje od pola vožnje koju traže Plitvička jezera, Krka je primjetno opušteniji dan: manje vremena u autu, više vremena u parku i povratak isto popodne, s dovoljno snage za večer. Skradin, gradić uz rijeku odakle počinje većina posjeta, i sam je ugodno stajanje: mala kamena luka u kojoj vrijedi popiti kavu prije ili poslije šetnje. Za one koji nemaju puno vremena, ili su već bili na Plitvicama, Krka je jednostavniji i fleksibilniji izbor, a slapovi zbog kojih ljudi dolaze tu su.",
"What's Included": "Što je uključeno",
"Private vehicle for your group only, no shared shuttle": "Privatno vozilo samo za vašu grupu, bez zajedničkog prijevoza",
"English-speaking driver for the full day": "Vozač na raspolaganju cijeli dan",
"Hotel or accommodation pickup and drop-off in Split": "Preuzimanje i povratak do hotela ili smještaja u Splitu",
"All fuel, tolls and parking at the park": "Gorivo, cestarina i parking kod parka",
"Flexible time inside the park. Your driver waits": "Fleksibilno vrijeme u parku. Vozač vas čeka",
"Bottled water for the journey": "Voda za put",
"Not included: Krka National Park entrance tickets and the optional Visovac Island boat trip, both purchased separately at the park.": "Nije uključeno: ulaznice za Nacionalni park Krka i vožnja brodom do Visovca po želji, koje se kupuju zasebno u parku.",
"Car": "Auto",
"Škoda Superb": "Škoda Superb",
"Pickup Address": "Adresa preuzimanja",
"Hotel name or full address in Split": "Ime hotela ili puna adresa u Splitu",
"Child seats, special requests...": "Dječje sjedalice, posebni zahtjevi...",
"Book This Trip · €255": "Rezerviraj izlet · 255 €",
"Booking confirmed!": "Rezervacija je zaprimljena!",
"A confirmation has been sent to your email with the full trip details.": "Na vaš e-mail poslali smo potvrdu sa svim detaljima izleta.",
"Ask a Question on WhatsApp": "Pitajte nas na WhatsApp",
"Fixed price for the day · driver waits at the park · flexible pickup time.": "Fiksna cijena za cijeli dan · vozač čeka kod parka · fleksibilno vrijeme polaska.",
"Suggested Itinerary": "Prijedlog plana",
"A Typical Day at Krka": "Kako izgleda dan na Krki",
"Pickup in Split": "Polazak iz Splita",
"A later start than Plitvice is comfortable here, given the shorter drive. Your driver collects you from your hotel or apartment.": "Zbog kraće vožnje ovdje možete krenuti kasnije nego na Plitvice. Vozač vas preuzima ispred hotela ili apartmana.",
"Arrival Near Skradin": "Dolazak kod Skradina",
"Your driver drops you at the park entrance and confirms a return time. Entrance tickets are purchased at the gate.": "Vozač vas ostavlja na ulazu u park i dogovara vrijeme povratka. Ulaznice se kupuju na ulazu.",
"Skradinski Buk & Walking Trails": "Skradinski buk i pješačke staze",
"Follow the boardwalks along and across the falls, with time for the optional boat trip to Visovac Island if you'd like to add it.": "Prošećite drvenim stazama uz slapove i preko njih, uz vremena za vožnju brodom do Visovca ako je želite.",
"Lunch in Skradin": "Ručak u Skradinu",
"The riverside town makes a pleasant lunch stop before the drive back, several restaurants sit right on the harbour.": "Gradić uz rijeku ugodno je mjesto za ručak prije povratka; nekoliko restorana nalazi se odmah uz luku.",
"Return Drive to Split": "Povratak u Split",
"Your driver is waiting at the agreed time for the shorter drive back to Split.": "Vozač vas čeka u dogovoreno vrijeme za kraću vožnju natrag u Split.",
"Drop-off in Split": "Dolazak u Split",
"Back at your accommodation by mid-to-late afternoon, plenty of the evening still ahead.": "U smještaju ste sredinom ili krajem popodneva, s cijelom večeri pred vama.",
"This is a suggested schedule: departure time, lunch stop and time spent in the park are all flexible and arranged directly with your driver.": "Ovo je prijedlog rasporeda: vrijeme polaska, stajanje za ručak i vrijeme u parku fleksibilni su i dogovarate ih izravno s vozačem.",

# plitvice
"Plitvice Day Trip from Split, Private Tour | Airport Split Transfer": "Izlet na Plitvice iz Splita, privatni prijevoz | Airport Split Transfer",
"Private day trip from Split to Plitvice Lakes National Park with an English-speaking driver. Fixed price, flexible pickup, 10-12 hours round trip. Book online.": "Privatni izlet iz Splita u Nacionalni park Plitvička jezera s vozačem. Fiksna cijena, fleksibilno vrijeme polaska, 10 do 12 sati u oba smjera. Rezervirajte online.",
"Plitvice Lakes Day Trip from Split": "Izlet iz Splita na Plitvička jezera",
"A private, full-day excursion from Split to Plitvice Lakes National Park with an English-speaking driver, round-trip transfer and flexible pickup time.": "Privatni cjelodnevni izlet iz Splita u Nacionalni park Plitvička jezera s vozačem, prijevozom u oba smjera i fleksibilnim vremenom polaska.",
"16 terraced lakes connected by waterfalls and wooden walking trails.": "16 kaskadnih jezera povezanih slapovima i drvenim stazama.",
"How long does the Plitvice Lakes day trip take?": "Koliko traje izlet na Plitvička jezera?",
"The full round trip from Split takes approximately 10–12 hours, including around 4–5 hours to explore the national park itself. Exact timing depends on your pickup location and how long you'd like to spend inside the park.": "Cijeli izlet iz Splita traje otprilike 10 do 12 sati, od čega oko 4 do 5 sati obilazite sam nacionalni park. Točno trajanje ovisi o mjestu polaska i o tome koliko dugo želite ostati u parku.",
"Your private vehicle, English-speaking driver, all fuel and tolls, and hotel/accommodation pickup and drop-off in Split are included. Plitvice Lakes National Park entrance tickets are purchased separately at the park. We're happy to advise on current prices when you book.": "Uključeni su privatno vozilo, vozač, gorivo i cestarina te preuzimanje i povratak do hotela ili smještaja u Splitu. Ulaznice za Nacionalni park Plitvička jezera kupuju se zasebno u parku. Pri rezervaciji rado ćemo vam reći aktualne cijene.",
"Is this a private tour or a shared group tour?": "Je li ovo privatni ili grupni izlet?",
"This is a fully private excursion: just your group and your driver, with no other travellers sharing the vehicle. You set the pace once inside the park.": "Ovo je potpuno privatni izlet: samo vaša grupa i vozač, bez drugih putnika u vozilu. U parku sami određujete tempo.",
"How much walking is involved at Plitvice Lakes?": "Koliko se hoda na Plitvičkim jezerima?",
"The park is explored on foot via wooden boardwalks and trails, with routes ranging from around 2 to 8 kilometres depending on which route you choose. Trails are mostly flat with some gentle inclines, and electric boats and a park shuttle bus cover the longer stretches.": "Park se obilazi pješice drvenim stazama i putovima, a rute su duge od oko 2 do 8 kilometara, ovisno o tome koju odaberete. Staze su uglavnom ravne uz pokoji blagi uspon, a dulje dionice pokrivaju električni brodovi i panoramski vlakić.",
"Can I book a return transfer separately, or is it always round trip?": "Mogu li rezervirati samo jedan smjer ili je izlet uvijek u oba smjera?",
"Day trips are booked as a complete round trip. Your driver waits at the park and brings you back to Split the same day. If you only need a one-way transfer to Plitvice, see our regular airport transfer page instead.": "Izleti se rezerviraju kao cijela vožnja u oba smjera. Vozač vas čeka kod parka i vraća u Split istog dana. Ako trebate samo prijevoz u jednom smjeru do Plitvica, pogledajte našu stranicu za obične transfere.",
"Turquoise terraced lakes and waterfalls at Plitvice Lakes National Park": "Tirkizna kaskadna jezera i slapovi u Nacionalnom parku Plitvička jezera",
"Split → Plitvice Lakes National Park": "Split → Nacionalni park Plitvička jezera",
"Private Day Trip to Plitvice Lakes": "Privatni izlet na Plitvička jezera",
"10–12 hrs": "10–12 h",
"~140 km": "~140 km",
"Day Trip from Split": "Izlet iz Splita",
"Croatia's Most Famous National Park": "Najpoznatiji nacionalni park u Hrvatskoj",
"Plitvice Lakes National Park is Croatia's oldest and largest national park, and a UNESCO World Heritage Site since 1979. Sixteen terraced lakes, ranging from deep blue to vivid turquoise, cascade into one another through a series of waterfalls, all connected by wooden boardwalks and forest trails that wind through beech and fir woodland. It's a full day out from Split, around two and a half hours' drive each way, which is exactly why most visitors prefer a private day trip over trying to arrange it independently: an early departure beats the tour-bus crowds to the upper lakes, and a driver who knows the road means the long drive itself is comfortable rather than tiring. Because the park sits inland, well away from the coast, this is also one of the few day trips from Split that shows a completely different side of Croatia, dense forest, karst limestone, and water in every direction, a genuine change of scenery from the Dalmatian coastline.": "Nacionalni park Plitvička jezera najstariji je i najveći nacionalni park u Hrvatskoj, a od 1979. nalazi se na UNESCO-ovu popisu svjetske baštine. Šesnaest kaskadnih jezera, od tamnoplave do jarko tirkizne boje, preljevaju se jedno u drugo nizom slapova, a povezuju ih drvene staze i šumski putovi kroz bukovu i jelovu šumu. Iz Splita je to cijeli dan, oko dva i pol sata vožnje u svakom smjeru, i upravo zato većina posjetitelja radije bira privatni izlet nego da sve organizira sama: rani polazak znači da ste na gornjim jezerima prije autobusa s grupama, a vozač koji poznaje cestu čini dugu vožnju ugodnom umjesto zamornom. Budući da je park u unutrašnjosti, daleko od mora, ovo je i jedan od rijetkih izleta iz Splita koji pokazuje potpuno drugačiju Hrvatsku: gustu šumu, krš i vodu na sve strane, pravu promjenu u odnosu na dalmatinsku obalu.",
"Two Ways to Visit": "Dva načina posjeta",
"Plitvice Lakes from Split": "Plitvička jezera iz Splita",
"Private One-Way Transfer": "Privatni transfer u jednom smjeru",
"From €430": "Od 430 €",
"A direct private transfer from Split Airport or Split to Plitvice Lakes, with drop-off at the park entrance or your accommodation. Ideal if you're staying near the lakes or continuing to Zagreb.": "Izravni privatni transfer od Zračne luke Split ili Splita do Plitvičkih jezera, s dolaskom do ulaza u park ili do smještaja. Idealno ako odsjedate kraj jezera ili nastavljate prema Zagrebu.",
"Private Full-Day Trip": "Privatni cjelodnevni izlet",
"A round trip from Split: your driver waits while you explore the lakes and brings you back the same day. 10–12 hours, fixed price for the whole day.": "Izlet iz Splita u oba smjera: vozač vas čeka dok obilazite jezera i vraća vas istog dana. 10 do 12 sati, fiksna cijena za cijeli dan.",
"Not included: Plitvice Lakes National Park entrance tickets, purchased on arrival or in advance directly with the park (prices vary by season), and food/drinks inside the park.": "Nije uključeno: ulaznice za Nacionalni park Plitvička jezera, koje se kupuju na ulazu ili unaprijed izravno od parka (cijene ovise o sezoni), te hrana i piće u parku.",
"Book This Trip · €430": "Rezerviraj izlet · 430 €",
"A Typical Day at Plitvice": "Kako izgleda dan na Plitvicama",
"Your driver collects you from your hotel or apartment at an early time to beat the tour-bus crowds to the park entrance.": "Vozač vas preuzima rano ispred hotela ili apartmana, da do ulaza u park stignete prije autobusa s grupama.",
"Arrival at Plitvice Lakes": "Dolazak na Plitvička jezera",
"Explore the Lakes": "Obilazak jezera",
"Walk the wooden boardwalks past the Lower and Upper Lakes, cross the electric boat between the two halves of the park, and stop as often as you like for photos.": "Prošećite drvenim stazama uz Donja i Gornja jezera, prijeđite električnim brodom između dva dijela parka i zastanite za fotografije kad god poželite.",
"Lunch Break": "Pauza za ručak",
"A short stop at one of the restaurants near the park entrance, or a picnic if you'd prefer, entirely up to you.": "Kratko stajanje u jednom od restorana kraj ulaza u park ili piknik, kako vam više odgovara.",
"Your driver is waiting at the agreed time for the drive back, with a short stop en route if you'd like one.": "Vozač vas čeka u dogovoreno vrijeme za povratak, uz kratko stajanje usput ako želite.",
"Back at your accommodation by early evening, with the rest of the day free.": "U smještaju ste do ranih večernjih sati, a ostatak dana je slobodan.",
"Day trips are booked as a complete round trip. Your driver waits at the park and brings you back to Split the same day. If you only need a one-way transfer to Plitvice, see our": "Izleti se rezerviraju kao cijela vožnja u oba smjera. Vozač vas čeka kod parka i vraća u Split istog dana. Ako trebate samo prijevoz u jednom smjeru do Plitvica, pogledajte našu",
"regular airport transfer page": "stranicu za obične transfere",
"instead.": ".",
}
JSR = {
"btn.dataset.label + ' · €' + price": "btn.dataset.label + ' · ' + price + ' €'",
"submitBtn.textContent = 'Sending...'": "submitBtn.textContent = 'Šaljem...'",
"alert('Something went wrong sending your request. Please try again or contact us on WhatsApp.')": "alert('Nešto je pošlo po krivu pri slanju zahtjeva. Pokušajte ponovno ili nam se javite na WhatsApp.')",
}
