# Marina pages (phase 2)
FILES = ["aci-marina-split", "aci-marina-trogir", "marina-agana", "marina-baotic", "marina-dalmacija", "marina-frapa", "marina-kastela", "marina-kornati", "marina-mandalina"]
# (EN name, genitive after "do")
M = [("ACI Marina Split", "ACI Marine Split"), ("ACI Marina Trogir", "ACI Marine Trogir"), ("Marina Agana", "Marine Agana"),
     ("Marina Baotić", "Marine Baotić"), ("Marina Dalmacija", "Marine Dalmacija"), ("Marina Frapa", "Marine Frapa"),
     ("Marina Kaštela", "Marine Kaštela"), ("Marina Kornati", "Marine Kornati"), ("Marina Mandalina", "Marine Mandalina")]
T = {}
for f in FILES:
    T[f"About@@{f}.html"] = "Oko"
    T[f"private day trip@@{f}.html"] = "privatni izlet"
for en, gen in M:
    T[f"Split Airport to {en} | Airport Split Transfer"] = f"Transfer od Zračne luke Split do {gen} | Airport Split Transfer"
    T[f"How long is the drive from Split Airport to {en}?"] = f"Koliko traje vožnja od Zračne luke Split do {gen}?"
    T[f"How much does the transfer to {en} cost?"] = f"Koliko košta transfer do {gen}?"
    T[f"Split Airport → {en}"] = f"Zračna luka Split → {en}"
    T[f"Split Airport to {en}"] = f"Od Zračne luke Split do {gen}"
    T[f"About {en}"] = f"O marini: {en}"
for tm, km, tmh in [("30 min", "22 km", "30 min"), ("15 min", "8 km", "15 min"), ("25 min", "20 km", "25 min"), ("15 min", "10 km", "15 min"),
                    ("1 h 30 min", "135 km", "1 h 30 min"), ("35 min", "34 km", "35 min"), ("15–20 min", "12 km", "15 do 20 min"),
                    ("1 h 10 min", "100 km", "1 h 10 min"), ("55 min", "55 km", "55 min")]:
    T[f"Around {tm} in normal traffic, about {km}. On summer Saturdays, when the charter crews change, allow a little more."] = f"Oko {tmh} u normalnom prometu, otprilike {km}. Ljeti subotom, kad se mijenjaju charter posade, računajte na malo više."
T.update({
"Private transfer from Split Airport to ACI Marina Split for charter crews: about 30 minutes, fixed price per vehicle, vans for up to 8 and meet and greet.": "Privatni transfer od Zračne luke Split do ACI Marine Split za charter posade: oko 30 minuta, fiksna cijena po vozilu, kombiji za do 8 osoba i doček.",
"The price is per vehicle and fixed before you travel, with tolls, fuel and meet and greet included. Tap \"Get your fixed price\" and enter your flight to see the exact price for a sedan or a van. The marina is already filled in.": "Cijena je po vozilu i fiksna prije vožnje, s uključenom cestarinom, gorivom i dočekom. Kliknite \"Izračunaj fiksnu cijenu\" i upišite let da vidite točnu cijenu za limuzinu ili kombi. Marina je već upisana.",
"Can you time the pickup around our charter check-in?": "Možete li preuzimanje uskladiti s ukrcajem na charter?",
"Yes. Give us your flight number and check-in time when you book. We follow the flight, and if you land early we can stop on the way, for example to buy provisions.": "Da. Pri rezervaciji nam pošaljite broj leta i vrijeme ukrcaja. Pratimo let, a ako sletite ranije, možemo usput stati, na primjer za nabavu namirnica.",
"We are eight people with a lot of luggage. Will one vehicle do?": "Osmero nas je s puno prtljage. Je li dovoljno jedno vozilo?",
"Yes. The Renault Trafic takes up to 8 passengers and the Mercedes V-Class up to 7, both with room for sailing bags, so the whole crew travels together.": "Da. Renault Trafic prima do 8 putnika, a Mercedes V-Class do 7, oba s mjestom za jedriličarske torbe, pa cijela posada putuje zajedno.",
"Can we book the ride back to the airport at the end of the charter?": "Možemo li rezervirati i povratak na aerodrom na kraju chartera?",
"Yes. Choose \"Return\" in the form to book both legs together and get 5% off the total. We will suggest a pickup time based on your check-out and your flight.": "Da. U obrascu odaberite \"Povratna\", rezervirajte obje vožnje odjednom i dobijte 5% popusta na ukupnu cijenu. Vrijeme preuzimanja predložit ćemo prema vremenu iskrcaja i letu.",
"ACI Marina Split is on the western side of Split's harbour, below Marjan hill and a short walk from the Riva and Diocletian's Palace.": "ACI Marina Split nalazi se na zapadnoj strani splitske luke, podno Marjana, na kratkoj šetnji od Rive i Dioklecijanove palače.",
"Vans for crews of up to": "Kombiji za posade do",
"Getting to the marina": "Kako do marine",
"The marina is about 22 km from the airport, on the far side of the city. The drive usually takes around 30 minutes along the coast road and round the harbour. On summer Saturdays, traffic through Split can add a few minutes, and we allow for it in your pickup.": "Marina je oko 22 km od aerodroma, na drugom kraju grada. Vožnja obalnom cestom i oko luke obično traje oko 30 minuta. Ljeti subotom promet kroz Split može dodati nekoliko minuta, a mi to uračunamo u vrijeme preuzimanja.",
"Most charter boats here change crews on Saturday. The old crew leaves in the morning and the new one usually boards in the afternoon, so Saturday is the busiest day on every road to the marinas. Tell us your flight and your check-in time and we plan the pickup around both. If you land hours before you can board, we can stop on the way for provisioning.": "Većina charter brodova ovdje mijenja posadu subotom. Stara posada odlazi ujutro, a nova se obično ukrcava poslijepodne, pa je subota najprometniji dan na svim cestama prema marinama. Javite nam let i vrijeme ukrcaja i preuzimanje ćemo planirati prema oboje. Ako sletite satima prije ukrcaja, možemo usput stati za nabavu namirnica.",
"Crews usually travel as six to eight people with soft bags and boxes of provisions. Rather than splitting into two taxis, one Mercedes V-Class (up to 7) or Renault Trafic (up to 8) takes everyone and the luggage, and the price is per vehicle, not per person.": "Posade obično putuju u šestero do osmero, s mekim torbama i kutijama namirnica. Umjesto dva taksija, jedan Mercedes V-Class (do 7 osoba) ili Renault Trafic (do 8 osoba) vozi sve s prtljagom, a cijena je po vozilu, a ne po osobi.",
"Tap the button above and add your flight. The marina is already filled in, and the price is fixed when you book.": "Kliknite gumb iznad i dodajte let. Marina je već upisana, a cijena je fiksna od trenutka rezervacije.",
"Straight to the marina": "Ravno u marinu",
"No other passengers and no stops unless you ask. We drop you at reception or the charter office.": "Bez drugih putnika i bez stajanja osim ako ne zatražite. Ostavljamo vas na recepciji ili kod ureda charter tvrtke.",
"ACI Marina Split belongs to the ACI chain of marinas along the Croatian coast and is one of the busiest charter bases in the city. For a first or last night in Split it is hard to beat: the old town, Diocletian's Palace and the Riva are a short walk away, and the ferry port is just across the harbour. Many crews spend an evening in the old town before sailing out to Šolta, Brač or Hvar the next morning.": "ACI Marina Split dio je lanca ACI marina duž hrvatske obale i jedna od najprometnijih charter baza u gradu. Za prvu ili zadnju noć u Splitu teško ju je nadmašiti: stara jezgra, Dioklecijanova palača i Riva na kratkoj su šetnji, a trajektna luka odmah preko lučkog bazena. Mnoge posade provedu večer u starom gradu prije nego sljedećeg jutra isplove prema Šolti, Braču ili Hvaru.",
"Heading somewhere else? See": "Idete negdje drugdje? Pogledajte",
"all our routes from Split Airport": "sve naše rute sa Zračne luke Split",
", or add a": " ili dodajte",
"before or after your charter.": "prije ili poslije chartera.",
"Private transfer from Split Airport to ACI Marina Trogir on Čiovo: about 15 minutes, fixed price per vehicle, vans for crews of up to 8, meet and greet.": "Privatni transfer od Zračne luke Split do ACI Marine Trogir na Čiovu: oko 15 minuta, fiksna cijena po vozilu, kombiji za posade do 8 osoba i doček.",
"ACI Marina Trogir is on Čiovo island, across a narrow channel from Trogir's UNESCO-listed old town and only minutes from Split Airport.": "ACI Marina Trogir nalazi se na Čiovu, preko uskog kanala od stare jezgre Trogira pod zaštitom UNESCO-a, samo nekoliko minuta od Zračne luke Split.",
"8 km": "8 km",
"This is one of the shortest marina transfers on the coast: about 8 km, usually around 15 minutes, over the bridge from the mainland onto Čiovo. The bridges around Trogir can slow down on Saturday afternoons, so we leave a little margin on changeover day.": "Ovo je jedan od najkraćih transfera do marine na obali: oko 8 km, obično oko 15 minuta, preko mosta s kopna na Čiovo. Mostovi oko Trogira subotom poslijepodne znaju biti spori, pa na dan smjene posada ostavljamo malo rezerve.",
"ACI Marina Trogir faces the old town across the Trogir channel, so the cathedral, the Kamerlengo fortress and the waterfront restaurants are a short walk over the bridge. Charter crews like it because the berths are sheltered and the islands are close: Šolta and the Drvenik islands are a short sail away, and Split's harbour is just to the east. With the airport so near, it also suits crews landing late on Friday or flying out early on the last Saturday.": "ACI Marina Trogir gleda na staru jezgru preko Trogirskog kanala, pa su katedrala, tvrđava Kamerlengo i restorani na rivi na kratkoj šetnji preko mosta. Charter posade je vole jer su vezovi zaštićeni, a otoci blizu: Šolta i Drvenik na kratkoj su plovidbi, a splitska luka odmah istočno. Zbog blizine aerodroma odgovara i posadama koje slijeću kasno u petak ili odlijeću rano zadnje subote.",
"Private transfer from Split Airport to Marina Agana in the village of Marina: about 25 minutes, fixed price per vehicle, vans for up to 8, meet and greet.": "Privatni transfer od Zračne luke Split do Marine Agana u mjestu Marina: oko 25 minuta, fiksna cijena po vozilu, kombiji za do 8 osoba i doček.",
"Marina Agana sits in a sheltered bay in the village of Marina, west of Trogir: a quieter charter base within easy reach of Split Airport.": "Marina Agana nalazi se u zaštićenoj uvali u mjestu Marina, zapadno od Trogira: mirnija charter baza nadohvat Zračne luke Split.",
"The marina is about 20 km from the airport. The drive usually takes around 25 minutes, past Trogir and along the coast towards Vinišće and Marina, with the last stretch running beside the bay.": "Marina je oko 20 km od aerodroma. Vožnja obično traje oko 25 minuta, pokraj Trogira i uz obalu prema Vinišću i Marini, a zadnja dionica vodi uz samu uvalu.",
"Marina Agana is smaller and calmer than the big marinas around Split and Trogir, set at the head of a deep, protected bay. The village of Marina has a few restaurants and shops along the waterfront, and Trogir's old town is a short drive back towards the airport. Crews often choose it for a relaxed start: less Saturday bustle and quick access to open water and the islands to the west.": "Marina Agana manja je i mirnija od velikih marina oko Splita i Trogira, smještena na dnu duboke i zaštićene uvale. U mjestu Marina ima nekoliko restorana i trgovina uz rivu, a stara jezgra Trogira kratka je vožnja natrag prema aerodromu. Posade je često biraju za opušten početak: manje subotnje gužve i brz izlazak na otvoreno more i prema otocima na zapadu.",
"Private transfer from Split Airport to Marina Baotić in Seget Donji: about 15 minutes, fixed price per vehicle, vans for crews of up to 8, meet and greet.": "Privatni transfer od Zračne luke Split do Marine Baotić u Segetu Donjem: oko 15 minuta, fiksna cijena po vozilu, kombiji za posade do 8 osoba i doček.",
"Marina Baotić is in Seget Donji, just west of Trogir, and is one of the largest charter bases near Split Airport.": "Marina Baotić nalazi se u Segetu Donjem, odmah zapadno od Trogira, i jedna je od najvećih charter baza blizu Zračne luke Split.",
"10 km": "10 km",
"The marina is about 10 km from the airport, and the drive usually takes around 15 minutes along the coast road past Trogir. Changeover Saturdays bring a lot of charter traffic to this stretch, so we plan the pickup with that in mind.": "Marina je oko 10 km od aerodroma, a vožnja obalnom cestom pokraj Trogira obično traje oko 15 minuta. Subotom, kad se mijenjaju posade, na ovoj dionici je puno charter prometa, pa preuzimanje planiramo s tim na umu.",
"Marina Baotić is a large, modern marina on the Trogir Riviera. Many charter fleets are based here, and from spring to autumn it is busy every Saturday. Trogir's old town is a short drive or a pleasant walk along the coast, which makes it easy to spend the evening before departure there. From the marina, the Drvenik islands, Šolta and the open water towards Hvar and Vis are all an easy first day's sail.": "Marina Baotić je velika i moderna marina na Trogirskoj rivijeri. Ovdje je baza mnogih charter flota, pa je od proljeća do jeseni svake subote puna. Stara jezgra Trogira kratka je vožnja ili ugodna šetnja uz more, pa je lako ondje provesti večer prije isplovljavanja. Iz marine su Drvenik, Šolta i otvoreno more prema Hvaru i Visu lagana plovidba za prvi dan.",
"Private transfer from Split Airport to D-Marin Dalmacija in Sukošan: about 1 h 30 min on the A1, fixed price per vehicle, vans for up to 8, meet and greet.": "Privatni transfer od Zračne luke Split do D-Marin Dalmacija u Sukošanu: oko 1 h 30 min autocestom A1, fiksna cijena po vozilu, kombiji za do 8 osoba i doček.",
"Marina Dalmacija (D-Marin Dalmacija) in Sukošan, south of Zadar, is one of the largest marinas on the Adriatic and a major charter base for the Kornati islands.": "Marina Dalmacija (D-Marin Dalmacija) u Sukošanu, južno od Zadra, jedna je od najvećih marina na Jadranu i velika charter baza za Kornate.",
"135 km": "135 km",
"1 h 30 min": "1 h 30 min",
"The marina is about 135 km from Split Airport, and the drive usually takes around 1 hour 30 minutes on the A1 motorway towards Zadar. Zadar Airport is closer to Sukošan, but many crews fly into Split for the wider choice of flights, and a private transfer makes the longer drive easy.": "Marina je oko 135 km od Zračne luke Split, a vožnja autocestom A1 prema Zadru obično traje oko 1 sat i 30 minuta. Zračna luka Zadar bliža je Sukošanu, ali mnoge posade slijeću u Split zbog većeg izbora letova, a privatni transfer olakšava dulju vožnju.",
"Marina Dalmacija is one of the biggest marinas in Croatia, with a very large charter fleet and full services on site. It is the classic starting point for sailing the Kornati islands and the Zadar archipelago. Zadar's old town, with the Sea Organ and the Greeting to the Sun, is fifteen to twenty minutes away by car if you want an evening ashore before you sail.": "Marina Dalmacija jedna je od najvećih marina u Hrvatskoj, s vrlo velikom charter flotom i svim uslugama na licu mjesta. Klasična je polazna točka za plovidbu Kornatima i zadarskim arhipelagom. Stara jezgra Zadra, s Morskim orguljama i Pozdravom Suncu, udaljena je petnaestak do dvadeset minuta autom ako želite večer na kopnu prije isplovljavanja.",
"Private transfer from Split Airport to Marina Frapa in Rogoznica: about 35 minutes, fixed price per vehicle, vans for crews of up to 8, meet and greet.": "Privatni transfer od Zračne luke Split do Marine Frapa u Rogoznici: oko 35 minuta, fiksna cijena po vozilu, kombiji za posade do 8 osoba i doček.",
"Split Airport to Marina Frapa, Rogoznica | Airport Split Transfer": "Transfer od Zračne luke Split do Marine Frapa, Rogoznica | Airport Split Transfer",
"Marina Frapa sits in a sheltered bay at Rogoznica, on the coast between Trogir and Šibenik, and is one of the most awarded marinas on the Adriatic.": "Marina Frapa nalazi se u zaštićenoj uvali u Rogoznici, na obali između Trogira i Šibenika, i jedna je od najnagrađivanijih marina na Jadranu.",
"34 km": "34 km",
"35 min": "35 min",
"The marina is about 34 km north of the airport. The drive usually takes around 35 minutes, mostly on the coast road past Trogir and Seget, then a short turn off towards Rogoznica. The marina has its own entrance before the town centre, and our drivers know it, which matters on a busy Saturday.": "Marina je oko 34 km sjeverno od aerodroma. Vožnja obično traje oko 35 minuta, većinom obalnom cestom pokraj Trogira i Segeta, a zatim kratkim skretanjem prema Rogoznici. Marina ima vlastiti ulaz prije centra mjesta, a naši ga vozači znaju, što je važno subotom kad je gužva.",
"Marina Frapa fills the quieter of Rogoznica's two bays, with restaurants and a boatyard on site, and it has collected more \"best marina\" awards than almost any other on the Adriatic. The small old town of Rogoznica, on its narrow isthmus, is a short walk away. From here crews head north to the Šibenik islands and the Kornati, or south towards Šolta and Hvar. Staying in town instead? See": "Marina Frapa zauzima mirniju od dvije rogozničke uvale, s restoranima i brodogradilištem, a skupila je više nagrada za \"najbolju marinu\" od gotovo bilo koje druge na Jadranu. Mala stara jezgra Rogoznice, na uskoj prevlaci, na kratkoj je šetnji. Odavde posade plove na sjever prema šibenskim otocima i Kornatima ili na jug prema Šolti i Hvaru. Odsjedate u mjestu? Pogledajte",
"transfers to Rogoznica": "transfere do Rogoznice",
"Private transfer from Split Airport to Marina Kaštela in Kaštel Gomilica: about 15 to 20 minutes, fixed price per vehicle, vans for up to 8, meet and greet.": "Privatni transfer od Zračne luke Split do Marine Kaštela u Kaštel Gomilici: oko 15 do 20 minuta, fiksna cijena po vozilu, kombiji za do 8 osoba i doček.",
"Marina Kaštela is in Kaštel Gomilica on the bay between Split and Trogir, one of the closest charter marinas to Split Airport.": "Marina Kaštela nalazi se u Kaštel Gomilici, u zaljevu između Splita i Trogira, i jedna je od charter marina najbližih Zračnoj luci Split.",
"15–20 min": "15–20 min",
"The marina is about 12 km from the airport, and the drive usually takes 15 to 20 minutes along the main road above the Kaštela villages. The airport sits at the western end of the same bay, so this is one of the quickest ways from the plane to the boat.": "Marina je oko 12 km od aerodroma, a vožnja glavnom cestom iznad kaštelanskih mjesta obično traje 15 do 20 minuta. Aerodrom je na zapadnom kraju istog zaljeva, pa je ovo jedan od najbržih puteva od aviona do broda.",
"Marina Kaštela is one of the larger marinas around Split and a base for several charter fleets. It is in Kaštel Gomilica, near the little Kaštilac fortress that appeared as Braavos in Game of Thrones, with cafés and a seafront promenade a short walk away. Split is about twenty minutes by road, and the sail out of the bay towards Šolta and Brač is short and sheltered.": "Marina Kaštela jedna je od većih marina oko Splita i baza nekoliko charter flota. Nalazi se u Kaštel Gomilici, blizu male utvrde Kaštilac koja je u Igri prijestolja glumila Braavos, s kafićima i šetnicom uz more na kratkoj šetnji. Split je dvadesetak minuta vožnje, a plovidba iz zaljeva prema Šolti i Braču kratka je i zaštićena.",
"Split Airport to Marina Kornati, Biograd | Airport Split Transfer": "Transfer od Zračne luke Split do Marine Kornati, Biograd | Airport Split Transfer",
"Private transfer from Split Airport to Marina Kornati in Biograd na Moru: about 1 h 10 min, fixed price per vehicle, vans for crews of up to 8.": "Privatni transfer od Zračne luke Split do Marine Kornati u Biogradu na Moru: oko 1 h 10 min, fiksna cijena po vozilu, kombiji za posade do 8 osoba.",
"Marina Kornati is in Biograd na Moru, roughly halfway between Split and Zadar, and is one of the largest charter bases in Croatia.": "Marina Kornati nalazi se u Biogradu na Moru, otprilike na pola puta između Splita i Zadra, i jedna je od najvećih charter baza u Hrvatskoj.",
"The marina is about 100 km north of the airport. Most of the drive is on the motorway, so it usually takes around 1 h 10 min, a little longer on summer Saturdays when charter traffic peaks. It is a longer ride than to most marinas near Split, so tell us if you would like to stop for provisions on the way.": "Marina je oko 100 km sjeverno od aerodroma. Većina vožnje je autocestom, pa obično traje oko 1 h 10 min, a ljeti subotom, kad je charter promet najgušći, malo dulje. Vožnja je dulja nego do većine marina blizu Splita, pa nam javite želite li usput stati po namirnice.",
"Marina Kornati sits right by the centre of Biograd na Moru, with cafés and shops a short walk away and the island of Pašman just across the channel. It is the closest large marina to Kornati National Park and Telašćica Nature Park, which is why so many sailing weeks start here. Staying in town instead? See": "Marina Kornati nalazi se odmah uz centar Biograda na Moru, s kafićima i trgovinama na kratkoj šetnji i otokom Pašmanom preko kanala. To je najbliža velika marina Nacionalnom parku Kornati i Parku prirode Telašćica, pa ovdje počinje toliko jedriličarskih tjedana. Odsjedate u mjestu? Pogledajte",
"transfers to Biograd na Moru": "transfere do Biograda na Moru",
"Private transfer from Split Airport to D-Marin Mandalina in Šibenik: about 55 minutes, fixed price per vehicle, vans for crews of up to 8, meet and greet.": "Privatni transfer od Zračne luke Split do D-Marin Mandalina u Šibeniku: oko 55 minuta, fiksna cijena po vozilu, kombiji za posade do 8 osoba i doček.",
"Marina Mandalina (D-Marin Mandalina) is on the Mandalina peninsula in Šibenik, a base for charter yachts and superyachts close to the Kornati islands and Krka.": "Marina Mandalina (D-Marin Mandalina) nalazi se na poluotoku Mandalina u Šibeniku, baza za charter jahte i superjahte blizu Kornata i Krke.",
"The marina is about 55 km north of the airport. The drive usually takes around 55 minutes, mostly on the motorway towards Šibenik and then down to the Mandalina peninsula on the south side of the city.": "Marina je oko 55 km sjeverno od aerodroma. Vožnja obično traje oko 55 minuta, većinom autocestom prema Šibeniku, a zatim do poluotoka Mandalina na južnoj strani grada.",
"Marina Mandalina is one of the main marinas in Šibenik, with berths for everything from charter yachts to superyachts. The old town and the UNESCO-listed Cathedral of St James are a short drive away, and the marina is a natural starting point for the Kornati National Park and the Krka river, which boats can sail up towards Skradin. If you arrive a day early, the old town is well worth an evening.": "Marina Mandalina jedna je od glavnih marina u Šibeniku, s vezovima za sve od charter jahti do superjahti. Stara jezgra i katedrala sv. Jakova pod zaštitom UNESCO-a kratka su vožnja, a marina je prirodna polazna točka za Nacionalni park Kornati i rijeku Krku, kojom se brodom može ploviti do Skradina. Ako stignete dan ranije, stari grad vrijedi jedne večeri.",
})
