# Blog posts, batch 3 (phase 2): taxi prices; Split taxi/bus/transfer
T = {
"Split Airport Taxi Prices (2026 Guide) | Airport Split Transfer": "Cijene taksija sa Zračne luke Split (2026.) | Airport Split Transfer",
"How much is a taxi from Split Airport to Split?": "Koliko košta taxi od Zračne luke Split do Splita?",
"A metered rank taxi usually costs €35–50 to Split city centre. A fixed-price private transfer costs around €50 for a car or €65–70 for a van.": "Taksi sa stajališta s taksimetrom do centra Splita obično košta 35–50 €. Privatni transfer po fiksnoj cijeni stoji oko 50 € za auto ili 65–70 € za kombi.",
"Do Split Airport taxis take cards?": "Primaju li taksiji na Zračnoj luci Split kartice?",
"Many do, but not all, ask before you get in. With our private transfers you can pay by card or cash to the driver.": "Mnogi primaju, ali ne svi, pa pitajte prije nego što uđete. Kod naših privatnih transfera vozaču možete platiti karticom ili gotovinom.",
"Is a private transfer more expensive than a taxi?": "Je li privatni transfer skuplji od taksija?",
"On most routes it costs about the same as a rank taxi, but the price is fixed before you land and includes meet & greet, tolls and child seats.": "Na većini ruta košta otprilike kao taksi sa stajališta, ali cijena je fiksna prije slijetanja i uključuje doček, cestarinu i dječje sjedalice.",
"\"How much is a taxi from Split Airport?\" is the first thing most visitors search, and the honest answer is: it depends on which kind of taxi. There are three, the metered taxis waiting at the rank, ride-hailing apps, and fixed-price private transfers, and they price the same journey in very different ways.": "\"Koliko košta taxi sa Zračne luke Split?\" prvo je što većina posjetitelja potraži, a iskren odgovor glasi: ovisi o kakvom taksiju govorimo. Postoje tri vrste, taksiji s taksimetrom na stajalištu, aplikacije za prijevoz i privatni transferi po fiksnoj cijeni, a istu vožnju naplaćuju vrlo različito.",
"Rank taxis: metered": "Taksiji sa stajališta: taksimetar",
"Taxis at the rank outside arrivals run on the meter. To Split city centre, expect roughly": "Taksiji na stajalištu ispred dolaznog terminala voze s taksimetrom. Do centra Splita računajte otprilike",
". Longer routes are harder to predict because the fare depends on the company, the route the driver takes, and traffic. Always confirm the price or ask for an estimate before you set off, and ask for a receipt.": ". Dulje rute teže je predvidjeti jer cijena ovisi o prijevozniku, ruti koju vozač odabere i prometu. Uvijek prije polaska potvrdite cijenu ili tražite procjenu te tražite račun.",
"Ride-hailing apps: surge pricing": "Aplikacije: cijene koje rastu s potražnjom",
"Apps like Bolt operate around Split and can be cheaper than the rank outside peak times. In July and August, surge pricing can push fares above the rank taxis, and availability late at night or very early in the morning is not guaranteed. Most app cars are sedans, so groups with luggage may need two.": "Aplikacije poput Bolta rade oko Splita i izvan špice mogu biti jeftinije od stajališta. U srpnju i kolovozu cijene s potražnjom mogu prijeći cijene taksija sa stajališta, a dostupnost kasno noću ili vrlo rano ujutro nije zajamčena. Većina vozila u aplikacijama su limuzine, pa grupama s prtljagom mogu trebati dva.",
"Private transfers: fixed per vehicle": "Privatni transferi: fiksno po vozilu",
"A private transfer is priced per vehicle before you book. The price doesn't change with traffic, delays or the time of day, and it already includes tolls, fuel, meet & greet in arrivals and child seats on request. These are typical one-way prices with us:": "Privatni transfer ima cijenu po vozilu prije rezervacije. Cijena se ne mijenja zbog prometa, kašnjenja ili doba dana, a već uključuje cestarinu, gorivo, doček u dolaznom terminalu i dječje sjedalice na zahtjev. Ovo su uobičajene cijene u jednom smjeru kod nas:",
"Route from Split Airport": "Ruta od Zračne luke Split",
"Drive time": "Trajanje",
"Car (1–4)": "Auto (1–4)",
"Van (up to 8)": "Kombi (do 8)",
"~7 km": "~7 km", "~20 km": "~20 km", "~27 km": "~27 km", "~45 km": "~45 km", "~65 km": "~65 km", "~89 km": "~89 km", "~230 km": "~230 km",
"Split centre / ferry port": "Centar Splita / trajektna luka",
"25–30 min": "25–30 min",
"3–3.5 h": "3–3,5 h",
"The exact price depends on your address and shows instantly in the": "Točna cijena ovisi o vašoj adresi i odmah se prikazuje u",
"booking form": "obrascu za rezervaciju",
". A return trip booked together gets 5% off.": ". Povratna vožnja rezervirana zajedno dobiva 5% popusta.",
"Which one is cheapest?": "Što je najjeftinije?",
"For one or two people going into Split outside peak season, an app ride can be the cheapest car option. For everyone else the gap closes quickly: a rank taxi to Split costs about the same as a transfer, and on longer routes a fixed price removes the risk of a meter running through summer traffic on the coast road. If you want the fixed-price option, see our": "Za jednu ili dvije osobe koje izvan sezone idu u Split vožnja preko aplikacije može biti najjeftinija opcija autom. Za sve ostale razlika se brzo smanjuje: taksi sa stajališta do Splita košta otprilike kao transfer, a na duljim rutama fiksna cijena uklanja rizik od taksimetra koji vrti kroz ljetnu gužvu na obalnoj cesti. Ako želite fiksnu cijenu, pogledajte naš",
"Split Airport taxi at a fixed price": "taxi sa Zračne luke Split po fiksnoj cijeni",
"The biggest saving is for groups. A van for up to eight people to Makarska costs around €185 in total: about €23 per person, only a little more than the bus, but from the arrivals hall to your door.": "Najveća je ušteda za grupe. Kombi za do osam osoba do Makarske ukupno košta oko 185 €: oko 23 € po osobi, tek malo više od autobusa, ali od dolaznog terminala do vaših vrata.",
"Things that can add to the price": "Što može povećati cijenu",
"Rank taxis:": "Taksiji sa stajališta:",
"luggage surcharges, night rates and detours in traffic.": "nadoplate za prtljagu, noćna tarifa i obilasci zbog prometa.",
"Apps:": "Aplikacije:",
"surge pricing and cancellations during busy periods.": "rast cijene s potražnjom i otkazivanja u gužvi.",
"Private transfers:": "Privatni transferi:",
"extra stops or route changes asked for on the day. With us these are always agreed before the ride, never added at the end.": "dodatna stajanja ili promjene rute zatražene na dan vožnje. Kod nas se to uvijek dogovara prije vožnje, nikad se ne dodaje na kraju.",
"Frequently Asked Questions": "Česta pitanja",
"Split Airport to Split: Taxi, Bus or Transfer | Airport Split Transfer": "Od Zračne luke do Splita: taxi, autobus ili transfer | Airport Split Transfer",
"How far is Split Airport from Split city centre?": "Koliko je Zračna luka Split udaljena od centra Splita?",
"About 20 km. The drive takes 25–30 minutes in normal traffic and longer on summer afternoons.": "Oko 20 km. Vožnja traje 25–30 minuta u normalnom prometu, a ljeti poslijepodne i dulje.",
"What is the cheapest way from Split Airport to Split?": "Koji je najjeftiniji način od Zračne luke Split do Splita?",
"The local city bus (line 37) is the cheapest, followed by the airport shuttle at roughly €8–10 per person. Both are slower than a taxi or transfer and don't take you to your door.": "Najjeftiniji je gradski autobus (linija 37), a zatim aerodromski shuttle za otprilike 8–10 € po osobi. Oba su sporija od taksija ili transfera i ne voze vas do vrata.",
"How much is a private transfer from Split Airport to Split?": "Koliko košta privatni transfer od Zračne luke Split do Splita?",
"Around €50 for a car with up to 4 passengers and around €65–70 for a van with up to 8, per vehicle. The booking form shows the exact fixed price for your address.": "Oko 50 € za auto s do 4 putnika i oko 65–70 € za kombi s do 8 putnika, po vozilu. Obrazac za rezervaciju pokazuje točnu fiksnu cijenu za vašu adresu.",
"Split Airport is not actually in Split. It sits in Kaštela, about 20 km west of the old town, so every arrival starts with the same question: how do I get into the city? There are three realistic answers, the airport shuttle, a taxi from the rank, or a private transfer booked in advance, and each one is the right choice for somebody.": "Zračna luka Split zapravo nije u Splitu. Nalazi se u Kaštelima, oko 20 km zapadno od stare jezgre, pa svaki dolazak počinje istim pitanjem: kako do grada? Postoje tri realna odgovora, aerodromski shuttle, taksi sa stajališta ili unaprijed rezerviran privatni transfer, i svaki je pravi izbor za nekoga.",
"Option 1: the airport shuttle bus": "Opcija 1: aerodromski shuttle autobus",
"The official airport shuttle leaves from right outside arrivals and runs to Split main bus station, which sits next to the ferry port and a five-minute walk from Diocletian's Palace. Departures are timed around arriving flights, the trip takes 30–40 minutes, and a ticket costs roughly €8–10 per person. Fares and timetables change from season to season, so check before you fly.": "Službeni aerodromski shuttle polazi odmah ispred dolaznog terminala i vozi do glavnog autobusnog kolodvora u Splitu, koji je uz trajektnu luku, pet minuta hoda od Dioklecijanove palače. Polasci su usklađeni s dolascima letova, vožnja traje 30–40 minuta, a karta košta otprilike 8–10 € po osobi. Cijene i vozni red mijenjaju se od sezone do sezone, pa provjerite prije leta.",
"Best for:": "Najbolje za:",
"solo travellers and couples with light luggage who are staying in or near the old town, or catching a ferry.": "osobe koje putuju same i parove s malo prtljage koji odsjedaju u staroj jezgri ili blizu nje ili idu na trajekt.",
"There is also the local city bus (line 37), which stops on the main road outside the airport. It is very cheap but slow, close to an hour to Split, and it does not end in the centre, so it rarely makes sense with suitcases.": "Postoji i gradski autobus (linija 37), koji staje na glavnoj cesti ispred aerodroma. Vrlo je jeftin, ali spor, gotovo sat vremena do Splita, i ne završava u centru, pa s koferima rijetko ima smisla.",
"Option 2: a taxi from the rank": "Opcija 2: taksi sa stajališta",
"The taxi rank is directly outside the terminal. Taxis are metered, and a ride to the centre usually lands somewhere between €35 and €50 depending on the company, traffic and time of day. Ride-hailing apps also work at the airport, but prices rise sharply with summer demand and cars can be scarce late at night.": "Taksi stajalište je odmah ispred terminala. Taksiji voze s taksimetrom, a vožnja do centra obično košta između 35 i 50 €, ovisno o prijevozniku, prometu i dobu dana. Na aerodromu rade i aplikacije za prijevoz, ali cijene ljeti naglo rastu s potražnjom, a kasno noću vozila zna nedostajati.",
"travellers who didn't book anything and don't want to wait for the next shuttle.": "putnike koji ništa nisu rezervirali i ne žele čekati sljedeći shuttle.",
"The catch is uncertainty. You don't know the final price until you arrive, and on a busy July afternoon the queue for a car can be longer than the drive itself. Groups of five or more may also find that the next car in line is a sedan.": "Problem je neizvjesnost. Konačnu cijenu ne znate dok ne stignete, a u gužvi srpanjskog poslijepodneva red za auto može trajati dulje od same vožnje. Grupe od pet i više osoba mogu otkriti i da je sljedeće vozilo u redu limuzina.",
"Option 3: a private transfer": "Opcija 3: privatni transfer",
"A pre-booked transfer costs about the same as a rank taxi, but the price is fixed before you land. With us, Split Airport to Split city centre is around": "Unaprijed rezerviran transfer košta otprilike kao taksi sa stajališta, ali cijena je fiksna prije slijetanja. Kod nas od Zračne luke Split do centra Splita košta oko",
"€50 in a car for up to 4 people": "50 € autom za do 4 osobe",
"and around": "i oko",
"€65–70 in a van for up to 8": "65–70 € kombijem za do 8 osoba",
"per vehicle, not per person, with tolls, fuel and meet & greet included. Read more on our": "po vozilu, a ne po osobi, s uključenom cestarinom, gorivom i dočekom. Više na stranici",
"page.": ".",
"Your driver tracks your flight, waits in the arrivals hall with a name sign and takes you to your exact address. That matters in Split more than in most cities: much of the old town is pedestrian-only, and a driver who knows the nearest drop-off point saves you dragging suitcases across marble streets.": "Vozač prati vaš let, čeka vas u dolaznom terminalu s vašim imenom na tabli i vozi vas na točnu adresu. U Splitu je to važnije nego u većini gradova: velik dio stare jezgre je pješačka zona, a vozač koji zna najbliže mjesto iskrcaja štedi vam vučenje kofera po kamenim ulicama.",
"families, groups, late arrivals, and anyone staying outside the bus station area.": "obitelji, grupe, kasne dolaske i sve koji odsjedaju podalje od autobusnog kolodvora.",
"Quick comparison": "Brza usporedba",
"Option": "Opcija",
"Price": "Cijena",
"Notes": "Napomena",
"Airport shuttle": "Aerodromski shuttle",
"~€8–10 per person": "~8–10 € po osobi",
"30–40 min": "30–40 min",
"Bus station only": "Samo do autobusnog kolodvora",
"Taxi from the rank": "Taksi sa stajališta",
"~€35–50 per car": "~35–50 € po vozilu",
"Metered, queue in summer": "Taksimetar, ljeti red",
"Private transfer": "Privatni transfer",
"~€50 car / ~€65 van": "~50 € auto / ~65 € kombi",
"Fixed price, door to door": "Fiksna cijena, od vrata do vrata",
"For two people with backpacks heading to the ferry, the shuttle is hard to beat. For a family of four with luggage, the shuttle already costs €32–40 and still leaves you at the bus station, at that point a private transfer to the door costs only a little more.": "Za dvoje s ruksacima koji idu na trajekt shuttle je teško nadmašiti. Za četveročlanu obitelj s prtljagom shuttle već stoji 32–40 € i opet vas ostavlja na autobusnom kolodvoru, pa privatni transfer do vrata košta tek malo više.",
}
