# Blog posts, batch 4 (phase 2): early morning; how to book; Dubrovnik worth it
T = {
"Early Morning Transfer to Split Airport | Airport Split Transfer": "Rani jutarnji transfer do Zračne luke Split | Airport Split Transfer",
"Is there a bus to Split Airport early in the morning?": "Vozi li rano ujutro autobus do Zračne luke Split?",
"Service at very early hours is limited. Check the first airport shuttle departure against your flight time before you rely on it.": "U vrlo rane sate prijevoz je ograničen. Prije nego što se na njega oslonite, usporedite prvi polazak aerodromskog shuttlea s vremenom svog leta.",
"How early should I get to Split Airport?": "Koliko ranije trebam doći na Zračnu luku Split?",
"About 2 hours before departure in summer, when morning security queues are longest.": "Ljeti oko 2 sata prije polijetanja, kad su jutarnji redovi na sigurnosnoj kontroli najdulji.",
"Do you charge extra for early morning transfers?": "Naplaćujete li dodatno rane jutarnje transfere?",
"No. The price is the same at any time of day, with no night rate.": "Ne. Cijena je ista u bilo koje doba dana, bez noćne tarife.",
"Many flights out of Split leave between 6 and 8 in the morning, especially budget airlines and charter flights on changeover days. That means a check-in around 4–5am, and the hardest part of the trip is often getting to the airport before the day has started.": "Mnogi letovi iz Splita polijeću između 6 i 8 ujutro, osobito niskotarifni i čarter letovi na dane smjene gostiju. To znači prijavu na let oko 4–5 ujutro, a najteži dio puta često je stići na aerodrom prije nego što je dan uopće počeo.",
"Why early mornings are tricky": "Zašto su rana jutra nezgodna",
"Buses aren't running yet,": "Autobusi još ne voze",
"or only a few are. Check the first airport shuttle departure against your flight time before you rely on it.": "ili vozi tek pokoji. Prije nego što se na njih oslonite, usporedite prvi polazak aerodromskog shuttlea s vremenom svog leta.",
"Ride-hailing apps are unreliable": "Aplikacije za prijevoz nisu pouzdane",
"at 4am. There may be no cars nearby, or a driver may accept and then cancel.": "u 4 ujutro. U blizini možda nema vozila ili vozač prihvati vožnju pa je otkaže.",
"Street taxis are rare": "Taksija na ulici je malo",
"outside the centre of Split, and almost non-existent in smaller towns along the coast.": "izvan centra Splita, a u manjim mjestima uz obalu gotovo ih nema.",
"How early should you leave?": "Koliko rano krenuti?",
"Aim to be at the airport": "Ciljajte biti na aerodromu",
"2 hours before departure": "2 sata prije polijetanja",
"in summer. Split Airport's terminal is modern but busy in peak season, and security queues build quickly in the morning wave of departures. Then add the drive time:": "ljeti. Terminal Zračne luke Split je moderan, ali u sezoni pun, a redovi na sigurnosnoj kontroli brzo rastu u jutarnjem valu polazaka. Zatim dodajte vrijeme vožnje:",
"Split city centre: 25–30 minutes": "Centar Splita: 25–30 minuta",
"Trogir: 10–15 minutes": "Trogir: 10–15 minuta",
"Podstrana: around 30 minutes": "Podstrana: oko 30 minuta",
"Omiš: around 45 minutes": "Omiš: oko 45 minuta",
"Makarska: around 1 hour 20 minutes": "Makarska: oko 1 sat i 20 minuta",
"Roads are quiet at that hour, so drive times are usually reliable. The risk is the time before the car arrives, not the drive.": "Ceste su u to doba mirne, pa je trajanje vožnje obično pouzdano. Rizik je vrijeme prije nego što auto stigne, a ne sama vožnja.",
"Book the day before, not on the morning": "Rezervirajte dan ranije, a ne isto jutro",
"A pre-booked transfer is the calm option. The driver is at your door at the agreed time, and the price is the same at 4am as at noon. There's no night rate. When you book, give us your flight time and we'll suggest a pickup time. If anything changes, you can move or cancel the booking free of charge.": "Unaprijed rezerviran transfer je mirna opcija. Vozač je pred vratima u dogovoreno vrijeme, a cijena je ista u 4 ujutro kao i u podne. Noćne tarife nema. Pri rezervaciji nam napišite vrijeme leta i predložit ćemo vrijeme preuzimanja. Ako se nešto promijeni, rezervaciju možete pomaknuti ili otkazati besplatno.",
"Tip: if you book your arrival and departure together as a return trip, you get 5% off both ways and never have to think about the return at the end of your holiday.": "Savjet: ako dolazak i odlazak rezervirate zajedno kao povratnu vožnju, dobivate 5% popusta na oba smjera i na kraju odmora ne morate razmišljati o povratku.",
"Checklist for the night before": "Popis za večer prije",
"Double-check the pickup time and address in your booking confirmation.": "Još jednom provjerite vrijeme i adresu preuzimanja u potvrdi rezervacije.",
"Tell us if your accommodation has a hard-to-find entrance or gate.": "Javite nam ako vaš smještaj ima teško uočljiv ulaz ili kapiju.",
"Check your flight status in case of a time change.": "Provjerite status leta za slučaj da se vrijeme promijenilo.",
"Have your passport and boarding pass ready. You'll be sleepy.": "Pripremite putovnicu i kartu za ukrcaj. Bit ćete pospani.",
"How to Book a Reliable Split Airport Transfer | Airport Split Transfer": "Kako rezervirati pouzdan transfer sa Zračne luke Split | Airport Split Transfer",
"What happens if my flight to Split is delayed?": "Što ako moj let za Split kasni?",
"We track your flight number and your driver adjusts the pickup time automatically. There is no extra charge for reasonable delays.": "Pratimo vaš let, a vozač sam prilagođava vrijeme preuzimanja. Za uobičajena kašnjenja nema dodatne naplate.",
"Can I cancel my Split Airport transfer?": "Mogu li otkazati transfer sa Zračne luke Split?",
"Yes, cancellation is free at any time before pickup, by email, phone or WhatsApp.": "Da, otkazivanje je besplatno u bilo kojem trenutku prije preuzimanja, e-mailom, telefonom ili WhatsAppom.",
"How do I pay for the transfer?": "Kako plaćam transfer?",
"You pay the driver on the day, by card or cash, unless another payment method was agreed in advance.": "Plaćate vozaču na dan vožnje, karticom ili gotovinom, osim ako unaprijed nije dogovoren drugi način plaćanja.",
"Most airport transfers go fine. The ones that don't usually fail in the same few ways: the driver isn't there, the price changes, or the car is too small for the group. Here's what to check before you book, so yours is one of the ones that go fine.": "Većina aerodromskih transfera prođe bez problema. Oni koji ne prođu obično zapnu na isti način: vozača nema, cijena se promijeni ili je auto premalen za grupu. Evo što provjeriti prije rezervacije da vaš bude među onima koji prođu dobro.",
"1. A fixed price, per vehicle": "1. Fiksna cijena po vozilu",
"You should know the full price before you pay anything. It should be per vehicle, not per person, and include tolls, fuel and waiting in arrivals. Watch out for low headline prices that add \"airport fees\" or luggage charges later.": "Punu cijenu trebate znati prije nego što bilo što platite. Trebala bi biti po vozilu, a ne po osobi, i uključivati cestarinu, gorivo i čekanje u dolaznom terminalu. Pazite na niske istaknute cijene na koje se kasnije dodaju \"aerodromske naknade\" ili nadoplate za prtljagu.",
"2. Flight tracking": "2. Praćenje leta",
"Your booking should ask for a flight number. A company that tracks flights will adjust the pickup if you land late, without charging you for the delay. If a booking form doesn't ask for your flight number, ask what happens when the flight is late.": "Rezervacija bi trebala tražiti broj leta. Prijevoznik koji prati letove pomaknut će preuzimanje ako kasnite, bez naplate kašnjenja. Ako obrazac ne traži broj leta, pitajte što se događa kad let kasni.",
"3. Meet & greet inside arrivals": "3. Doček u dolaznom terminalu",
"The driver should wait in the arrivals hall with a name sign, not in the car park. At Split Airport that saves you finding a car in a busy summer car park with your luggage.": "Vozač bi vas trebao čekati u dolaznom terminalu s vašim imenom na tabli, a ne na parkiralištu. Na Zračnoj luci Split to vam štedi traženje auta po punom ljetnom parkiralištu s prtljagom.",
"4. The right vehicle for your group": "4. Pravo vozilo za vašu grupu",
"Four people with four large suitcases don't fit comfortably in most taxis. Look for a company that asks how many passengers you are and offers a van for bigger groups. We use a Škoda Superb for up to 4 and vans for up to 8.": "Četiri osobe s četiri velika kofera ne stanu udobno u većinu taksija. Tražite prijevoznika koji pita koliko vas je i nudi kombi za veće grupe. Mi vozimo Škodu Superb za do 4 osobe i kombije za do 8.",
"5. Free child seats": "5. Besplatne dječje sjedalice",
"Children in Croatia must travel in a suitable child seat. A good transfer company provides them free of charge when you ask during booking.": "Djeca u Hrvatskoj moraju putovati u odgovarajućoj dječjoj sjedalici. Dobar prijevoznik daje ih besplatno ako ih zatražite pri rezervaciji.",
"6. Free cancellation": "6. Besplatno otkazivanje",
"Plans change. Check that you can cancel or change the booking without a fee: ideally right up to pickup, not just 48 hours before.": "Planovi se mijenjaju. Provjerite možete li otkazati ili promijeniti rezervaciju bez naknade, idealno sve do preuzimanja, a ne samo do 48 sati prije.",
"7. A way to reach a real person": "7. Način da dobijete stvarnu osobu",
"Before you fly, make sure you have a phone number and WhatsApp for the company, not just an email. If your flight is diverted or your phone dies, you need to reach someone quickly.": "Prije leta provjerite imate li broj telefona i WhatsApp prijevoznika, a ne samo e-mail. Ako vam let preusmjere ili se mobitel isprazni, morate brzo nekoga dobiti.",
"8. Real reviews": "8. Stvarne recenzije",
"Look for reviews on Google, not just testimonials on the company's own website, and check how the company answers when something went wrong.": "Tražite recenzije na Googleu, a ne samo pohvale na stranici samog prijevoznika, i pogledajte kako prijevoznik odgovara kad nešto nije bilo u redu.",
"How booking works with us": "Kako rezervacija funkcionira kod nas",
"Enter your pickup and drop-off addresses in the": "Upišite adresu polazišta i odredišta u",
"and see the fixed price for each vehicle instantly.": "i odmah vidite fiksnu cijenu za svako vozilo.",
"Add your flight number, number of passengers and any child seats.": "Dodajte broj leta, broj putnika i dječje sjedalice ako trebaju.",
"Get a confirmation by email. Pay the driver by card or cash on the day.": "Potvrdu dobivate e-mailom. Vozaču plaćate karticom ili gotovinom na dan vožnje.",
"Your driver tracks your flight and waits in arrivals with your name.": "Vozač prati vaš let i čeka vas u dolaznom terminalu s vašim imenom.",
"Questions before you book? Message us on": "Imate pitanja prije rezervacije? Pišite nam na",
"we usually reply within minutes.": ", obično odgovaramo u nekoliko minuta.",
"Split Airport to Dubrovnik: Is It Worth It? | Airport Split Transfer": "Od Zračne luke Split do Dubrovnika: isplati li se? | Airport Split Transfer",
"About 3 to 3.5 hours, depending on traffic and the route.": "Oko 3 do 3,5 sata, ovisno o prometu i ruti.",
"Do I need a passport to drive from Split to Dubrovnik?": "Trebam li putovnicu za vožnju od Splita do Dubrovnika?",
"The route over the Pelješac Bridge stays in Croatia, but keep passports with you in case the driver uses the road through Neum in Bosnia and Herzegovina.": "Ruta preko Pelješkog mosta ostaje u Hrvatskoj, ali dokumente imajte uza se za slučaj da vozač krene cestom kroz Neum u Bosni i Hercegovini.",
"How much is a transfer from Split Airport to Dubrovnik?": "Koliko košta transfer od Zračne luke Split do Dubrovnika?",
"Around €380 for a car with up to 4 passengers and around €455 for a van with up to 8, per vehicle.": "Oko 380 € za auto s do 4 putnika i oko 455 € za kombi s do 8 putnika, po vozilu.",
"Many travellers heading to Dubrovnik end up flying into Split instead: because flights are cheaper, there are more routes, or they want to see both cities. The question is whether the 230 km in between is a problem or part of the trip. (For the route itself and places to stop, see our": "Mnogi putnici koji idu u Dubrovnik na kraju slete u Split: jer su letovi jeftiniji, linija je više ili žele vidjeti oba grada. Pitanje je jesu li 230 km između problem ili dio putovanja. (Za samu rutu i mjesta za stajanje pogledajte naš",
"Split to Dubrovnik route guide": "vodič za rutu Split–Dubrovnik",
"When it makes sense": "Kada se isplati",
"The flight price difference is big.": "Razlika u cijeni leta je velika.",
"For a family, saving €100 or more per ticket on flights into Split easily covers the drive.": "Za obitelj ušteda od 100 € ili više po karti na letovima za Split lako pokriva vožnju.",
"You want to see Split too.": "Želite vidjeti i Split.",
"Fly in, spend a few days in Split, then transfer to Dubrovnik and fly home from there.": "Sletite, provedite nekoliko dana u Splitu, zatim se prevezite u Dubrovnik i odande letite kući.",
"There's no direct flight": "Nema izravnog leta",
"from your city to Dubrovnik on your dates, especially outside summer.": "iz vašeg grada do Dubrovnika na vaše datume, osobito izvan ljeta.",
"If you're flying in only to go straight to Dubrovnik for a short stay, and a direct flight to Dubrovnik costs about the same, flying direct is simpler.": "Ako slijećete samo da biste odmah otišli u Dubrovnik na kratki boravak, a izravni let do Dubrovnika košta otprilike isto, jednostavnije je letjeti izravno.",
"How long does it take?": "Koliko traje?",
"By car, 3 to 3.5 hours. The motorway covers the first part; the rest follows the coast. Since the Pelješac Bridge opened in 2022, the route can avoid the short stretch through Bosnia and Herzegovina at Neum. Keep passports handy anyway, drivers sometimes choose the Neum road depending on traffic.": "Autom 3 do 3,5 sata. Prvi dio je autocestom, a ostatak uz obalu. Otkako je 2022. otvoren Pelješki most, ruta može zaobići kratki dio kroz Bosnu i Hercegovinu kod Neuma. Dokumente ipak imajte pri ruci, vozači ponekad ovisno o prometu odaberu cestu kroz Neum.",
"Your options compared": "Usporedba opcija",
"Bus": "Autobus",
"~€20–30 per person": "~20–30 € po osobi",
"4.5–5 h": "4,5–5 h",
"Change in Split first": "Presjedanje u Splitu",
"Catamaran (summer)": "Katamaran (ljeti)",
"~€40–60 per person": "~40–60 € po osobi",
"4–5 h": "4–5 h",
"From Split port, stops at islands": "Iz splitske luke, staje na otocima",
"~€380 car / ~€455 van": "~380 € auto / ~455 € kombi",
"Door to door, stops on request": "Od vrata do vrata, stajanja na zahtjev",
"Bus and ferry fares change by season; check with the operators before you travel.": "Cijene autobusa i brodova mijenjaju se po sezoni; provjerite kod prijevoznika prije putovanja.",
"What a transfer costs": "Koliko košta transfer",
"A private transfer costs around": "Privatni transfer košta oko",
"€380 in a car for up to 4": "380 € autom za do 4 osobe",
"€455 in a van for up to 8": "455 € kombijem za do 8 osoba",
", per vehicle. For a group of eight that's about €57 per person: not far from the catamaran, but directly from the arrivals hall to your hotel door in Dubrovnik, with no connection to make.": ", po vozilu. Za grupu od osmero to je oko 57 € po osobi: nedaleko od katamarana, ali izravno od dolaznog terminala do vrata hotela u Dubrovniku, bez presjedanja.",
"It also turns the drive into part of the holiday. With a private driver you can stop for photos, coffee, or lunch in Ston for oysters. Tell us what you'd like when booking and we'll plan the time.": "Uz to vožnja postaje dio odmora. S privatnim vozačem možete stati za fotografije, kavu ili ručak u Stonu uz kamenice. Pri rezervaciji nam recite što želite i isplanirat ćemo vrijeme.",
"The verdict": "Zaključak",
"For couples on a budget, the bus is fine. For families and groups with luggage, a private transfer is usually the most comfortable way: and when the flight savings are big, it often pays for itself.": "Za parove s ograničenim budžetom autobus je sasvim u redu. Za obitelji i grupe s prtljagom privatni transfer obično je najudobniji način, a kad je ušteda na letovima velika, često se sam isplati.",
}
