# Blog posts, batch 5 (phase 2): Makarska options; Omiš; Podstrana
T = {
"Split Airport to Makarska: Transport Options | Airport Split Transfer": "Od Zračne luke Split do Makarske: opcije prijevoza | Airport Split Transfer",
"Is there a direct bus from Split Airport to Makarska?": "Postoji li izravni autobus od Zračne luke Split do Makarske?",
"Not usually. Most travellers take the airport shuttle to Split bus station and change to a coastal bus to Makarska.": "Uglavnom ne. Većina putnika aerodromskim shuttleom ode do autobusnog kolodvora u Splitu i ondje presjedne na autobus za Makarsku.",
"How long does it take to get from Split Airport to Makarska?": "Koliko traje put od Zračne luke Split do Makarske?",
"About 1 hour 20 minutes by car. By bus via Split, allow 3 hours or more including the change.": "Autom oko 1 sat i 20 minuta. Autobusom preko Splita računajte 3 sata ili više, s presjedanjem.",
"How much is a transfer from Split Airport to Makarska?": "Koliko košta transfer od Zračne luke Split do Makarske?",
"Around €155 for a car with up to 4 passengers and around €185 for a van with up to 8, per vehicle, fixed in advance.": "Oko 155 € za auto s do 4 putnika i oko 185 € za kombi s do 8 putnika, po vozilu, fiksno unaprijed.",
"Makarska is about 89 km south of Split Airport, roughly 1 hour 20 minutes by car. There's no direct public transport from the terminal, so the choice is really about how many changes you're willing to make with your luggage. Here are the four options, from cheapest to most direct. (For the drive itself and the towns along the Riviera, see our": "Makarska je oko 89 km južno od Zračne luke Split, otprilike 1 sat i 20 minuta autom. Izravnog javnog prijevoza od terminala nema, pa je pitanje zapravo koliko presjedanja s prtljagom ste spremni podnijeti. Evo četiri opcije, od najjeftinije do najizravnije. (Za samu vožnju i mjesta na rivijeri pogledajte naš",
"Split to Makarska route guide": "vodič za rutu Split–Makarska",
"1. Bus via Split": "1. Autobus preko Splita",
"Take the airport shuttle to Split main bus station (30–40 minutes), then a coastal bus to Makarska. Coastal buses run often in summer and take around 1.5–2 hours. Together with waiting time, plan on 3 hours or more door to door, and around €20 per person for both tickets.": "Aerodromskim shuttleom do glavnog autobusnog kolodvora u Splitu (30–40 minuta), zatim autobusom uz obalu do Makarske. Ljeti autobusi voze često i putuju oko 1,5–2 sata. Sa čekanjem računajte 3 sata ili više od vrata do vrata i oko 20 € po osobi za obje karte.",
"It's the cheapest option for one person travelling light. It's also the slowest, and in July and August buses toward the Riviera can be full.": "To je najjeftinija opcija za jednu osobu s malo prtljage. Ujedno je i najsporija, a u srpnju i kolovozu autobusi prema rivijeri znaju biti puni.",
"2. Rental car": "2. Unajmljeni auto",
"Car hire desks are in the terminal, and the coast road is easy to drive. The problem is Makarska itself: parking in the centre is limited and expensive in summer, and many apartments have no space. If you plan to stay by the beach most of the week, you may pay for a car that sits parked.": "Šalteri za najam auta su u terminalu, a obalnom cestom lako se vozi. Problem je sama Makarska: parking u centru je ljeti ograničen i skup, a mnogi apartmani nemaju mjesta. Ako većinu tjedna planirate biti na plaži, možda plaćate auto koji samo stoji.",
"3. Taxi from the rank": "3. Taksi sa stajališta",
"A metered taxi works, but on a 90 km route through summer traffic the final price is hard to predict. Always agree an estimate before you set off.": "Taksi s taksimetrom je opcija, ali na ruti od 90 km kroz ljetnu gužvu konačnu cijenu teško je predvidjeti. Uvijek prije polaska dogovorite procjenu.",
"4. Private transfer": "4. Privatni transfer",
"A fixed-price transfer from the arrivals hall to your door costs around": "Transfer po fiksnoj cijeni od dolaznog terminala do vaših vrata košta oko",
"€155 in a car for up to 4": "155 € autom za do 4 osobe",
"€185 in a van for up to 8": "185 € kombijem za do 8 osoba",
". For a family of four that's €39 per person; for a group of eight in a van, about €23 each: close to the bus fare, without the change in Split.": ". Za četveročlanu obitelj to je 39 € po osobi; za grupu od osmero u kombiju oko 23 € po osobi: blizu cijene autobusa, bez presjedanja u Splitu.",
"Bus via Split": "Autobus preko Splita",
"~€20 per person": "~20 € po osobi",
"3 h+": "3 h+",
"Two buses, change in Split": "Dva autobusa, presjedanje u Splitu",
"Rental car": "Unajmljeni auto",
"Varies + parking": "Ovisi + parking",
"Parking in Makarska is hard": "Parking u Makarskoj je težak",
"Rank taxi": "Taksi sa stajališta",
"Metered": "Taksimetar",
"Price depends on traffic": "Cijena ovisi o prometu",
"~€155 car / ~€185 van": "~155 € auto / ~185 € kombi",
"Fixed, door to door": "Fiksno, od vrata do vrata",
"Summer Saturdays": "Ljetne subote",
"Saturday is changeover day for holiday rentals along the whole Riviera, and the coast road through Omiš slows down in both directions. If you book with your flight number, your driver plans for that. On the way back, we'll suggest a pickup time with enough buffer for Saturday traffic.": "Subota je dan smjene gostiju u apartmanima duž cijele rivijere, pa obalna cesta kroz Omiš usporava u oba smjera. Ako rezervirate s brojem leta, vozač to uzima u obzir. Za povratak ćemo predložiti vrijeme preuzimanja s dovoljno rezerve za subotnji promet.",
"Split Airport to Omiš: Transfer Guide | Airport Split Transfer": "Od Zračne luke Split do Omiša: vodič za transfer | Airport Split Transfer",
"How far is Omiš from Split Airport?": "Koliko je Omiš udaljen od Zračne luke Split?",
"About 45 km, which is around 45 minutes by car in normal traffic.": "Oko 45 km, što je oko 45 minuta autom u normalnom prometu.",
"How much is a transfer from Split Airport to Omiš?": "Koliko košta transfer od Zračne luke Split do Omiša?",
"Around €90 for a car with up to 4 passengers and around €130 for a van with up to 8, per vehicle.": "Oko 90 € za auto s do 4 putnika i oko 130 € za kombi s do 8 putnika, po vozilu.",
"Can you drive me to an apartment above Omiš or in the Cetina valley?": "Možete li me odvesti do apartmana iznad Omiša ili u dolini Cetine?",
"Yes. Give us the exact address when booking and the driver will confirm the access and drop-off point in advance.": "Da. Pri rezervaciji nam pošaljite točnu adresu i vozač će unaprijed potvrditi pristup i mjesto iskrcaja.",
"Omiš sits where the Cetina river cuts through the mountains into the sea, about 45 km from Split Airport. The drive takes around 45 minutes, and it's one of the most scenic arrivals on the coast, the last few kilometres run along the sea with the cliffs of the canyon ahead of you.": "Omiš je na mjestu gdje se rijeka Cetina probija kroz planine u more, oko 45 km od Zračne luke Split. Vožnja traje oko 45 minuta i jedan je od najljepših dolazaka na obali: zadnjih nekoliko kilometara vozite uz more, a pred vama su litice kanjona.",
"From the airport, the road bypasses Split and joins the coast road (the D8) past Stobreč and Podstrana. After that it's a straight run along the sea into Omiš. In summer, traffic through Podstrana and the Omiš bridge is the main thing that slows you down, especially on Saturday afternoons.": "Od aerodroma cesta zaobilazi Split i spaja se s obalnom cestom (D8) pokraj Stobreča i Podstrane. Nakon toga vozite ravno uz more do Omiša. Ljeti vas najviše usporava promet kroz Podstranu i na omiškom mostu, osobito subotom poslijepodne.",
"By bus": "Autobusom",
"There's no direct bus from the airport. Take the airport shuttle into Split main bus station and change to a coastal bus heading south, most of them stop in Omiš. Allow around two hours door to door, and more in peak season when buses fill up.": "Izravnog autobusa od aerodroma nema. Aerodromskim shuttleom odete do glavnog autobusnog kolodvora u Splitu i presjednete na autobus prema jugu, a većina staje u Omišu. Računajte oko dva sata od vrata do vrata, a u sezoni, kad se autobusi napune, i više.",
"By private transfer": "Privatnim transferom",
"€90 in a car for up to 4": "90 € autom za do 4 osobe",
"€130 in a van for up to 8": "130 € kombijem za do 8 osoba",
", fixed per vehicle. Your driver waits in arrivals and takes you straight to your accommodation.": ", fiksno po vozilu. Vozač vas čeka u dolaznom terminalu i vozi ravno do smještaja.",
"That matters in Omiš more than in most places. Many apartments are not in the town itself but up the hill, in villages like Duće, Ruskamen or Lokva Rogoznica along the coast, or up the Cetina valley. These addresses can be hard to find, and some aren't on any bus route. Put your exact address in the booking, and the driver will check the access before the day.": "U Omišu je to važnije nego u većini mjesta. Mnogi apartmani nisu u samom gradu, nego na brdu, u mjestima uz obalu poput Duća, Ruskamena ili Lokve Rogoznice, ili gore u dolini Cetine. Te adrese teško je naći, a do nekih ne vozi nijedan autobus. Upišite točnu adresu u rezervaciju i vozač će prije dana vožnje provjeriti pristup.",
"Things to do once you're there": "Što raditi kad stignete",
"Rafting and canyoning": "Rafting i kanjoning",
"on the Cetina: the most popular activities, running from spring to early autumn.": "na Cetini: najpopularnije aktivnosti, od proljeća do rane jeseni.",
"Zipline": "Zip-line",
"over the Cetina canyon.": "iznad kanjona Cetine.",
"The fortresses": "Tvrđave",
"Mirabella and Fortica above the town, with views over the river mouth.": "Mirabela i Fortica iznad grada, s pogledom na ušće rijeke.",
"The beaches": "Plaže",
"the long sandy beach right in town is rare on this coast and great for children.": ": duga pješčana plaža u samom gradu rijetkost je na ovoj obali i odlična je za djecu.",
"Many activity companies meet in town, so it's easy to go without a car once you've arrived.": "Mnoge agencije za aktivnosti skupljaju goste u gradu, pa nakon dolaska lako možete bez auta.",
"Split Airport to Podstrana Taxi Price (2026) | Airport Split Transfer": "Cijena taksija od Zračne luke Split do Podstrane (2026.) | Airport Split Transfer",
"How much is a taxi from Split Airport to Podstrana?": "Koliko košta taxi od Zračne luke Split do Podstrane?",
"A private transfer costs around €55 for a car with up to 4 passengers and around €75 for a van with up to 8. Rank taxis are metered, so the price depends on traffic.": "Privatni transfer košta oko 55 € za auto s do 4 putnika i oko 75 € za kombi s do 8 putnika. Taksiji sa stajališta voze s taksimetrom, pa cijena ovisi o prometu.",
"About 30 minutes. The road bypasses Split city centre.": "Oko 30 minuta. Cesta zaobilazi centar Splita.",
"Do you drive to Le Méridien Lav?": "Vozite li do hotela Le Méridien Lav?",
"Yes, we drop guests at the hotel reception. Just enter the hotel name as your drop-off address.": "Da, goste ostavljamo na recepciji hotela. Samo upišite ime hotela kao odredište.",
"Podstrana is the long seaside stretch just south of Split, between Stobreč and Omiš. From the airport it's about 27 km and around 30 minutes by car, because the road bypasses the city centre instead of going through it.": "Podstrana je dugi potez uz more odmah južno od Splita, između Stobreča i Omiša. Od aerodroma je oko 27 km i oko 30 minuta autom, jer cesta zaobilazi centar grada umjesto da prolazi kroz njega.",
"How much is a taxi to Podstrana?": "Koliko košta taxi do Podstrane?",
"A metered taxi from the airport rank is priced by distance and traffic, so the final price is only known when you arrive. A private transfer with us is fixed before you land: around": "Taksi s taksimetrom sa stajališta na aerodromu naplaćuje se prema udaljenosti i prometu, pa konačnu cijenu znate tek kad stignete. Privatni transfer kod nas je fiksan prije slijetanja: oko",
"€55 in a car for up to 4": "55 € autom za do 4 osobe",
"€75 in a van for up to 8": "75 € kombijem za do 8 osoba",
", per vehicle. That includes tolls, fuel, meet & greet in arrivals and child seats on request. Book a return trip together and you get 5% off both ways. See how our": ", po vozilu. To uključuje cestarinu, gorivo, doček u dolaznom terminalu i dječje sjedalice na zahtjev. Rezervirate li povratnu vožnju zajedno, dobivate 5% popusta na oba smjera. Pogledajte kako radi naša usluga",
"service works.": ".",
"The exact price depends on where in Podstrana you're staying, the area is almost ten kilometres long, and shows instantly in the": "Točna cijena ovisi o tome gdje u Podstrani odsjedate, jer je mjesto dugo gotovo deset kilometara, a odmah se prikazuje u",
"Is there a bus?": "Ima li autobusa?",
"Local buses from Split run along the coast through Podstrana, but there's no direct connection from the airport. You would take the shuttle into Split first, then a local bus back out: usually well over an hour with a change, and not practical with suitcases.": "Gradski autobusi iz Splita voze uz obalu kroz Podstranu, ali izravne veze s aerodroma nema. Prvo biste shuttleom otišli u Split, a zatim gradskim autobusom natrag: obično i više od sat vremena s presjedanjem, što s koferima nije praktično.",
"Hotels in Podstrana": "Hoteli u Podstrani",
"Podstrana is home to some of the largest resort hotels near Split, including": "U Podstrani su neki od najvećih resort hotela blizu Splita, među njima",
"Le Méridien Lav": "Le Méridien Lav",
". Drivers know the hotel entrances and drop you at reception, not on the main road. If you're in a private apartment, the side streets down to the sea can be narrow and steep. Put your exact address in the booking and we'll confirm the best drop-off point.": ". Vozači znaju ulaze u hotele i ostavljaju vas na recepciji, a ne na glavnoj cesti. Ako ste u privatnom apartmanu, sporedne ulice prema moru znaju biti uske i strme. Upišite točnu adresu u rezervaciju i potvrdit ćemo najbolje mjesto iskrcaja.",
"Staying in Podstrana, visiting Split": "Boravak u Podstrani, izleti u Split",
"Podstrana is a good base: quieter than Split, with long beaches, and only 15–20 minutes from the old town. Local buses run to Split regularly. For an evening out, a taxi back is easy to find in Split, but agree the price first.": "Podstrana je dobra baza: mirnija od Splita, s dugim plažama i samo 15–20 minuta od stare jezgre. Gradski autobusi redovito voze do Splita. Za večernji izlazak taksi natrag lako je naći u Splitu, ali cijenu dogovorite unaprijed.",
}
