# Blog posts, batch 6 (phase 2): Trogir; Baška Voda; Amadria Park
T = {
"Split Airport to Trogir Transfer Guide (2026) | Airport Split Transfer": "Vodič za transfer od Zračne luke Split do Trogira (2026.) | Airport Split Transfer",
"About 7 km. The drive takes 10–15 minutes, longer on summer Saturdays.": "Oko 7 km. Vožnja traje 10–15 minuta, ljeti subotom i dulje.",
"How much is a transfer from Split Airport to Trogir?": "Koliko košta transfer od Zračne luke Split do Trogira?",
"Around €35 for a car with up to 4 passengers and around €45 for a van with up to 8, per vehicle. The booking form shows the exact price for your address.": "Oko 35 € za auto s do 4 putnika i oko 45 € za kombi s do 8 putnika, po vozilu. Obrazac za rezervaciju pokazuje točnu cijenu za vašu adresu.",
"Can a car drive into Trogir old town?": "Može li auto ući u staru jezgru Trogira?",
"No, the old town is pedestrian-only. Drivers drop you at the nearest point, usually a few minutes' walk from your accommodation.": "Ne, stara jezgra je pješačka zona. Vozači vas ostavljaju na najbližem mjestu, obično nekoliko minuta hoda od smještaja.",
"Trogir is the easiest arrival on the whole Dalmatian coast. The UNESCO-listed old town sits only around seven kilometres west of Split Airport, and the drive usually takes 10–15 minutes. You can be walking along the riva before some passengers on your flight have collected their bags.": "Trogir je najlakši dolazak na cijeloj dalmatinskoj obali. Stara jezgra pod zaštitom UNESCO-a samo je sedam kilometara zapadno od Zračne luke Split, a vožnja obično traje 10–15 minuta. Možete šetati rivom prije nego što neki putnici s vašeg leta pokupe prtljagu.",
"Getting there by bus": "Autobusom",
"Local bus line 37 between Split and Trogir stops on the main road outside the airport. It runs frequently, the ride to Trogir is short, and a ticket costs a couple of euros (less if you buy it in the Promet Split app). It ends at Trogir bus station, just across the bridge from the old town.": "Gradski autobus linije 37 između Splita i Trogira staje na glavnoj cesti ispred aerodroma. Vozi često, vožnja do Trogira je kratka, a karta stoji par eura (manje ako je kupite u aplikaciji Promet Split). Završava na autobusnom kolodvoru u Trogiru, odmah preko mosta od stare jezgre.",
"It is a good option with a backpack. With suitcases, remember you'll walk from the terminal to the main road, and from the bus station to your accommodation, often across the stone streets of the old town.": "S ruksakom je to dobra opcija. S koferima imajte na umu da ćete hodati od terminala do glavne ceste i od kolodvora do smještaja, često po kamenim ulicama stare jezgre.",
"Taxi or private transfer": "Taksi ili privatni transfer",
"A rank taxi to Trogir is short but priced by the meter. A private transfer with us costs around": "Vožnja taksijem sa stajališta do Trogira je kratka, ali se naplaćuje po taksimetru. Privatni transfer kod nas košta oko",
"€35 in a car for up to 4": "35 € autom za do 4 osobe",
"€45 in a van for up to 8": "45 € kombijem za do 8 osoba",
", per vehicle, fixed before you fly. Your driver meets you in arrivals with a name sign and drives you to your address.": ", po vozilu, fiksno prije leta. Vozač vas dočekuje u dolaznom terminalu s vašim imenom na tabli i vozi na vašu adresu.",
"Where you'll be dropped off": "Gdje ćete izaći",
"Trogir's old town is on a small island connected by bridges, and it's closed to cars. Drivers drop you at the nearest point, usually by the bridge from the mainland or on the Čiovo side, and from there everything is a few minutes' walk. If you're staying on Čiovo island or in Seget Donji, the car can usually go all the way to the door. Put your full address in the booking and the driver will confirm the best spot.": "Stara jezgra Trogira nalazi se na otočiću povezanom mostovima i zatvorena je za automobile. Vozači vas ostavljaju na najbližem mjestu, obično kod mosta s kopna ili s čiovske strane, a odatle je sve nekoliko minuta hoda. Ako odsjedate na Čiovu ili u Segetu Donjem, auto obično može doći do samih vrata. Upišite punu adresu u rezervaciju i vozač će potvrditi najbolje mjesto.",
"Marinas and charter bases": "Marine i charter baze",
"Trogir is one of the busiest sailing bases in Croatia, and Saturday is charter changeover day. Traffic on the bridges gets slow in the afternoon. If you're joining a boat, write the marina name and the charter company in the booking notes and we'll drop you at the reception, not at the town car park.": "Trogir je jedna od najprometnijih nautičkih baza u Hrvatskoj, a subota je dan smjene charter posada. Promet na mostovima poslijepodne postaje spor. Ako idete na brod, u napomenu rezervacije upišite ime marine i charter tvrtke i ostavit ćemo vas na recepciji, a ne na gradskom parkiralištu.",
"Going back to the airport": "Povratak na aerodrom",
"Because the airport is so close, it's tempting to leave late. On summer Saturdays the bridge between Trogir and Čiovo can back up badly, so allow more time than the distance suggests. We plan pickup times around your flight time, tell us when you fly and we'll tell you when to be ready.": "Budući da je aerodrom tako blizu, primamljivo je krenuti kasno. Ljeti subotom most između Trogira i Čiova zna se jako zagušiti, pa računajte na više vremena nego što udaljenost govori. Vrijeme preuzimanja planiramo prema letu: recite nam kad letite i reći ćemo vam kada biti spremni.",
"Split Airport to Baška Voda Transfer (2026) | Airport Split Transfer": "Transfer od Zračne luke Split do Baške Vode (2026.) | Airport Split Transfer",
"How far is Baška Voda from Split Airport?": "Koliko je Baška Voda udaljena od Zračne luke Split?",
"About 65 km, around 1 hour 10 minutes by car.": "Oko 65 km, oko 1 sat i 10 minuta autom.",
"How much is a transfer from Split Airport to Baška Voda?": "Koliko košta transfer od Zračne luke Split do Baške Vode?",
"Around €115 for a car with up to 4 passengers and around €135 for a van with up to 8, per vehicle.": "Oko 115 € za auto s do 4 putnika i oko 135 € za kombi s do 8 putnika, po vozilu.",
"Is there a bus from Split Airport to Baška Voda?": "Vozi li autobus od Zračne luke Split do Baške Vode?",
"Not directly. You'd go into Split first and change to a coastal bus, which stops on the main road above the village.": "Ne izravno. Prvo biste otišli u Split i presjeli na autobus uz obalu, koji staje na glavnoj cesti iznad mjesta.",
"Baška Voda is a small, family-friendly resort at the northern end of the Makarska Riviera, between Brela and Makarska. From Split Airport it's about 65 km along the coast, around 1 hour 10 minutes by car.": "Baška Voda je malo, obiteljima prilagođeno mjesto na sjevernom kraju Makarske rivijere, između Brela i Makarske. Od Zračne luke Split udaljena je oko 65 km uz obalu, oko 1 sat i 10 minuta autom.",
"The drive": "Vožnja",
"The road bypasses Split, follows the coast through Podstrana and Omiš, and then runs below the Biokovo mountains to Baška Voda. There are sea views for most of the way. Saturday afternoons in summer are the slowest, when holiday rentals along the Riviera change over.": "Cesta zaobilazi Split, prati obalu kroz Podstranu i Omiš, a zatim vodi ispod Biokova do Baške Vode. Veći dio puta pogled je na more. Najsporije je ljeti subotom poslijepodne, kad se mijenjaju gosti u apartmanima na rivijeri.",
"Bus or transfer?": "Autobus ili transfer?",
"There's no direct bus from the airport. You'd take the shuttle into Split, then a coastal bus toward Makarska, which stops on the main road above Baška Voda. From there it's a walk downhill into the village: fine with a backpack, hard work with suitcases and children.": "Izravnog autobusa od aerodroma nema. Shuttleom biste otišli u Split, a zatim autobusom prema Makarskoj, koji staje na glavnoj cesti iznad Baške Vode. Odatle se do mjesta spušta pješice: s ruksakom u redu, s koferima i djecom naporno.",
"€115 in a car for up to 4": "115 € autom za do 4 osobe",
"€135 in a van for up to 8": "135 € kombijem za do 8 osoba",
", per vehicle. For a family of four, that's about €29 per person, from the arrivals hall to your door.": ", po vozilu. Za četveročlanu obitelj to je oko 29 € po osobi, od dolaznog terminala do vaših vrata.",
"Getting to your accommodation": "Do smještaja",
"Many apartments in Baška Voda are on the slope between the main road and the sea, on narrow streets with limited turning space. Our drivers know the village and will get you as close as the street allows. Put the full address, not just \"Baška Voda\", in the booking.": "Mnogi apartmani u Baškoj Vodi nalaze se na padini između glavne ceste i mora, u uskim ulicama s malo mjesta za okretanje. Naši vozači poznaju mjesto i dovest će vas onoliko blizu koliko ulica dopušta. U rezervaciju upišite punu adresu, a ne samo \"Baška Voda\".",
"Around Baška Voda": "Oko Baške Vode",
"is a scenic walk along the coastal path or a few minutes' drive north, with some of Croatia's most photographed pebble beaches.": "su slikovita šetnja obalnom stazom ili nekoliko minuta vožnje na sjever, s nekim od najfotografiranijih šljunčanih plaža u Hrvatskoj.",
"is 15 minutes south, with more restaurants and nightlife.": "je 15 minuta južno, s više restorana i noćnog života.",
"Biokovo Nature Park": "Park prirode Biokovo",
"rises right behind the village, with the Skywalk and a road to the summit.": "diže se odmah iza mjesta, sa Skywalkom i cestom do vrha.",
"If you're travelling with friends staying elsewhere on the Riviera, we can combine drop-offs in one booking, mention the extra stop and we'll confirm the price first.": "Ako putujete s prijateljima koji odsjedaju negdje drugdje na rivijeri, možemo spojiti iskrcaje u jednoj rezervaciji: navedite dodatno stajanje i prvo ćemo potvrditi cijenu.",
"Split Airport to Amadria Park Solaris Šibenik | Airport Split Transfer": "Od Zračne luke Split do Amadria Parka Solaris Šibenik | Airport Split Transfer",
"Traveling from Split Airport to Amadria Park Hotel Solaris in Šibenik? Fixed-price private transfer, meet & greet at arrivals, and door-to-door service.": "Putujete od Zračne luke Split do Amadria Park Hotela Solaris u Šibeniku? Privatni transfer po fiksnoj cijeni, doček u dolaznom terminalu i usluga od vrata do vrata.",
"How long does the transfer take?": "Koliko traje transfer?",
"Typically 50 to 70 minutes from Split Airport to Amadria Park Solaris.": "Obično 50 do 70 minuta od Zračne luke Split do Amadria Parka Solaris.",
"We track your flight in real time and adjust your pickup accordingly.": "Pratimo vaš let u stvarnom vremenu i prema njemu prilagođavamo preuzimanje.",
"Can I book a transfer for larger groups?": "Mogu li rezervirati transfer za veće grupe?",
"Yes. Vehicles are available for solo travelers, families, and groups of up to 8 passengers.": "Da. Imamo vozila za osobe koje putuju same, obitelji i grupe do 8 putnika.",
"Traveling from Split Airport (SPU) to Amadria Park Hotel Solaris in Šibenik? A private airport transfer is the fastest and most comfortable way to reach the resort, with door-to-door service and a fixed price.": "Putujete od Zračne luke Split (SPU) do Amadria Park Hotela Solaris u Šibeniku? Privatni aerodromski transfer najbrži je i najudobniji način da stignete do resorta, od vrata do vrata i po fiksnoj cijeni.",
"How far is Amadria Park Solaris from Split Airport?": "Koliko je Amadria Park Solaris udaljen od Zračne luke Split?",
"Distance: approximately 60 km (37 miles)": "Udaljenost: otprilike 60 km",
"Travel time: 50–70 minutes": "Trajanje vožnje: 50–70 minuta",
"Route: A1 motorway and the Adriatic coastal approach to Šibenik": "Ruta: autocesta A1 i obalni prilaz Šibeniku",
"Most transfers take around one hour, depending on traffic and the season.": "Većina transfera traje oko sat vremena, ovisno o prometu i sezoni.",
"Meet & Greet at Split Airport": "Doček na Zračnoj luci Split",
"Your driver will meet you in the Arrivals Hall with a name sign after your flight lands. We monitor flight arrivals, so if your plane is delayed, your pickup time is adjusted automatically at no extra charge.": "Nakon slijetanja vozač vas dočekuje u dolaznom terminalu s vašim imenom na tabli. Pratimo dolaske letova, pa ako avion kasni, vrijeme preuzimanja automatski se prilagođava bez dodatne naplate.",
"Why choose a private transfer?": "Zašto privatni transfer?",
"Fixed price with no hidden fees": "Fiksna cijena bez skrivenih troškova",
"Direct transfer to your hotel": "Izravan prijevoz do hotela",
"Flight tracking included": "Praćenje leta uključeno",
"Professional English-speaking driver": "Profesionalni vozač koji govori engleski",
"Child seats available on request": "Dječje sjedalice na zahtjev",
"Comfortable, air-conditioned vehicle": "Udobno vozilo s klimom",
"About Amadria Park Hotel Solaris": "O Amadria Park Hotelu Solaris",
"Amadria Park is one of Croatia's premier seaside resorts, located just south of Šibenik. The resort includes several hotels, family attractions, beaches, restaurants, and a marina, making it a popular destination for couples, families, and conference guests.": "Amadria Park jedan je od vodećih resorta uz more u Hrvatskoj, odmah južno od Šibenika. Ima nekoliko hotela, sadržaje za obitelji, plaže, restorane i marinu, pa je omiljen među parovima, obiteljima i gostima konferencija.",
"When booking your transfer, it's helpful to specify your exact hotel within the Amadria Park complex to ensure direct drop-off at the correct entrance.": "Pri rezervaciji navedite točan hotel unutar kompleksa Amadria Park kako bismo vas ostavili izravno na pravom ulazu.",
"Book Your Split Airport to Amadria Park Solaris Transfer": "Rezervirajte transfer od Zračne luke Split do Amadria Parka Solaris",
"Avoid waiting for taxis or public transport after your flight. A pre-booked private transfer offers a reliable, comfortable, and stress-free journey directly from Split Airport to Amadria Park Hotel Solaris in Šibenik.": "Izbjegnite čekanje taksija ili javnog prijevoza nakon leta. Unaprijed rezerviran privatni transfer nudi pouzdanu, udobnu i opuštenu vožnju izravno od Zračne luke Split do Amadria Park Hotela Solaris u Šibeniku.",
}
