# Prices +10% on 2026-10-07 (minimum fares unchanged): the English
# segments whose euro amounts changed, with the same change in the translation.
T = {
'A metered rank taxi usually costs €35–50 to Split city centre. A fixed-price private transfer costs around €55 for a car or €70–75 for a van.': 'Taksi sa stajališta s taksimetrom do centra Splita obično košta 35–50 €. Privatni transfer po fiksnoj cijeni stoji oko 55 € za auto ili 70–75 € za kombi.',
'The biggest saving is for groups. A van for up to eight people to Makarska costs around €205 in total: about €26 per person, only a little more than the bus, but from the arrivals hall to your door.': 'Najveća je ušteda za grupe. Kombi za do osam osoba do Makarske ukupno košta oko 205 €: oko 26 € po osobi, tek malo više od autobusa, ali od dolaznog terminala do vaših vrata.',
'Around €125 for a car with up to 4 passengers and around €150 for a van with up to 8, per vehicle.': 'Oko 125 € za auto s do 4 putnika i oko 150 € za kombi s do 8 putnika, po vozilu.',
'€125 in a car for up to 4': '125 € autom za do 4 osobe',
'€150 in a van for up to 8': '150 € kombijem za do 8 osoba',
", per vehicle. For a family of four, that's about €31 per person, from the arrivals hall to your door.": ', po vozilu. Za četveročlanu obitelj to je oko 31 € po osobi, od dolaznog terminala do vaših vrata.',
'Around €415 for a car with up to 4 passengers and around €500 for a van with up to 8, per vehicle.': 'Oko 415 € za auto s do 4 putnika i oko 500 € za kombi s do 8 putnika, po vozilu.',
'~€415 car / ~€500 van': '~415 € auto / ~500 € kombi',
'€415 in a car for up to 4': '415 € autom za do 4 osobe',
'€500 in a van for up to 8': '500 € kombijem za do 8 osoba',
", per vehicle. For a group of eight that's about €63 per person: not far from the catamaran, but directly from the arrivals hall to your hotel door in Dubrovnik, with no connection to make.": ', po vozilu. Za grupu od osmero to je oko 63 € po osobi: nedaleko od katamarana, ali izravno od dolaznog terminala do vrata hotela u Dubrovniku, bez presjedanja.',
'Around €170 for a car with up to 4 passengers and around €205 for a van with up to 8, per vehicle, fixed in advance.': 'Oko 170 € za auto s do 4 putnika i oko 205 € za kombi s do 8 putnika, po vozilu, fiksno unaprijed.',
'€170 in a car for up to 4': '170 € autom za do 4 osobe',
'€205 in a van for up to 8': '205 € kombijem za do 8 osoba',
". For a family of four that's €43 per person; for a group of eight in a van, about €26 each: close to the bus fare, without the change in Split.": '. Za četveročlanu obitelj to je 43 € po osobi; za grupu od osmero u kombiju oko 26 € po osobi: blizu cijene autobusa, bez presjedanja u Splitu.',
'~€170 car / ~€205 van': '~170 € auto / ~205 € kombi',
'Around €100 for a car with up to 4 passengers and around €140 for a van with up to 8, per vehicle.': 'Oko 100 € za auto s do 4 putnika i oko 140 € za kombi s do 8 putnika, po vozilu.',
'€100 in a car for up to 4': '100 € autom za do 4 osobe',
'€140 in a van for up to 8': '140 € kombijem za do 8 osoba',
'A private transfer costs around €60 for a car with up to 4 passengers and around €85 for a van with up to 8. Rank taxis are metered, so the price depends on traffic.': 'Privatni transfer košta oko 60 € za auto s do 4 putnika i oko 85 € za kombi s do 8 putnika. Taksiji sa stajališta voze s taksimetrom, pa cijena ovisi o prometu.',
'€60 in a car for up to 4': '60 € autom za do 4 osobe',
'€85 in a van for up to 8': '85 € kombijem za do 8 osoba',
'Around €55 for a car with up to 4 passengers and around €70–75 for a van with up to 8, per vehicle. The booking form shows the exact fixed price for your address.': 'Oko 55 € za auto s do 4 putnika i oko 70–75 € za kombi s do 8 putnika, po vozilu. Obrazac za rezervaciju pokazuje točnu fiksnu cijenu za vašu adresu.',
'€55 in a car for up to 4 people': '55 € autom za do 4 osobe',
'€70–75 in a van for up to 8': '70–75 € kombijem za do 8 osoba',
'~€55 car / ~€70 van': '~55 € auto / ~70 € kombi',
'The Renault Trafic takes up to 8 passengers and 8 suitcases, and the Mercedes V-Class up to 7 with 7 suitcases. You pay for the vehicle, not per seat, so the fuller it is, the less each person pays. A group of eight going from the airport to Makarska pays about €26 each.': 'Renault Trafic prima do 8 putnika i 8 kofera, a Mercedes V-Class do 7 putnika i 7 kofera. Plaćate vozilo, a ne sjedalo, pa što je vozilo punije, svatko plaća manje. Grupa od osmero od aerodroma do Makarske plaća oko 26 € po osobi.',
'Book This Trip · €280': 'Rezerviraj izlet · 280 €',
'From €475': 'Od 475 €',
'Book This Trip · €475': 'Rezerviraj izlet · 475 €',
'Both a private one-way transfer from Split Airport to Plitvice Lakes and a private full-day trip with return to Split start from €475. For a one-way transfer, the exact price depends on your pickup and drop-off address. Enter both in our booking form to see an instant, fixed price for the Sedan or for the Business Van/Van: tolls, fuel and meet-and-greet at arrivals are always included.': 'I privatni transfer u jednom smjeru od Zračne luke Split do Plitvičkih jezera i privatni cjelodnevni izlet s povratkom u Split počinju od 475 €. Za transfer u jednom smjeru točna cijena ovisi o adresi polazišta i odredišta. Upišite obje u obrazac za rezervaciju i odmah ćete vidjeti fiksnu cijenu za limuzinu ili kombi: cestarina, gorivo i doček u dolaznom terminalu uvijek su uključeni.',
}
