T = {
# booking widget
"Book Your Transfer": "Prenota il tuo transfer",
"Your Trip": "Il tuo viaggio",
"Edit": "Modifica",
"Route": "Percorso",
"Split Airport → Split": "Aeroporto di Spalato → Spalato",
"Trip type": "Tipo di viaggio",
"One way": "Solo andata",
"Outbound": "Andata",
"Return": "Andata e ritorno",
"Passengers": "Passeggeri",
"One Way": "Solo andata",
"5% discount on return transfers": "5% di sconto su andata e ritorno",
"Pickup": "Partenza",
"Split Airport, hotel, address, marina...": "Aeroporto di Spalato, hotel, indirizzo, marina...",
"Swap pickup and dropoff": "Inverti partenza e destinazione",
"Dropoff": "Destinazione",
"Hotel, address, marina, city...": "Hotel, indirizzo, marina, città...",
"Pickup and dropoff can't be the same address.": "Partenza e destinazione non possono essere lo stesso indirizzo.",
"Trip Details": "Dettagli del viaggio",
"Date": "Data",
"Time": "Ora",
"Select time": "Scegli l'ora",
"Return Date": "Data del ritorno",
"Return Time": "Ora del ritorno",
"Choose your vehicle": "Scegli il veicolo",
"Sedan": "Berlina",
"Škoda Superb or similar": "Škoda Superb o simile",
"Up to 4 pax": "Fino a 4 pers.",
"Business Van": "Van business",
"Mercedes-Benz V-Class": "Mercedes-Benz Classe V",
"Up to 7 pax": "Fino a 7 pers.",
"Van": "Van",
"Renault Trafic or similar": "Renault Trafic o simile",
"Up to 8 pax": "Fino a 8 pers.",
"Enter your pickup and dropoff to see your fixed price.": "Inserisci partenza e destinazione per vedere il prezzo fisso.",
"Calculating your price…": "Calcolo del prezzo…",
"Can't find your destination? Contact us on": "Non trovi la tua destinazione? Scrivici su",
"WhatsApp": "WhatsApp",
"or": "o",
"email": "e-mail",
"for a personalised quote.": "per un preventivo su misura.",
"Your Details": "I tuoi dati",
"Full Name": "Nome e cognome",
"Email": "E-mail",
"Phone": "Telefono",
"Add luggage, flight number or a note": "Aggiungi bagagli, numero di volo o una nota",
"Suitcases (optional)": "Valigie (facoltativo)",
"Flight Number (optional)": "Numero di volo (facoltativo)",
"e.g. OU491": "es. OU491",
"Notes (optional)": "Note (facoltativo)",
"Child seats, exact pickup address, special requests...": "Seggiolini per bambini, indirizzo esatto di partenza, richieste particolari...",
"By booking, you agree to our": "Prenotando accetti la nostra",
"Privacy Policy": "Informativa sulla privacy",
"Book Now": "Prenota ora",
"Booking request sent": "Richiesta di prenotazione inviata",
"Thank you! We've received your transfer request. Your driver's confirmation will be sent to your email shortly before pickup.": "Grazie! Abbiamo ricevuto la tua richiesta di transfer. La conferma con i dati dell'autista ti arriverà via e-mail prima del ritiro.",
"Booking reference": "Codice prenotazione",
"Vehicle": "Veicolo",
"Total": "Totale",
"Chat on WhatsApp": "Scrivici su WhatsApp",
"Also visiting Plitvice Lakes or Krka National Park? We run private day trips too.": "Visiti anche i Laghi di Plitvice o il Parco nazionale di Krka? Organizziamo anche escursioni private di un giorno.",
"See Our Day Trips →": "Scopri le escursioni →",
"Need to change anything?": "Devi cambiare qualcosa?",
"Contact us anytime.": "Contattaci quando vuoi.",
"Price Summary": "Riepilogo prezzo",
"Enter a pickup and dropoff address to see your fixed price and trip details here.": "Inserisci l'indirizzo di partenza e di destinazione: qui vedrai il prezzo fisso e i dettagli del viaggio.",
"Sedan, Škoda Superb": "Berlina, Škoda Superb",
"Fixed price, all-inclusive. No hidden fees, no taximeter.": "Prezzo fisso, tutto incluso. Nessun costo nascosto, nessun tassametro.",

# homepage
"Split Airport Transfers | Airport Split Transfer": "Transfer e taxi dall'aeroporto di Spalato a prezzo fisso | Airport Split Transfer",
"Fixed-price Split Airport transfers. Book a private transfer from Split Airport instead of a Split Airport taxi: meet & greet, flight tracking, 5% off returns.": "Transfer privati dall'aeroporto di Spalato (Split) a prezzo fisso, un'alternativa al taxi: accoglienza con cartello, monitoraggio del volo e 5% di sconto su andata e ritorno.",
"Airport Split Transfer": "Airport Split Transfer",
"Split-Dalmatia County, Croatia": "Regione spalatino-dalmata, Croazia",
"Fiona Maher": "Fiona Maher",
"Ivan was so friendly and helpful. We were travelling with our little 9 month old and he really helped us and made sure all was ok. Gave us great recommendations too! Nicest journey we have had as it is tough with a baby, really made it easy for us getting back to airport and fitting all our luggage.": "Ivan was so friendly and helpful. We were travelling with our little 9 month old and he really helped us and made sure all was ok. Gave us great recommendations too! Nicest journey we have had as it is tough with a baby, really made it easy for us getting back to airport and fitting all our luggage.",
"Ben Huffman": "Ben Huffman",
"Ivan is an excellent driver and I would highly recommend him for your driving needs. He is safe, intuitive, friendly, helpful. His car is clean, smoke free, and he was early for pick up time.": "Ivan is an excellent driver and I would highly recommend him for your driving needs. He is safe, intuitive, friendly, helpful. His car is clean, smoke free, and he was early for pick up time.",
"Chaneze B.": "Chaneze B.",
"I recommend, we were late for our plane and he helped us a lot! Nice drive and kind man. Thank you.": "I recommend, we were late for our plane and he helped us a lot! Nice drive and kind man. Thank you.",
"How much does a private transfer from Split Airport cost?": "Quanto costa un transfer privato dall'aeroporto di Spalato?",
"The exact price depends on your pickup and drop-off address and the vehicle you choose. Enter your details in the booking form above for an instant, fixed price: tolls, fuel and meet-and-greet at arrivals are always included, with no hidden fees.": "Il prezzo esatto dipende dall'indirizzo di partenza e di arrivo e dal veicolo scelto. Inserisci i dati nel modulo di prenotazione qui sopra e ottieni subito un prezzo fisso: pedaggi, carburante e accoglienza agli arrivi sono sempre inclusi, senza costi nascosti.",
"Which destinations do you cover from Split Airport?": "Quali destinazioni servite dall'aeroporto di Spalato?",
"We run private, fixed-price transfers from Split Airport to Split, Trogir, Omiš, Makarska, Šibenik, Zadar, Dubrovnik, Plitvice Lakes and every other major town and village along the Dalmatian coast.": "Effettuiamo transfer privati a prezzo fisso dall'aeroporto di Spalato verso Spalato, Trogir, Omiš, Makarska, Šibenik, Zadar, Dubrovnik, i Laghi di Plitvice e tutte le principali località della costa dalmata.",
"What happens if my flight is delayed?": "Cosa succede se il mio volo è in ritardo?",
"We monitor your flight number in real time, so your driver adjusts the pickup automatically. There is no extra charge for reasonable delays.": "Monitoriamo il tuo volo in tempo reale, così l'autista adegua automaticamente l'orario di ritiro. Per i ritardi ragionevoli non c'è alcun costo aggiuntivo.",
"Can I book a return transfer?": "Posso prenotare anche il ritorno?",
"Yes, select \"Return\" when booking to schedule both legs of your trip together, with a 5% discount on the total price.": "Sì, scegli \"Andata e ritorno\" durante la prenotazione per organizzare entrambe le tratte insieme, con il 5% di sconto sul prezzo totale.",
"What vehicles can I choose from?": "Quali veicoli posso scegliere?",
"A Škoda Superb sedan (1–4 passengers), a Mercedes-Benz V-Class (1–7 passengers) or a Renault Trafic van (1–8 passengers), all at a fixed price per vehicle.": "Una berlina Škoda Superb (1–4 passeggeri), una Mercedes-Benz Classe V (1–7 passeggeri) o un van Renault Trafic (1–8 passeggeri), tutti a prezzo fisso per veicolo.",
"Are child seats available?": "Avete seggiolini per bambini?",
"Yes, child seats are provided free of charge on request, just mention it when booking.": "Sì, i seggiolini sono gratuiti su richiesta: basta indicarlo al momento della prenotazione.",
"How do I pay for my transfer?": "Come si paga il transfer?",
"We accept both card and cash. The price is agreed and confirmed before you travel, so there are no surprises on the day.": "Accettiamo carta e contanti. Il prezzo viene concordato e confermato prima del viaggio, quindi il giorno stesso non ci sono sorprese.",
"Home": "Home",
"Popular Destinations": "Destinazioni popolari",
"Hotels": "Hotel",
"Day Trips": "Escursioni",
"Vehicles": "Veicoli",
"Services": "Servizi",
"Blog": "Blog",
"About": "Chi siamo",
"Contact": "Contatti",
"EN": "IT",
"English": "English",
"Deutsch": "Deutsch",
"Svenska": "Svenska",
"Norsk": "Norsk",
"Open menu": "Apri il menu",
"Close menu": "Chiudi il menu",
"×": "×",
"Booking": "Prenotazione",
"Routes": "Percorsi",
"Hotel Transfers": "Transfer per hotel",
"About Us": "Chi siamo",
"Language": "Lingua",
"DE": "DE",
"SV": "SV",
"NO": "NO",
"Split Airport Transfers": "Transfer dall'aeroporto di Spalato",
"Fixed-price private transfers from Split Airport across the Dalmatian coast.": "Transfer privati a prezzo fisso dall'aeroporto di Spalato lungo tutta la costa dalmata.",
"35+ Google Reviews": "35+ recensioni Google",
"Licensed Taxi": "Taxi autorizzato",
"Fixed Prices": "Prezzi fissi",
"Card & Cash": "Carta e contanti",
"Free Child Seats": "Seggiolini gratuiti",
"Prefer to chat?": "Preferisci scriverci?",
"WhatsApp us": "Scrivici su WhatsApp",
"Popular Routes": "Percorsi più richiesti",
"Where We Take You": "Dove ti portiamo",
"View All Routes →": "Tutti i percorsi →",
"Split City Center / Ferry Port": "Centro di Spalato / porto traghetti",
"Podstrana": "Podstrana",
"Omiš": "Omiš",
"Makarska": "Makarska",
"Dubrovnik": "Dubrovnik",
"Plitvice Lakes": "Laghi di Plitvice",
"Zadar": "Zadar",
"Brela": "Brela",
"Our Vehicles": "I nostri veicoli",
"Three Vehicles, One Standard": "Tre veicoli, un unico standard",
"View All Vehicles →": "Tutti i veicoli →",
"White Škoda Superb sedan used for private Split Airport transfers": "Berlina Škoda Superb bianca per transfer privati dall'aeroporto di Spalato",
"White · Executive Sedan": "Bianca · berlina executive",
"AC": "Aria condizionata",
"Black Mercedes-Benz V-Class van used for group airport transfers from Split": "Mercedes-Benz Classe V nera per transfer di gruppo dall'aeroporto di Spalato",
"Black · Premium Van": "Nero · van premium",
"White Renault Trafic minibus used for larger group transfers from Split": "Minibus Renault Trafic bianco per gruppi più numerosi da Spalato",
"White · Group Transfer": "Bianco · transfer di gruppo",
"Clean & comfortable vehicles": "Veicoli puliti e confortevoli",
"AC in all vehicles": "Aria condizionata in tutti i veicoli",
"Plenty of luggage space": "Tanto spazio per i bagagli",
"Baby seats on request": "Seggiolini per neonati su richiesta",
"Non smoking": "Non fumatori",
"60 min": "60 min",
"Free Waiting at the Airport": "di attesa gratuita in aeroporto",
"Live": "In tempo reale",
"Flight Tracking": "Monitoraggio del volo",
"Free": "Gratuita",
"Cancellation": "Cancellazione",
"Straight to your hotel door": "Fino alla porta del tuo hotel",
"Fixed-price transfers to the resorts and hotels guests ask for most.": "Transfer a prezzo fisso verso i resort e gli hotel più richiesti dai nostri clienti.",
"Amadria Park Šibenik (Solaris)": "Amadria Park Šibenik (Solaris)",
"Hotel Le Meridien Lav": "Hotel Le Meridien Lav",
"Radisson Blu Resort Split": "Radisson Blu Resort Split",
"Medora Auri, Podgora": "Medora Auri, Podgora",
"All hotel transfers →": "Tutti i transfer per hotel →",
"How It Works": "Come funziona",
"From Booking to Arrival": "Dalla prenotazione all'arrivo",
"Request Your Transfer": "Richiedi il transfer",
"Enter your flight details, destination and passenger count: see the fixed price instantly, no obligation.": "Inserisci i dati del volo, la destinazione e il numero di passeggeri: vedi subito il prezzo fisso, senza impegno.",
"Booking Request Received": "Richiesta ricevuta",
"We'll confirm your transfer by email with pickup details.": "Ti confermiamo il transfer via e-mail con tutti i dettagli del ritiro.",
"We Track Your Flight": "Monitoriamo il tuo volo",
"Live flight monitoring means your driver adjusts pickup time automatically if your flight is delayed.": "Grazie al monitoraggio in tempo reale, l'autista adegua l'orario di ritiro se il volo è in ritardo.",
"Meet Your Driver": "Incontra l'autista",
"Your driver waits at arrivals with a name board. Luggage assistance and a direct route to your address.": "L'autista ti aspetta agli arrivi con un cartello con il tuo nome, ti aiuta con i bagagli e ti porta direttamente al tuo indirizzo.",
"Testimonials": "Recensioni",
"What Our Customers Say": "Cosa dicono i nostri clienti",
"based on 35+ Google reviews": "su oltre 35 recensioni Google",
"Read our Google reviews →": "Leggi le recensioni su Google →",
"“Ivan was so friendly and helpful. We were travelling with our little 9 month old and he really helped us and made sure all was ok. Gave us great recommendations too!”": "“Ivan è stato gentilissimo e disponibile. Viaggiavamo con la nostra bimba di 9 mesi, ci ha aiutato tanto e si è assicurato che fosse tutto a posto. Ci ha dato anche ottimi consigli!”",
"Fiona Maher, Google review": "Fiona Maher, recensione Google (tradotta)",
"“Ivan is an excellent driver and I would highly recommend him for your driving needs. He is safe, intuitive, friendly, helpful. His car is clean, smoke free, and he was early for pick up time.”": "“Ivan è un ottimo autista e lo consiglio vivamente. Guida in modo sicuro, è attento, cordiale e disponibile. L'auto è pulita, senza odore di fumo, ed è arrivato persino in anticipo.”",
"Ben Huffman, Google review": "Ben Huffman, recensione Google (tradotta)",
"“I recommend, we were late for our plane and he helped us a lot! Nice drive and kind man. Thank you.”": "“Lo consiglio, eravamo in ritardo per l'aereo e ci ha aiutato tantissimo! Viaggio piacevole e persona gentile. Grazie.”",
"Chaneze B., Google review": "Chaneze B., recensione Google (tradotta)",
"FAQ": "Domande frequenti",
"Common Questions": "Domande frequenti",
"Need help or a custom offer?": "Ti serve aiuto o un'offerta su misura?",
"Contact us on WhatsApp. We reply in minutes!": "Scrivici su WhatsApp. Rispondiamo in pochi minuti!",
"See fixed prices": "Vedi i prezzi fissi",
"Private transfers and tours across Croatia. Your journey, our priority.": "Transfer privati ed escursioni in tutta la Croazia. Il tuo viaggio, la nostra priorità.",
"Instagram": "Instagram",
"TikTok": "TikTok",
"Google": "Google",
"Location": "Dove siamo",
"Quick Links": "Link utili",
"Split Airport Taxi": "Taxi aeroporto di Spalato",
"Split Airport → Split City Center / Ferry Port": "Aeroporto di Spalato → centro di Spalato / porto",
"Split Airport → Podstrana": "Aeroporto di Spalato → Podstrana",
"Split Airport → Omiš": "Aeroporto di Spalato → Omiš",
"Split Airport → Makarska": "Aeroporto di Spalato → Makarska",
"Split Airport → Brela": "Aeroporto di Spalato → Brela",
"All routes": "Tutti i percorsi",
"Split, Croatia": "Spalato, Croazia",
"© 2026 Airport Split Transfer. All rights reserved.": "© 2026 Airport Split Transfer. Tutti i diritti riservati.",
"Terms & Conditions": "Termini e condizioni",
"Cookie Preferences": "Preferenze cookie",
"The exact price depends on your pickup and drop-off address and the vehicle you choose. Enter your details in the booking form above for an instant, fixed price: tolls, fuel and meet-and-greet at arrivals are always included, with no hidden fees. Our": "Il prezzo esatto dipende dall'indirizzo di partenza e di arrivo e dal veicolo scelto. Inserisci i dati nel modulo di prenotazione qui sopra e ottieni subito un prezzo fisso: pedaggi, carburante e accoglienza agli arrivi sono sempre inclusi, senza costi nascosti. La pagina",
"Split Airport taxi": "taxi aeroporto di Spalato",
"page explains how the fixed price compares with a metered rank taxi.": "spiega la differenza tra il prezzo fisso e un taxi con tassametro.",
}
