T = {
# split-airport-transfers
"Split Airport Taxi at a Fixed Price | Airport Split Transfer": "Taxi aeroporto di Spalato a prezzo fisso | Airport Split Transfer",
"Private Split Airport taxi at a fixed price, no meter. English-speaking drivers, flight tracking and 24/7 pickups to Split, Trogir, Omiš, Makarska and more.": "Taxi privato dall'aeroporto di Spalato (Split) a prezzo fisso, senza tassametro. Autisti che parlano inglese, monitoraggio del volo e servizio 24/7 per Spalato, Trogir, Omiš, Makarska e oltre.",
"Airport Taxi": "Taxi aeroporto",
"How much does a taxi from Split Airport cost?": "Quanto costa un taxi dall'aeroporto di Spalato?",
"The exact price depends on your pickup and drop-off address and the vehicle you choose. Enter your details in our booking form for an instant, fixed price: tolls, fuel and meet-and-greet at arrivals are always included, with no hidden fees.": "Il prezzo esatto dipende dall'indirizzo di partenza e di arrivo e dal veicolo scelto. Inserisci i dati nel modulo di prenotazione e ottieni subito un prezzo fisso: pedaggi, carburante e accoglienza agli arrivi sono sempre inclusi, senza costi nascosti.",
"How long does it take to get from Split Airport to Split city center?": "Quanto ci vuole dall'aeroporto di Spalato al centro città?",
"The drive from Split Airport to Split city center takes about 20–25 minutes under normal traffic conditions.": "Il tragitto dall'aeroporto al centro di Spalato dura circa 20–25 minuti con traffico normale.",
"Do you offer transfers to Trogir, Omiš, Makarska and other coastal towns?": "Fate transfer anche per Trogir, Omiš, Makarska e le altre località della costa?",
"Yes. We run private, fixed-price transfers from Split Airport to Trogir, Omiš, Makarska, Šibenik, Zadar, Novalja and every other major town along the Dalmatian coast.": "Sì. Effettuiamo transfer privati a prezzo fisso dall'aeroporto di Spalato verso Trogir, Omiš, Makarska, Šibenik, Zadar, Novalja e tutte le principali località della costa dalmata.",
"Is the price really fixed, with no hidden fees?": "Il prezzo è davvero fisso, senza costi nascosti?",
"Yes. The price is agreed before you travel, based on the vehicle class rather than a taximeter, and already includes tolls, fuel and meet-and-greet at arrivals.": "Sì. Il prezzo viene concordato prima del viaggio in base al tipo di veicolo, non al tassametro, e include già pedaggi, carburante e accoglienza agli arrivi.",
"Can I book a return transfer from my hotel to Split Airport?": "Posso prenotare anche il ritorno dall'hotel all'aeroporto di Spalato?",
"Yes, select \"Return\" when booking to schedule both legs of your trip together. 5% discount on return transfers.": "Sì, scegli \"Andata e ritorno\" durante la prenotazione per organizzare entrambe le tratte insieme. 5% di sconto su andata e ritorno.",
"What vehicles are available for Split Airport transfers?": "Quali veicoli sono disponibili per i transfer dall'aeroporto di Spalato?",
"We offer a Škoda Superb sedan (1–4 passengers), a Mercedes-Benz V-Class (1–7 passengers) and a Renault Trafic van (1–8 passengers), all at a fixed price per vehicle.": "Offriamo una berlina Škoda Superb (1–4 passeggeri), una Mercedes-Benz Classe V (1–7 passeggeri) e un van Renault Trafic (1–8 passeggeri), tutti a prezzo fisso per veicolo.",
"How do I book a Split Airport taxi online?": "Come prenoto online un taxi dall'aeroporto di Spalato?",
"Enter your pickup and drop-off address, choose your date, time and vehicle in the booking form on this page, and you'll see an instant fixed price, no account or deposit required to reserve.": "Nel modulo di questa pagina inserisci partenza e destinazione, scegli data, ora e veicolo e vedrai subito il prezzo fisso. Per prenotare non servono account né acconti.",
"Hrvatski": "Hrvatski",
"Italiano": "Italiano",
"IT": "IT",
"HR": "HR",
"Private Airport Taxi": "Taxi privato dall'aeroporto",
"Fixed-price private taxi from Split Airport to Split, Trogir, Omiš, Makarska and the whole Dalmatian coast: English-speaking drivers, flight tracking and 24/7 service.": "Taxi privato a prezzo fisso dall'aeroporto di Spalato verso Spalato, Trogir, Omiš, Makarska e tutta la costa dalmata: autisti che parlano inglese, monitoraggio del volo e servizio 24/7.",
"Why Choose Us": "Perché sceglierci",
"Split Airport Taxi Done Right": "Il taxi dall'aeroporto come si deve",
"No meter, no hidden costs": "Niente tassametro, niente costi nascosti",
"Pickup adjusts to delays": "Il ritiro si adatta ai ritardi",
"24/7 Service": "Servizio 24/7",
"Every flight, day or night": "Ogni volo, di giorno e di notte",
"Free Cancellation": "Cancellazione gratuita",
"Plans change, no penalty": "I piani cambiano, nessuna penale",
"Split Airport Taxi To Every Coastal Town": "Taxi dall'aeroporto per ogni località della costa",
"Split": "Spalato",
"Trogir": "Trogir",
"Šibenik": "Šibenik",
"Novalja": "Novalja",
"Three Vehicles, One Fixed Price": "Tre veicoli, un prezzo fisso",
"Meter-free and fixed in advance: ideal for solo travellers or couples who want a quick, quiet ride straight to their address.": "Senza tassametro e con prezzo fissato in anticipo: ideale per chi viaggia da solo o in coppia e vuole un tragitto rapido e tranquillo fino all'indirizzo.",
"Select Vehicle": "Scegli il veicolo",
"Extra legroom and leather seating for families or small groups who want a private-driver feel without the higher cost of a chauffeur service.": "Più spazio per le gambe e sedili in pelle per famiglie e piccoli gruppi che vogliono l'esperienza di un autista privato senza il costo di un servizio di lusso.",
"The practical pick for wedding parties, sports teams and larger groups, plenty of room for people and bags in one taxi.": "La scelta pratica per matrimoni, squadre sportive e gruppi numerosi, con tanto spazio per persone e bagagli in un unico veicolo.",
"View All Vehicles": "Tutti i veicoli",
"“Great experience. Arrived ahead of time and charged a fair price to the airport. Plenty of space in the car for our luggage and got to the airport in time.”": "“Ottima esperienza. È arrivato in anticipo e ci ha chiesto un prezzo onesto per l'aeroporto. Tanto spazio in auto per i bagagli e siamo arrivati in aeroporto in tempo.”",
"Karen Holland, Google Local Guide": "Karen Holland, Google Local Guide (tradotta)",
"“First class service, reliable, friendly, quick and affordable. Professional and quick drive taking care about the traffic and about passengers.”": "“Servizio di prima classe, affidabile, cordiale, rapido e conveniente. Guida professionale e veloce, attenta al traffico e ai passeggeri.”",
"Nikola Stosic, Google review": "Nikola Stosic, recensione Google (tradotta)",
"“Excellent transfer service: the driver was professional, friendly and punctual, and the journey was smooth and comfortable. Communication was great throughout.”": "“Servizio di transfer eccellente: l'autista è stato professionale, cordiale e puntuale, e il viaggio è stato tranquillo e confortevole. Comunicazione ottima dall'inizio alla fine.”",
"Zacker Zap, Google review": "Zacker Zap, recensione Google (tradotta)",
"Split Airport Taxi: Common Questions": "Taxi aeroporto di Spalato: domande frequenti",
"Enter your pickup and drop-off address, choose your date, time and vehicle in the booking form below, and you'll see an instant fixed price, no account or deposit required to reserve.": "Nel modulo qui sotto inserisci partenza e destinazione, scegli data, ora e veicolo e vedrai subito il prezzo fisso. Per prenotare non servono account né acconti.",
"Book Your Fixed-Price Split Airport Taxi": "Prenota il taxi dall'aeroporto a prezzo fisso",
"Enter your route below for an instant quote: no hidden fees, no obligation.": "Inserisci il percorso qui sotto e ricevi subito il prezzo: nessun costo nascosto, nessun impegno.",
"Split Airport → Šibenik": "Aeroporto di Spalato → Šibenik",
"Split Airport → Zadar": "Aeroporto di Spalato → Zadar",

# destinations
"Split Airport Transfers: All Destinations | Airport Split Transfer": "Transfer dall'aeroporto di Spalato: tutte le destinazioni | Airport Split Transfer",
"Browse every destination served by Airport Split Transfer from Split Airport, with fixed prices, distances and travel times.": "Tutte le destinazioni che serviamo dall'aeroporto di Spalato, con prezzi fissi, distanze e tempi di percorrenza.",
"Destinations": "Destinazioni",
"How many destinations do you serve from Split Airport?": "Quante destinazioni servite dall'aeroporto di Spalato?",
"Dozens: from Split itself to Dubrovnik and Plitvice Lakes National Park, plus smaller coastal villages and marinas. Use the search box above to find yours.": "Decine: da Spalato stessa a Dubrovnik e al Parco nazionale dei Laghi di Plitvice, oltre a piccoli paesi costieri e marine. Usa la casella di ricerca qui sopra per trovare la tua.",
"Is the price the same in both directions?": "Il prezzo è lo stesso nelle due direzioni?",
"Yes. Each destination card above links to both directions, \"From Airport\" and \"To Airport\", priced the same way, based on the exact pickup and drop-off address.": "Sì. Ogni scheda qui sopra porta a entrambe le direzioni, \"Dall'aeroporto\" e \"Per l'aeroporto\", con lo stesso calcolo del prezzo, in base all'indirizzo esatto di partenza e di arrivo.",
"My destination isn't listed, can I still book a transfer?": "La mia destinazione non è in elenco, posso comunque prenotare?",
"Yes. We cover most of the Dalmatian coast beyond what's listed here, contact us with your address for a quote.": "Sì. Copriamo gran parte della costa dalmata anche oltre quanto elencato qui: mandaci il tuo indirizzo e ti facciamo un preventivo.",
"How is the exact price calculated?": "Come viene calcolato il prezzo esatto?",
"The price is computed instantly from your precise pickup and drop-off address and chosen vehicle, enter the details in the booking form on the homepage for a fixed quote.": "Il prezzo viene calcolato subito in base all'indirizzo preciso di partenza e di arrivo e al veicolo scelto: inserisci i dati nel modulo della home page per ottenere un prezzo fisso.",
"Can I search for my destination on this page?": "Posso cercare la mia destinazione in questa pagina?",
"Yes, type a town name into the search box above the destination cards to filter the list instantly.": "Sì, scrivi il nome della località nella casella di ricerca sopra le schede e l'elenco si filtra subito.",
"Transfers Across the Dalmatian Coast": "Transfer lungo la costa dalmata",
"Fixed, all-inclusive one-way prices from Split Airport to every major destination on the coast. Select a destination for distance, travel time and answers to common questions.": "Prezzi fissi di sola andata, tutto incluso, dall'aeroporto di Spalato a tutte le principali destinazioni della costa. Scegli una destinazione per distanza, tempo di viaggio e risposte alle domande più comuni.",
"Search a destination…": "Cerca una destinazione…",
"No destinations match your search.": "Nessuna destinazione corrisponde alla ricerca.",
"From Airport": "Dall'aeroporto",
"To Airport": "Per l'aeroporto",
"Baška Voda": "Baška Voda",
"Vodice": "Vodice",
"Primošten": "Primošten",
"Kaštela": "Kaštela",
"More of the Coast": "Altre località della costa",
"Smaller Villages & Marinas": "Piccoli paesi e marine",
"Quieter coastal spots, sailing bases and hamlets along the same routes: every one a private, fixed-price transfer from Split Airport.": "Località costiere più tranquille, basi charter e piccoli borghi lungo gli stessi percorsi: per ognuno un transfer privato a prezzo fisso dall'aeroporto di Spalato.",
"Rogoznica": "Rogoznica",
"Ražanj": "Ražanj",
"Grebaštica": "Grebaštica",
"Vinišće": "Vinišće",
"Seget Donji": "Seget Donji",
"Pisak": "Pisak",
"Marušići": "Marušići",
"Promajna": "Promajna",
"Tučepi": "Tučepi",
"Živogošće": "Živogošće",
"Podgora": "Podgora",
"Murter": "Murter",
"Biograd na Moru": "Biograd na Moru",
"ACI Marina Split": "ACI Marina Split",
"ACI Marina Trogir": "ACI Marina Trogir",
"Marina Baotić": "Marina Baotić",
"Marina Kaštela": "Marina Kaštela",
"Marina Agana": "Marina Agana",
"Marina Mandalina": "Marina Mandalina",
"Marina Dalmacija": "Marina Dalmacija",
"Marina Frapa": "Marina Frapa",
"Marina Kornati": "Marina Kornati",
"My destination isn't listed: can I still book a transfer?": "La mia destinazione non è in elenco: posso comunque prenotare?",

# fleet
"Our Fleet: Škoda Superb, V-Class, Trafic | Airport Split Transfer": "I nostri veicoli: Škoda Superb, Classe V, Trafic | Airport Split Transfer",
"Explore the Airport Split Transfer fleet: Škoda Superb executive sedan, Mercedes-Benz V-Class premium van, and Renault Trafic for groups.": "Scopri i veicoli di Airport Split Transfer: berlina executive Škoda Superb, van premium Mercedes-Benz Classe V e Renault Trafic per i gruppi.",
"Fleet": "Veicoli",
"What's the difference between the Sedan, Business Van and Van?": "Che differenza c'è tra berlina, van business e van?",
"The Sedan (Škoda Superb) suits 1–4 passengers, the Business Van (Mercedes-Benz V-Class) suits 1–7 with a more premium interior, and the Van (Renault Trafic) suits 1–8 for larger groups. All three include air conditioning and a professional driver.": "La berlina (Škoda Superb) è adatta a 1–4 passeggeri, il van business (Mercedes-Benz Classe V) a 1–7 con interni più curati e il van (Renault Trafic) a 1–8 per i gruppi più numerosi. Tutti e tre hanno aria condizionata e un autista professionista.",
"How much luggage fits in each vehicle?": "Quanti bagagli entrano in ogni veicolo?",
"The Sedan comfortably fits 3 large suitcases, the Business Van 7, and the Van 8, plenty of room for carry-on bags and beach gear as well.": "Nella berlina entrano comodamente 3 valigie grandi, nel van business 7 e nel van 8, con spazio anche per bagagli a mano e attrezzatura da spiaggia.",
"Can I choose a specific vehicle when I book?": "Posso scegliere un veicolo preciso quando prenoto?",
"Yes, select your preferred vehicle directly on this page or in the booking form, and the price updates instantly.": "Sì, scegli il veicolo direttamente in questa pagina o nel modulo di prenotazione e il prezzo si aggiorna subito.",
"Are child seats available in all vehicles?": "I seggiolini sono disponibili in tutti i veicoli?",
"Yes, child seats are available free of charge on request in any of the three vehicles.": "Sì, i seggiolini sono gratuiti su richiesta in tutti e tre i veicoli.",
"Are the prices shown on this page final?": "I prezzi indicati in questa pagina sono definitivi?",
"They're sample \"from\" prices for common routes. The exact price depends on your precise pickup and drop-off address: enter your details in the booking form for an instant, fixed quote.": "Sono prezzi indicativi \"a partire da\" per i percorsi più comuni. Il prezzo esatto dipende dall'indirizzo preciso di partenza e di arrivo: inserisci i dati nel modulo di prenotazione per un prezzo fisso immediato.",
"Is the Van suitable for a group with a lot of luggage?": "Il van è adatto a un gruppo con molti bagagli?",
"Yes, the Renault Trafic is built for larger groups such as wedding parties and families, with plenty of space for luggage alongside 8 passengers.": "Sì, il Renault Trafic è pensato per gruppi numerosi come matrimoni e famiglie, con tanto spazio per i bagagli oltre a 8 passeggeri.",
"The Fleet": "I veicoli",
"Vehicles for Every Journey": "Un veicolo per ogni viaggio",
"Three vehicle classes, one standard of service. Every car and van is late-model, cleaned between every transfer and driven by a licensed professional chauffeur.": "Tre classi di veicoli, un unico standard di servizio. Ogni auto e ogni van è di modello recente, viene pulito dopo ogni transfer ed è guidato da un autista professionista autorizzato.",
"Our vehicles": "I nostri veicoli",
"An elegant sedan for solo travellers, couples and business trips: quiet, comfortable and quick through traffic.": "Una berlina elegante per chi viaggia da solo, in coppia o per lavoro: silenziosa, comoda e agile nel traffico.",
"Sample route": "Percorso di esempio",
"From": "Da",
"Select Sedan": "Scegli la berlina",
"The flagship of the fleet: leather seating, cabin space and a private-driver feel for families and small groups.": "Il fiore all'occhiello: sedili in pelle, abitacolo spazioso e l'esperienza di un autista privato per famiglie e piccoli gruppi.",
"Select Business Van": "Scegli il van business",
"Built for groups: wedding parties, teams and larger families travelling together with plenty of luggage.": "Pensato per i gruppi: matrimoni, squadre e famiglie numerose che viaggiano insieme con tanti bagagli.",
"Select Van": "Scegli il van",

# services
"Services: Airport, Direct and Group Transfers | Airport Split Transfer": "Servizi: transfer aeroportuali, diretti e di gruppo | Airport Split Transfer",
"Private airport transfers, point-to-point rides, return trips, group and wedding transfers, and hourly hire across the Dalmatian coast.": "Transfer privati dall'aeroporto, tragitti diretti tra località, andata e ritorno, transfer per gruppi e matrimoni e noleggio con autista a ore lungo la costa dalmata.",
"What transfer services do you offer besides airport pickups?": "Quali servizi offrite oltre al ritiro in aeroporto?",
"Airport arrivals and departures, point-to-point transfers between towns, return transfers, group and wedding transfers, and hourly or full-day vehicle hire.": "Arrivi e partenze in aeroporto, transfer diretti tra località, andata e ritorno, transfer per gruppi e matrimoni e noleggio con autista a ore o per l'intera giornata.",
"Do you offer transfers between two towns that don't involve the airport?": "Fate transfer anche tra due località, senza passare dall'aeroporto?",
"Yes, direct point-to-point transfers are available between any two towns along the coast, such as Split to Makarska or Šibenik to Zadar.": "Sì, effettuiamo transfer diretti tra due località qualsiasi della costa, per esempio Spalato–Makarska o Šibenik–Zadar.",
"Is there a discount for booking a return transfer?": "C'è uno sconto se prenoto andata e ritorno?",
"Yes, return transfers booked together receive a 5% discount on the total price.": "Sì, prenotando insieme andata e ritorno ottieni il 5% di sconto sul prezzo totale.",
"Can you arrange transport for a wedding or large group?": "Potete organizzare il trasporto per un matrimonio o un gruppo numeroso?",
"Yes, we can combine the Renault Trafic van with multiple Mercedes-Benz V-Class vehicles to move wedding parties, teams or larger families together.": "Sì, possiamo combinare il van Renault Trafic con più Mercedes-Benz Classe V per spostare insieme invitati, squadre o famiglie numerose.",
"Do you offer hourly or full-day hire for touring?": "È possibile noleggiare un veicolo con autista a ore o per l'intera giornata?",
"Yes, a vehicle and driver can be booked at your disposal for touring, business itineraries or multi-stop day trips. Contact us for a custom quote.": "Sì, un veicolo con autista può essere a tua disposizione per visite, impegni di lavoro o escursioni con più tappe. Contattaci per un preventivo su misura.",
"How far in advance should I book?": "Con quanto anticipo devo prenotare?",
"Standard transfers can be booked instantly online, any time. For group, wedding or custom itineraries, contact us a few days ahead so we can arrange the right vehicles.": "I transfer standard si prenotano online subito, a qualsiasi ora. Per gruppi, matrimoni o itinerari su misura contattaci qualche giorno prima, così organizziamo i veicoli giusti.",
"Private Transfer Services": "Servizi di transfer privato",
"From a single airport pickup to multi-day itineraries, every service is built around a private vehicle, a fixed price and a professional driver.": "Da un singolo ritiro in aeroporto a itinerari di più giorni, ogni servizio prevede un veicolo privato, un prezzo fisso e un autista professionista.",
"Airport Arrivals": "Arrivi in aeroporto",
"Your driver tracks your flight and waits at arrivals with a name board, ready to help with luggage from the terminal to the car.": "L'autista monitora il tuo volo e ti aspetta agli arrivi con un cartello con il tuo nome, pronto ad aiutarti con i bagagli dal terminal all'auto.",
"Airport Departures": "Partenze dall'aeroporto",
"Scheduled pickup from your address timed to your flight, with a buffer built in for check-in and security.": "Ritiro al tuo indirizzo programmato in base al volo, con il margine necessario per check-in e controlli di sicurezza.",
"Point-to-Point Transfers": "Transfer diretti",
"Direct transfers between towns along the coast: Split to Makarska, Šibenik to Zadar, or any route in between.": "Transfer diretti tra località della costa: Spalato–Makarska, Šibenik–Zadar o qualsiasi percorso intermedio.",
"Return Transfers": "Andata e ritorno",
"Book both legs of your trip together, with your return pickup pre-scheduled. 5% discount on return transfers, no surprises.": "Prenota entrambe le tratte insieme, con il ritiro del ritorno già programmato. 5% di sconto su andata e ritorno, senza sorprese.",
"Group & Wedding Transfers": "Transfer per gruppi e matrimoni",
"The Renault Trafic and multiple V-Class vehicles can be combined for wedding parties, teams and larger groups travelling together.": "Il Renault Trafic e più veicoli Classe V possono essere combinati per matrimoni, squadre e gruppi numerosi che viaggiano insieme.",
"Hourly & Full-Day Hire": "Noleggio a ore o giornaliero",
"A vehicle and driver at your disposal for touring, business itineraries or multi-stop day trips, contact us for a custom quote.": "Un veicolo con autista a tua disposizione per visite, impegni di lavoro o escursioni con più tappe: contattaci per un preventivo su misura.",
"Who we drive": "Chi accompagniamo",
"Transfers made for how you travel": "Transfer pensati per il tuo modo di viaggiare",
"Families with kids": "Famiglie con bambini",
"Free child seats, room for pushchairs and no shared stops after a long flight.": "Seggiolini gratuiti, spazio per i passeggini e nessuna fermata condivisa dopo un lungo volo.",
"Groups and events": "Gruppi ed eventi",
"One van for up to 8 people and their bags, several vehicles for bigger groups.": "Un van per un massimo di 8 persone con i loro bagagli, più veicoli per i gruppi più grandi.",
"Cruise and ferry passengers": "Passeggeri di crociere e traghetti",
"From Split port to the airport or your hotel, with the meeting point agreed before the day.": "Dal porto di Spalato all'aeroporto o al tuo hotel, con il punto d'incontro concordato in anticipo.",
"Business travellers": "Viaggi di lavoro",
"Company invoice on request, a fixed price agreed in advance and flight tracking for every pickup.": "Fattura intestata all'azienda su richiesta, prezzo fisso concordato in anticipo e monitoraggio del volo per ogni ritiro.",
"No hidden costs": "Nessun costo nascosto",
"Door to Door Service": "Servizio porta a porta",
"We take you to your address": "Ti portiamo al tuo indirizzo",
"Local & Reliable": "Locali e affidabili",
"Based in Split": "Con base a Spalato",
"Years of Experience": "Anni di esperienza",
"Local knowledge of every route": "Conosciamo ogni percorso",
"Safe & Insured": "Sicuri e assicurati",
"Your safety is our priority": "La tua sicurezza è la nostra priorità",
"Ready to Book?": "Pronto a prenotare?",

# about
"About Us | Airport Split Transfer": "Chi siamo | Airport Split Transfer",
"Airport Split Transfer operates private, fixed-price airport transfers between Split Airport and destinations across the Dalmatian coast.": "Airport Split Transfer effettua transfer privati a prezzo fisso tra l'aeroporto di Spalato e le destinazioni della costa dalmata.",
"Who operates Airport Split Transfer?": "Chi gestisce Airport Split Transfer?",
"Airport Split Transfer is operated by De Niro, obrt za prijevoz, a licensed private transport business based in Kaštela, next to Split Airport.": "Airport Split Transfer è gestito da De Niro, obrt za prijevoz, un'impresa di trasporto privato autorizzata con sede a Kaštela, vicino all'aeroporto di Spalato.",
"Are your drivers licensed and insured?": "I vostri autisti sono autorizzati e assicurati?",
"Yes. Every driver is a licensed professional, and all vehicles are fully insured.": "Sì. Ogni autista è un professionista autorizzato e tutti i veicoli sono completamente assicurati.",
"Is this a shared shuttle or a private vehicle?": "È una navetta condivisa o un veicolo privato?",
"Every transfer is a single private vehicle booked for your party only, never a shared shuttle with other passengers.": "Ogni transfer è un veicolo privato riservato solo a te e al tuo gruppo, mai una navetta condivisa con altri passeggeri.",
"What languages do your drivers speak?": "Che lingue parlano i vostri autisti?",
"All drivers speak English, in addition to Croatian.": "Tutti gli autisti parlano inglese, oltre al croato.",
"Do you only operate airport transfers?": "Fate solo transfer aeroportuali?",
"No. Alongside Split Airport transfers, we also run point-to-point transfers between towns, private day trips, and hourly or full-day vehicle hire, see our Services page for details.": "No. Oltre ai transfer dall'aeroporto di Spalato effettuiamo transfer diretti tra località, escursioni private di un giorno e noleggio con autista a ore o per l'intera giornata: trovi i dettagli nella pagina Servizi.",
"Which areas do you cover?": "Quali zone coprite?",
"We cover the Dalmatian coast from Split itself all the way to Dubrovnik, including Trogir, Omiš, Makarska, Šibenik, Zadar and Plitvice Lakes National Park.": "Copriamo la costa dalmata da Spalato fino a Dubrovnik, comprese Trogir, Omiš, Makarska, Šibenik, Zadar e il Parco nazionale dei Laghi di Plitvice.",
"A Private Transfer, Done Properly": "Un transfer privato fatto come si deve",
"Airport Split Transfer was built around a simple idea: the first and last hour of a trip should feel as good as the rest of it.": "Airport Split Transfer nasce da un'idea semplice: la prima e l'ultima ora di un viaggio devono essere piacevoli quanto il resto.",
"We operate private, fixed-price transfers between Split Airport and destinations across the Dalmatian coast: from the old town of Split itself to Dubrovnik, three and a half hours south. Every transfer is a single private vehicle for your party, not a shared shuttle.": "Effettuiamo transfer privati a prezzo fisso tra l'aeroporto di Spalato e le destinazioni della costa dalmata: dal centro storico di Spalato fino a Dubrovnik, tre ore e mezza più a sud. Ogni transfer è un veicolo privato solo per il tuo gruppo, non una navetta condivisa.",
"Our drivers are licensed professionals who know the coast road, the ferry timetables and the fastest way around Split's old town traffic. Every flight is tracked in real time, so a delay on your end never means a missed pickup on ours.": "I nostri autisti sono professionisti autorizzati che conoscono la strada costiera, gli orari dei traghetti e il modo più rapido per evitare il traffico del centro di Spalato. Ogni volo viene monitorato in tempo reale, quindi un tuo ritardo non significa mai un ritiro mancato.",
"The fleet is maintained to a consistent standard across all three vehicle classes, the Škoda Superb, the Mercedes-Benz V-Class and the Renault Trafic, so the level of care is the same whether you are travelling alone or with a group of eight.": "Tutti e tre i veicoli, la Škoda Superb, la Mercedes-Benz Classe V e il Renault Trafic, sono mantenuti con lo stesso standard, quindi la cura è la stessa sia che tu viaggi da solo sia in un gruppo di otto.",
"Availability": "Disponibilità",
"Fixed": "Fisso",
"Upfront Pricing": "Prezzo in anticipo",
"Dalmatian Destinations": "Destinazioni in Dalmazia",
"No. Alongside Split Airport transfers, we also run point-to-point transfers between towns, private day trips, and hourly or full-day vehicle hire, see our": "No. Oltre ai transfer dall'aeroporto di Spalato effettuiamo transfer diretti tra località, escursioni private di un giorno e noleggio con autista a ore o per l'intera giornata: trovi i dettagli nella pagina",
"page for details.": ".",

# contact
"Contact Us | Airport Split Transfer": "Contatti | Airport Split Transfer",
"Contact Airport Split Transfer for airport transfers, group bookings and custom itineraries across Split and the Dalmatian coast.": "Contatta Airport Split Transfer per transfer aeroportuali, prenotazioni di gruppo e itinerari su misura a Spalato e lungo la costa dalmata.",
"How quickly will I get a reply?": "Quanto velocemente rispondete?",
"We reply within a few minutes during the day, and within the hour overnight.": "Di giorno rispondiamo in pochi minuti, di notte entro un'ora.",
"What's the fastest way to reach you?": "Qual è il modo più rapido per contattarvi?",
"WhatsApp usually gets the quickest response. You can also call, email, or use the form on this page.": "Di solito la risposta più rapida arriva su WhatsApp. Puoi anche chiamare, scrivere un'e-mail o usare il modulo in questa pagina.",
"Can I request a custom quote or itinerary through this form?": "Posso chiedere un preventivo o un itinerario su misura con questo modulo?",
"Yes, group bookings, wedding transfers and custom multi-stop itineraries can all be arranged this way. For a standard one-way or return transfer, the instant booking form on the homepage is faster.": "Sì, in questo modo si organizzano prenotazioni di gruppo, transfer per matrimoni e itinerari con più tappe. Per un normale transfer di sola andata o andata e ritorno è più rapido il modulo di prenotazione della home page.",
"Do you have a walk-in office I can visit?": "Avete un ufficio aperto al pubblico?",
"We're based in Split and Kaštela and handle bookings directly by phone, WhatsApp and email rather than a walk-in office, this keeps us available 24/7 wherever you are.": "Siamo a Spalato e Kaštela e gestiamo le prenotazioni direttamente per telefono, WhatsApp ed e-mail, senza un ufficio aperto al pubblico: così siamo disponibili 24/7 ovunque tu sia.",
"What should I include in my message?": "Cosa devo scrivere nel messaggio?",
"Your route, travel dates, passenger count and flight number (if relevant) help us reply with an accurate answer straight away.": "Percorso, date del viaggio, numero di passeggeri e numero di volo (se serve) ci aiutano a darti subito una risposta precisa.",
"Get in Touch": "Contattaci",
"Questions about a route, a group booking or a custom itinerary? Reach us directly, any time.": "Domande su un percorso, una prenotazione di gruppo o un itinerario su misura? Contattaci direttamente, a qualsiasi ora.",
"Send a Message": "Invia un messaggio",
"Subject": "Oggetto",
"Message": "Messaggio",
"By sending this message, you agree to our": "Inviando questo messaggio accetti la nostra",
"Send Message": "Invia messaggio",
"Message Sent": "Messaggio inviato",
"Thank you. We've received your message and will reply shortly.": "Grazie. Abbiamo ricevuto il tuo messaggio e ti risponderemo a breve.",
"Direct Contact": "Contatto diretto",
"Base": "Sede",
"Google Rating": "Valutazione Google",
"★ 5.0 (35+ reviews)": "★ 5.0 (35+ recensioni)",
}
