T = {
# privacy
"Privacy Policy | Airport Split Transfer": "Informativa sulla privacy | Airport Split Transfer",
"How Airport Split Transfer / Taxi De Niro Split collects, uses and protects your personal data under the GDPR when you book a private transfer in Croatia.": "Come Airport Split Transfer / Taxi De Niro Split raccoglie, usa e protegge i tuoi dati personali secondo il GDPR quando prenoti un transfer privato in Croazia.",
"Legal": "Note legali",
"Last updated: 4 October 2026": "Ultimo aggiornamento: 4 ottobre 2026",
"This policy explains how we handle your personal data when you visit airportsplittransfer.com, request a transfer or day trip, or contact us. We process personal data in line with the EU General Data Protection Regulation (GDPR) and the Croatian Act on the Implementation of the GDPR.": "Questa informativa spiega come trattiamo i tuoi dati personali quando visiti airportsplittransfer.com, richiedi un transfer o un'escursione o ci contatti. Trattiamo i dati personali in conformità al Regolamento generale sulla protezione dei dati dell'UE (GDPR) e alla legge croata di attuazione del GDPR.",
"1. Who is responsible for your data": "1. Chi è responsabile dei tuoi dati",
"The data controller is:": "Il titolare del trattamento è:",
"Airport Split Transfer / Taxi De Niro Split": "Airport Split Transfer / Taxi De Niro Split",
"Put Vele Meje 12, 21212 Kaštel Sućurac, Croatia": "Put Vele Meje 12, 21212 Kaštel Sućurac, Croazia",
"OIB: 76407755281": "OIB (codice fiscale croato): 76407755281",
"Email:": "E-mail:",
"Phone / WhatsApp:": "Telefono / WhatsApp:",
"For any question about your data or to exercise your rights, write to us at the email address above.": "Per qualsiasi domanda sui tuoi dati o per esercitare i tuoi diritti, scrivici all'indirizzo e-mail indicato sopra.",
"2. What data we collect": "2. Quali dati raccogliamo",
"When you request a transfer or day trip": "Quando richiedi un transfer o un'escursione",
", we collect the details you enter in the booking form:": ", raccogliamo i dati che inserisci nel modulo di prenotazione:",
"full name, email address and phone number;": "nome e cognome, indirizzo e-mail e numero di telefono;",
"pickup and drop-off address (including map coordinates when you pick an address suggestion), date and time;": "indirizzo di partenza e di arrivo (comprese le coordinate sulla mappa quando scegli un indirizzo suggerito), data e ora;",
"return date and time, flight number, number of passengers and suitcases, chosen vehicle and quoted price;": "data e ora del ritorno, numero di volo, numero di passeggeri e valigie, veicolo scelto e prezzo indicato;",
"any notes you add, for example child seats or special requests;": "eventuali note che aggiungi, per esempio seggiolini o richieste particolari;",
"the website language you booked in.": "la lingua del sito in cui hai prenotato.",
"When you contact us": "Quando ci contatti",
"by email, phone or WhatsApp, we receive your contact details and the content of your message.": "via e-mail, telefono o WhatsApp, riceviamo i tuoi dati di contatto e il contenuto del messaggio.",
"When you browse the website": "Quando navighi sul sito",
", our hosting provider automatically records technical data such as IP address, browser type and time of access, which is needed to deliver the site securely. Analytics data is collected only if you consent to it (see section 7).": ", il nostro fornitore di hosting registra automaticamente dati tecnici come indirizzo IP, tipo di browser e ora di accesso, necessari per fornire il sito in modo sicuro. I dati statistici vengono raccolti solo con il tuo consenso (vedi punto 7).",
"We do not ask for special categories of data. Please do not include health or other sensitive information in the notes field unless it is needed for your transfer (for example, a wheelchair).": "Non chiediamo categorie particolari di dati. Ti preghiamo di non inserire nel campo note informazioni sulla salute o altri dati sensibili, salvo se necessari per il transfer (per esempio, una sedia a rotelle).",
"3. Why we use your data and on what legal basis": "3. Perché usiamo i tuoi dati e su quale base giuridica",
"To arrange and carry out your transfer": "Per organizzare ed effettuare il transfer",
"confirming the booking, planning the pickup, tracking your flight, contacting you on the day and sending the confirmation email. Legal basis: performance of a contract and steps before entering into it (Art. 6(1)(b) GDPR).": "conferma della prenotazione, pianificazione del ritiro, monitoraggio del volo, contatto il giorno del viaggio e invio dell'e-mail di conferma. Base giuridica: esecuzione di un contratto e misure precontrattuali (art. 6, par. 1, lett. b, GDPR).",
"To answer your questions": "Per rispondere alle tue domande",
"sent by email, phone or WhatsApp. Legal basis: Art. 6(1)(b) GDPR, or our legitimate interest in replying to enquiries (Art. 6(1)(f) GDPR).": "inviate via e-mail, telefono o WhatsApp. Base giuridica: art. 6, par. 1, lett. b, GDPR, oppure il nostro legittimo interesse a rispondere alle richieste (art. 6, par. 1, lett. f, GDPR).",
"To keep accounting and tax records": "Per la tenuta delle scritture contabili e fiscali",
"of completed services. Legal basis: legal obligation (Art. 6(1)(c) GDPR).": "relative ai servizi effettuati. Base giuridica: obbligo di legge (art. 6, par. 1, lett. c, GDPR).",
"To keep the website secure and working": "Per mantenere il sito sicuro e funzionante",
", and to prevent misuse of the booking form. Legal basis: legitimate interest (Art. 6(1)(f) GDPR).": " e per prevenire abusi del modulo di prenotazione. Base giuridica: legittimo interesse (art. 6, par. 1, lett. f, GDPR).",
"To understand how the website is used": "Per capire come viene usato il sito",
"through Google Analytics. Legal basis: your consent (Art. 6(1)(a) GDPR), which you can withdraw at any time.": "tramite Google Analytics. Base giuridica: il tuo consenso (art. 6, par. 1, lett. a, GDPR), che puoi revocare in qualsiasi momento.",
"We do not use your data for automated decision-making or profiling, and we do not sell it.": "Non usiamo i tuoi dati per processi decisionali automatizzati o profilazione e non li vendiamo.",
"4. Who receives your data": "4. Chi riceve i tuoi dati",
"Your data is seen only by the people who need it to deliver your transfer. Our team and the driver assigned to your booking. We also use these service providers, who process data on our behalf under data processing agreements:": "I tuoi dati sono visibili solo a chi ne ha bisogno per effettuare il transfer: il nostro team e l'autista assegnato alla prenotazione. Ci avvaliamo inoltre di questi fornitori, che trattano i dati per nostro conto in base ad accordi sul trattamento dei dati:",
"Netlify, Inc.": "Netlify, Inc.",
"website hosting and receipt of booking form submissions;": "hosting del sito e ricezione dei moduli di prenotazione inviati;",
"Resend": "Resend",
"delivery of booking confirmation emails;": "invio delle e-mail di conferma della prenotazione;",
"Google Maps address suggestions and distance calculation when you type an address in the booking form and Google Analytics (only with your consent);": "suggerimenti di indirizzi e calcolo della distanza tramite Google Maps quando scrivi un indirizzo nel modulo di prenotazione, e Google Analytics (solo con il tuo consenso);",
"WhatsApp (Meta)": "WhatsApp (Meta)",
"only if you choose to contact us on WhatsApp.": "solo se scegli di contattarci su WhatsApp.",
"We may disclose data to public authorities where the law requires it.": "Possiamo comunicare i dati alle autorità pubbliche quando la legge lo richiede.",
"5. Transfers outside the EU": "5. Trasferimenti fuori dall'UE",
"Some of the providers above are based in the United States. Where data leaves the European Economic Area, it is protected by the EU–U.S. Data Privacy Framework or by the European Commission's Standard Contractual Clauses.": "Alcuni dei fornitori indicati hanno sede negli Stati Uniti. Quando i dati escono dallo Spazio economico europeo, sono protetti dal Data Privacy Framework UE-USA o dalle clausole contrattuali tipo della Commissione europea.",
"6. How long we keep your data": "6. Per quanto tempo conserviamo i dati",
"Booking data is kept for as long as needed to carry out the transfer and handle any follow-up questions or complaints, and for no longer than 24 months after the transfer date.": "I dati della prenotazione sono conservati per il tempo necessario a effettuare il transfer e a gestire eventuali domande o reclami successivi, e comunque non oltre 24 mesi dalla data del transfer.",
"Where a booking is part of our accounting records, those records are kept for the period required by Croatian accounting and tax law.": "Se una prenotazione fa parte delle nostre scritture contabili, queste sono conservate per il periodo previsto dalla normativa contabile e fiscale croata.",
"Messages sent to us are kept for as long as needed to deal with your enquiry.": "I messaggi che ci invii sono conservati per il tempo necessario a gestire la tua richiesta.",
"Analytics data is kept for no longer than 14 months.": "I dati statistici sono conservati per non più di 14 mesi.",
"7. Cookies": "7. Cookie",
"We use a small number of cookies:": "Usiamo un numero ridotto di cookie:",
"region": "region",
"a necessary cookie that records only whether you are visiting from the EU/EEA/UK, so we know whether to show the cookie banner (kept for 30 days);": "cookie necessario che registra solo se visiti il sito dall'UE/SEE/Regno Unito, per sapere se mostrare il banner dei cookie (conservato 30 giorni);",
"klaro-consent": "klaro-consent",
"a necessary cookie that remembers your cookie choice (kept for 12 months);": "cookie necessario che ricorda la tua scelta sui cookie (conservato 12 mesi);",
"_ga, _ga_*": "_ga, _ga_*",
"Google Analytics cookies, set only if you accept analytics.": "cookie di Google Analytics, impostati solo se accetti le statistiche.",
"You can change your choice at any time with the “Cookie Preferences” link at the bottom of every page.": "Puoi modificare la tua scelta in qualsiasi momento con il link “Preferenze cookie” in fondo a ogni pagina.",
"8. Your rights": "8. I tuoi diritti",
"Under the GDPR you have the right to:": "In base al GDPR hai il diritto di:",
"access the personal data we hold about you and receive a copy;": "accedere ai dati personali che conserviamo su di te e riceverne una copia;",
"have inaccurate data corrected;": "ottenere la rettifica dei dati inesatti;",
"have your data erased where there is no legal reason for us to keep it;": "ottenere la cancellazione dei dati quando non abbiamo un motivo legale per conservarli;",
"restrict or object to processing based on our legitimate interest;": "limitare il trattamento basato sul nostro legittimo interesse od opporti a esso;",
"receive your data in a portable format;": "ricevere i tuoi dati in un formato portabile;",
"withdraw your consent at any time, without affecting processing carried out before the withdrawal.": "revocare il consenso in qualsiasi momento, senza pregiudicare il trattamento effettuato prima della revoca.",
"To use any of these rights, email": "Per esercitare uno qualsiasi di questi diritti, scrivi a",
". We reply within one month.": ". Rispondiamo entro un mese.",
"You also have the right to lodge a complaint with the Croatian supervisory authority: Agencija za zaštitu osobnih podataka (AZOP), Selska cesta 136, 10000 Zagreb,": "Hai anche il diritto di presentare reclamo all'autorità di controllo croata: Agencija za zaštitu osobnih podataka (AZOP), Selska cesta 136, 10000 Zagabria,",
"azop.hr": "azop.hr",
"9. Security": "9. Sicurezza",
"The website is served only over encrypted HTTPS connections, and access to booking data is limited to the people who need it to deliver your transfer.": "Il sito è servito solo tramite connessioni HTTPS cifrate e l'accesso ai dati delle prenotazioni è limitato a chi ne ha bisogno per effettuare il transfer.",
"10. Changes to this policy": "10. Modifiche all'informativa",
"We may update this policy when our services or the law change. The date at the top of the page shows when it was last updated.": "Possiamo aggiornare questa informativa quando cambiano i nostri servizi o la legge. La data in cima alla pagina indica l'ultimo aggiornamento.",

# terms
"Terms & Conditions | Airport Split Transfer": "Termini e condizioni | Airport Split Transfer",
"Booking, cancellation, refund, waiting time and liability terms for private transfers and day trips with Airport Split Transfer / Taxi De Niro Split in Croatia.": "Condizioni di prenotazione, cancellazione, rimborso, attesa e responsabilità per transfer privati ed escursioni con Airport Split Transfer / Taxi De Niro Split in Croazia.",
"Last updated: 5 October 2026": "Ultimo aggiornamento: 5 ottobre 2026",
"These terms apply to every private transfer and day trip booked through airportsplittransfer.com, by email, by phone or on WhatsApp. By sending a booking request you accept these terms.": "Questi termini si applicano a ogni transfer privato ed escursione prenotati tramite airportsplittransfer.com, via e-mail, per telefono o su WhatsApp. Inviando una richiesta di prenotazione accetti questi termini.",
"1. About us": "1. Chi siamo",
"We provide private passenger transport with a driver in Croatia: airport transfers, point-to-point transfers and private day trips.": "Offriamo trasporto privato di passeggeri con autista in Croazia: transfer aeroportuali, transfer diretti tra località ed escursioni private di un giorno.",
"2. Booking and confirmation": "2. Prenotazione e conferma",
"Submitting the booking form sends us a booking request. The booking is confirmed once we send you a confirmation by email with your pickup details.": "Inviando il modulo di prenotazione ci mandi una richiesta di prenotazione. La prenotazione è confermata quando ti inviamo una conferma via e-mail con i dettagli del ritiro.",
"Please check that your name, phone number, email, addresses, date, time and flight number are correct. We plan the transfer on the details you give us.": "Controlla che nome, numero di telefono, e-mail, indirizzi, data, ora e numero di volo siano corretti. Organizziamo il transfer in base ai dati che ci fornisci.",
"For airport pickups, please add your flight number so we can follow your actual landing time.": "Per i ritiri in aeroporto indica il numero di volo, così possiamo seguire l'orario effettivo di atterraggio.",
"No account and no deposit are needed to book.": "Per prenotare non servono account né acconti.",
"3. Prices and payment": "3. Prezzi e pagamento",
"Prices are fixed per vehicle, not per person, and are shown before you book. They include the driver, fuel, road tolls, meet and greet at arrivals, and child seats on request.": "I prezzi sono fissi per veicolo, non a persona, e vengono mostrati prima della prenotazione. Includono autista, carburante, pedaggi, accoglienza agli arrivi e seggiolini su richiesta.",
"A return transfer booked together with the outbound transfer includes an automatic 5% discount on the total price.": "Un transfer di ritorno prenotato insieme a quello di andata include automaticamente uno sconto del 5% sul prezzo totale.",
"Extra stops, route changes requested on the day, or waiting beyond what is included may be charged extra. We will always tell you the amount first.": "Fermate aggiuntive, cambi di percorso richiesti il giorno stesso o attese oltre quanto incluso possono essere addebitati a parte. Ti comunicheremo sempre prima l'importo.",
"Day trips have a fixed price for the whole day. National park entrance tickets, boat trips, food and drinks are not included.": "Le escursioni hanno un prezzo fisso per l'intera giornata. Biglietti d'ingresso ai parchi nazionali, gite in barca, cibo e bevande non sono inclusi.",
"Unless a different payment method has been agreed in advance, payment is made to the driver on the day of the transfer.": "Salvo un diverso metodo di pagamento concordato in anticipo, il pagamento si effettua all'autista il giorno del transfer.",
"4. Waiting time and flight delays": "4. Tempo di attesa e ritardi dei voli",
"Airport pickups:": "Ritiri in aeroporto:",
"we track your flight and adjust the pickup to your actual landing time. Flight delays are not charged extra when your flight number was provided. Your driver waits for you in the arrivals hall, and the first 60 minutes after your actual landing time are free of charge.": "monitoriamo il tuo volo e adeguiamo il ritiro all'orario effettivo di atterraggio. I ritardi del volo non comportano costi aggiuntivi se hai indicato il numero di volo. L'autista ti aspetta nella sala arrivi e i primi 60 minuti dopo l'atterraggio effettivo sono gratuiti.",
"Pickups from an address": "Ritiri a un indirizzo",
"(hotel, apartment, port): the driver waits up to 15 minutes after the booked time free of charge.": "(hotel, appartamento, porto): l'autista attende gratuitamente fino a 15 minuti dopo l'orario prenotato.",
"If your flight is cancelled or rebooked, let us know as soon as possible and we will move your transfer to the new time where possible, at no extra cost.": "Se il tuo volo viene cancellato o riprogrammato, avvisaci il prima possibile e, quando possibile, sposteremo il transfer al nuovo orario senza costi aggiuntivi.",
"5. Changes and cancellations by you": "5. Modifiche e cancellazioni da parte tua",
"Cancellation is always free of charge. You can cancel your booking at any time before pickup by email, phone or WhatsApp, with no cancellation fee.": "La cancellazione è sempre gratuita. Puoi cancellare la prenotazione in qualsiasi momento prima del ritiro via e-mail, telefono o WhatsApp, senza alcuna penale.",
"Changes to the date, time, addresses or vehicle are also free of charge, subject to availability. Please let us know as early as possible, especially on the day of travel.": "Anche le modifiche a data, ora, indirizzi o veicolo sono gratuite, secondo disponibilità. Avvisaci il prima possibile, soprattutto il giorno del viaggio.",
"No-show:": "Mancata presentazione:",
"if you do not arrive at the pickup point and cannot be reached by phone or WhatsApp after the waiting time, the driver may leave and the booking is closed. If your plans change, please cancel instead so the driver is not sent out.": "se non ti presenti al punto di ritiro e non sei raggiungibile per telefono o su WhatsApp dopo il tempo di attesa, l'autista può andare via e la prenotazione viene chiusa. Se i tuoi piani cambiano, cancella la prenotazione così l'autista non parte inutilmente.",
"6. Changes and cancellations by us": "6. Modifiche e cancellazioni da parte nostra",
"If we cannot carry out a confirmed transfer, for example because of a vehicle breakdown, we will arrange an equivalent vehicle at no extra cost. If that is not possible, we will cancel the booking and refund in full anything you have paid in advance.": "Se non possiamo effettuare un transfer confermato, per esempio per un guasto al veicolo, organizzeremo un veicolo equivalente senza costi aggiuntivi. Se non è possibile, cancelleremo la prenotazione e rimborseremo per intero quanto hai pagato in anticipo.",
"7. Refunds": "7. Rimborsi",
"If you paid in advance, you receive a full refund whenever you cancel, and also if we cancel the booking.": "Se hai pagato in anticipo, ricevi il rimborso completo ogni volta che cancelli, e anche se siamo noi a cancellare la prenotazione.",
"Refunds are made to the original payment method within 14 days.": "I rimborsi vengono effettuati con il metodo di pagamento originale entro 14 giorni.",
"8. Passengers, luggage and children": "8. Passeggeri, bagagli e bambini",
"Please book the correct number of passengers and suitcases. Vehicle capacity: Škoda Superb 1–4 passengers, Mercedes-Benz V-Class 1–7 passengers, Renault Trafic 1–8 passengers.": "Prenota il numero corretto di passeggeri e valigie. Capienza dei veicoli: Škoda Superb 1–4 passeggeri, Mercedes-Benz Classe V 1–7 passeggeri, Renault Trafic 1–8 passeggeri.",
"Let us know in advance about oversized items such as bicycles, surfboards, golf bags or wheelchairs. If the luggage does not fit the booked vehicle, a larger vehicle may be needed at the matching price.": "Avvisaci in anticipo di oggetti ingombranti come biciclette, tavole da surf, sacche da golf o sedie a rotelle. Se i bagagli non entrano nel veicolo prenotato, potrebbe servire un veicolo più grande al prezzo corrispondente.",
"Child seats are free of charge and must be requested when booking. Children must travel in a suitable child seat as required by Croatian law.": "I seggiolini sono gratuiti e vanno richiesti al momento della prenotazione. I bambini devono viaggiare su un seggiolino adeguato, come previsto dalla legge croata.",
"Seat belts must be worn. Smoking, including e-cigarettes, is not allowed in our vehicles.": "Le cinture di sicurezza sono obbligatorie. Nei nostri veicoli è vietato fumare, anche sigarette elettroniche.",
"The driver may refuse to carry passengers whose behaviour puts the safety of the journey at risk. Cleaning costs for serious soiling of the vehicle may be charged.": "L'autista può rifiutare il trasporto di passeggeri il cui comportamento mette a rischio la sicurezza del viaggio. Possono essere addebitati i costi di pulizia in caso di sporco grave del veicolo.",
"9. Day trips": "9. Escursioni",
"Day trips are private round trips: your driver takes you to the destination, waits, and brings you back the same day.": "Le escursioni sono viaggi privati di andata e ritorno: l'autista ti porta a destinazione, ti aspetta e ti riporta indietro in giornata.",
"The suggested itinerary is flexible and agreed with your driver. Park opening times, closures and ticket rules are set by the national parks, not by us.": "L'itinerario proposto è flessibile e si concorda con l'autista. Orari di apertura, chiusure e regole sui biglietti sono stabiliti dai parchi nazionali, non da noi.",
"10. Liability": "10. Responsabilità",
"Our vehicles are licensed for passenger transport and insured as required by Croatian law.": "I nostri veicoli sono autorizzati al trasporto passeggeri e assicurati come previsto dalla legge croata.",
"We plan every transfer with enough time, but we are not responsible for delays caused by traffic, weather, road closures, border or police checks, accidents involving third parties, or other events outside our control.": "Pianifichiamo ogni transfer con il tempo necessario, ma non siamo responsabili per ritardi dovuti a traffico, maltempo, strade chiuse, controlli di frontiera o di polizia, incidenti causati da terzi o altri eventi fuori dal nostro controllo.",
"For departures, please choose a pickup time that leaves enough margin for your flight or ferry. We are not liable for a missed flight, ferry or connection caused by circumstances outside our control or by a pickup time chosen with too little margin.": "Per le partenze scegli un orario di ritiro con un margine sufficiente per il volo o il traghetto. Non rispondiamo di voli, traghetti o coincidenze persi per circostanze fuori dal nostro controllo o per un orario di ritiro scelto con troppo poco margine.",
"Where we are liable, our liability is limited to the price of the booked service, except for death or personal injury, or damage caused intentionally or through gross negligence, where the law does not allow liability to be limited.": "Quando siamo responsabili, la nostra responsabilità è limitata al prezzo del servizio prenotato, salvo i casi di morte o lesioni personali o di danni causati con dolo o colpa grave, per i quali la legge non consente di limitare la responsabilità.",
"Please take your belongings with you. We keep items found in our vehicles and will help you get them back, but we are not responsible for valuables left in the vehicle.": "Ricordati di portare con te i tuoi effetti personali. Conserviamo gli oggetti trovati nei veicoli e ti aiutiamo a recuperarli, ma non siamo responsabili per oggetti di valore lasciati nel veicolo.",
"11. Complaints and applicable law": "11. Reclami e legge applicabile",
"If something was not right, please tell us as soon as possible at": "Se qualcosa non è andato bene, faccelo sapere il prima possibile a",
". We reply to complaints within 15 days.": ". Rispondiamo ai reclami entro 15 giorni.",
"These terms are governed by Croatian law. This does not affect the rights you have as a consumer under the mandatory law of the country where you live.": "Questi termini sono regolati dalla legge croata. Ciò non pregiudica i diritti che hai come consumatore in base alle norme imperative del paese in cui vivi.",
"Passenger transport booked for a specific date is not covered by the 14-day right of withdrawal for distance contracts. Our free cancellation policy in section 5 applies instead.": "Il trasporto passeggeri prenotato per una data specifica non rientra nel diritto di recesso di 14 giorni previsto per i contratti a distanza. Si applica invece la nostra cancellazione gratuita descritta al punto 5.",
"12. Personal data": "12. Dati personali",
"How we use your personal data is explained in our": "Il modo in cui usiamo i tuoi dati personali è spiegato nella nostra",
}
