T = {
# services/ audience pages (phase 2)
"Business Transfers from Split Airport | Airport Split Transfer": "Transfer business dall'aeroporto di Spalato | Airport Split Transfer",
"Private business transfers from Split Airport: company invoice on request, flight tracking, Škoda Superb or Mercedes V-Class, fixed price agreed in advance.": "Transfer business privati dall'aeroporto di Spalato: fattura intestata all'azienda su richiesta, monitoraggio del volo, Škoda Superb o Mercedes Classe V, prezzo fisso concordato in anticipo.",
"Can I get an invoice for my company?": "Posso avere la fattura intestata alla mia azienda?",
"Yes. Give us the company name, address and tax number when you book, and we issue the invoice in the company's name after the ride. Croatian companies receive an R1 invoice.": "Sì. Indicaci ragione sociale, indirizzo e partita IVA quando prenoti: emettiamo la fattura intestata all'azienda dopo il viaggio. Le aziende croate ricevono la fattura R1.",
"Which car is best for a business trip?": "Qual è l'auto migliore per un viaggio di lavoro?",
"The Škoda Superb for up to 4 people. For a team or clients, the Mercedes V-Class seats up to 7 in a premium cabin.": "La Škoda Superb fino a 4 persone. Per un team o dei clienti, la Mercedes Classe V porta fino a 7 persone in un abitacolo premium.",
"Can the driver wait during a meeting and take us back?": "L'autista può aspettare durante una riunione e riportarci indietro?",
"Yes. A car and driver can be booked by the hour or for the full day. Contact us with your plan for a quote.": "Sì. Auto e autista si possono prenotare a ore o per l'intera giornata. Mandaci il tuo programma per un preventivo.",
"What if my flight is delayed?": "E se il mio volo è in ritardo?",
"We follow your flight number and adjust the pickup. The first 60 minutes after landing are free.": "Seguiamo il tuo volo e adeguiamo il ritiro. I primi 60 minuti dopo l'atterraggio sono gratuiti.",
"Can I pay by card?": "Posso pagare con la carta?",
"Yes, card and cash are both accepted, and the price is fixed when you book.": "Sì, accettiamo sia carta sia contanti, e il prezzo è fissato al momento della prenotazione.",
"Business transfers from Split Airport": "Transfer business dall'aeroporto di Spalato",
"Landing for a meeting, a conference or a site visit? Your driver is waiting in arrivals, the price is fixed in advance, and you get an invoice made out to your company.": "Atterri per una riunione, un congresso o un sopralluogo? L'autista ti aspetta agli arrivi, il prezzo è fissato in anticipo e ricevi una fattura intestata alla tua azienda.",
"Company invoice": "Fattura aziendale",
"on request": "su richiesta",
"Fixed price": "Prezzo fisso",
"agreed in advance": "concordato in anticipo",
"Live@@split-airport-business-transfers.html": "Monitoraggio",
"flight tracking": "del volo in tempo reale",
"Card or cash": "Carta o contanti",
"Made for work trips": "Pensato per i viaggi di lavoro",
"Add your company's name, address and tax number in the notes when you book, and after the ride we issue the invoice in the company's name. Croatian companies get a standard R1 invoice. You can pay by card or in cash, and the price does not change on the day.": "Quando prenoti, indica nelle note ragione sociale, indirizzo e partita IVA dell'azienda: dopo il viaggio emettiamo la fattura intestata all'azienda. Le aziende croate ricevono la normale fattura R1. Puoi pagare con carta o in contanti e il prezzo non cambia il giorno stesso.",
"The Škoda Superb is a quiet executive sedan for up to 4 people. For a team or a client group, the Mercedes V-Class seats up to 7 in a premium cabin, with room for luggage and equipment.": "La Škoda Superb è una berlina executive silenziosa per un massimo di 4 persone. Per un team o un gruppo di clienti, la Mercedes Classe V porta fino a 7 persone in un abitacolo premium, con spazio per bagagli e attrezzatura.",
"We follow your flight, and the first 60 minutes after landing are free, so a delay or a slow passport line costs you nothing. For a day of meetings in Split, Trogir or Šibenik, a car and driver can stay with you by the hour or for the whole day.": "Seguiamo il tuo volo e i primi 60 minuti dopo l'atterraggio sono gratuiti, quindi un ritardo o una coda lenta al controllo passaporti non ti costano nulla. Per una giornata di riunioni a Spalato, Trogir o Šibenik, auto e autista possono restare con te a ore o per l'intera giornata.",
"How it works": "Come funziona",
"Book": "Prenota",
"Tap the button and add your company details in the notes.": "Tocca il pulsante e aggiungi i dati dell'azienda nelle note.",
"We follow your flight": "Seguiamo il tuo volo",
"If you land early or late, your driver knows and adjusts.": "Se atterri in anticipo o in ritardo, l'autista lo sa e si adegua.",
"Met in arrivals": "Accoglienza agli arrivi",
"Your driver waits with a name board and helps with the bags.": "L'autista ti aspetta con un cartello con il tuo nome e ti aiuta con i bagagli.",
"Straight to your meeting": "Dritto alla riunione",
"No other passengers and no shared stops.": "Nessun altro passeggero e nessuna fermata condivisa.",
"See": "Scopri",
"all our services": "tutti i nostri servizi",
", including hourly and full-day hire, or our": ", compreso il noleggio con autista a ore o per l'intera giornata, oppure i nostri",
"hotel transfers": "transfer per hotel",
"Questions": "Domande",

"Split Airport Transfer with Kids | Airport Split Transfer": "Transfer dall'aeroporto di Spalato con bambini | Airport Split Transfer",
"Private transfer from Split Airport for families: free child seats on request, no shared stops, room for pushchairs, fixed price per vehicle.": "Transfer privato dall'aeroporto di Spalato per famiglie: seggiolini gratuiti su richiesta, nessuna fermata condivisa, spazio per i passeggini, prezzo fisso per veicolo.",
"Are child seats really free?": "I seggiolini sono davvero gratuiti?",
"Yes. Baby and child seats are free on request in all three vehicles. Tell us how many children are travelling and how old they are when you book.": "Sì. Ovetti e seggiolini sono gratuiti su richiesta in tutti e tre i veicoli. Quando prenoti, indicaci quanti bambini viaggiano e quanti anni hanno.",
"Which vehicle is best for a family?": "Qual è il veicolo migliore per una famiglia?",
"Up to 4 people with normal luggage fit in the Škoda Superb. With a pushchair, a travel cot or more than three suitcases, take the Mercedes V-Class (up to 7) or the Renault Trafic (up to 8).": "Nella Škoda Superb entrano fino a 4 persone con bagagli normali. Con un passeggino, un lettino da viaggio o più di tre valigie, scegli la Mercedes Classe V (fino a 7) o il Renault Trafic (fino a 8).",
"What if our flight is late?": "E se il nostro volo è in ritardo?",
"We follow your flight number, so the driver adjusts to the real landing time. The first 60 minutes after landing are free.": "Seguiamo il vostro volo, così l'autista si adegua all'orario reale di atterraggio. I primi 60 minuti dopo l'atterraggio sono gratuiti.",
"Do children pay extra?": "I bambini pagano un supplemento?",
"No. The price is per vehicle and fixed when you book, with tolls, fuel and meet and greet included.": "No. Il prezzo è per veicolo e fissato al momento della prenotazione, con pedaggi, carburante e accoglienza inclusi.",
"Can we book the ride back to the airport too?": "Possiamo prenotare anche il ritorno in aeroporto?",
"Yes. Choose \"Return\" in the form to book both legs together and get 5% off the total.": "Sì. Scegli \"Andata e ritorno\" nel modulo per prenotare entrambe le tratte insieme con il 5% di sconto sul totale.",
"Families with children": "Famiglie con bambini",
"Split Airport transfers for families with kids": "Transfer dall'aeroporto di Spalato per famiglie con bambini",
"After a flight with small children, the last thing you need is a taxi queue or a bus change. Your driver meets you in arrivals, the child seats are already fitted, and you go straight to your door.": "Dopo un volo con bambini piccoli, l'ultima cosa che serve è una coda per il taxi o un cambio di autobus. L'autista vi accoglie agli arrivi, i seggiolini sono già montati e andate dritti fino alla porta.",
"Free@@split-airport-transfer-with-kids.html": "Seggiolini",
"child seats on request": "gratuiti su richiesta",
"free waiting at the airport": "di attesa gratuita in aeroporto",
"per vehicle, not per person": "per veicolo, non a persona",
"Vans for families of up to": "Van per famiglie fino a",
"What we take care of": "Di cosa ci occupiamo noi",
"Child seats are free and fitted before you get in. When you book, add the number of children and their ages in the notes, so the driver brings the right seats. Croatian law requires a suitable seat for young children, and we always follow it.": "I seggiolini sono gratuiti e montati prima che saliate. Quando prenoti, indica nelle note il numero di bambini e la loro età, così l'autista porta i seggiolini giusti. La legge croata prevede un seggiolino adeguato per i bambini piccoli e noi la rispettiamo sempre.",
"Pushchairs, travel cots and your own car seats go in the boot with the suitcases. With a lot of luggage, choose the Mercedes V-Class or the Renault Trafic. The price is per vehicle, so the extra space does not mean paying per head.": "Passeggini, lettini da viaggio e i vostri seggiolini vanno nel bagagliaio con le valigie. Con molti bagagli, scegli la Mercedes Classe V o il Renault Trafic. Il prezzo è per veicolo, quindi lo spazio in più non significa pagare a persona.",
"Flights with children are often late, and passport control can be slow. We follow your flight, and the first 60 minutes after landing are free, so nobody has to rush.": "I voli con bambini sono spesso in ritardo e il controllo passaporti può essere lento. Seguiamo il vostro volo e i primi 60 minuti dopo l'atterraggio sono gratuiti, quindi nessuno deve correre.",
"“We were travelling with our little 9 month old and he really helped us and made sure all was ok.”": "“Viaggiavamo con la nostra bimba di 9 mesi, ci ha aiutato tanto e si è assicurato che fosse tutto a posto.”",
"Tap the button, enter your address and add the children's ages in the notes.": "Tocca il pulsante, inserisci l'indirizzo e aggiungi nelle note l'età dei bambini.",
"Your driver waits with a name board and helps with the bags and the pushchair.": "L'autista vi aspetta con un cartello con il vostro nome e vi aiuta con bagagli e passeggino.",
"Straight to your door": "Fino alla porta di casa",
"No other passengers. Child seats are ready in the car.": "Nessun altro passeggero. I seggiolini sono già in auto.",
"Planning a day out with the kids? See our": "Una gita con i bambini? Scopri le nostre",
"private day trips": "escursioni private di un giorno",
"to Krka and Plitvice, or": "a Krka e Plitvice, oppure",
"compare the vehicles": "confronta i veicoli",

"Group Transfers from Split Airport | Airport Split Transfer": "Transfer di gruppo dall'aeroporto di Spalato | Airport Split Transfer",
"Private group transfers from Split Airport: one van for up to 8 people and their bags, several vehicles for bigger groups, fixed price per vehicle.": "Transfer privati di gruppo dall'aeroporto di Spalato: un van per un massimo di 8 persone con i bagagli, più veicoli per i gruppi più grandi, prezzo fisso per veicolo.",
"How many people fit in one vehicle?": "Quante persone entrano in un veicolo?",
"Up to 8 in the Renault Trafic and up to 7 in the Mercedes V-Class, each with room for one suitcase per person. The Škoda Superb takes up to 4.": "Fino a 8 nel Renault Trafic e fino a 7 nella Mercedes Classe V, entrambi con spazio per una valigia a persona. La Škoda Superb porta fino a 4 persone.",
"We are more than 8. Can you take everyone?": "Siamo più di 8. Potete portarci tutti?",
"Yes, we combine several vehicles. Contact us a few days ahead so we can arrange them.": "Sì, combiniamo più veicoli. Contattaci qualche giorno prima così li organizziamo.",
"Is the price per person?": "Il prezzo è a persona?",
"No, per vehicle, with tolls, fuel and meet and greet included. Divide it by the number of people in the van to see each share.": "No, per veicolo, con pedaggi, carburante e accoglienza inclusi. Dividilo per il numero di persone nel van per vedere la quota di ciascuno.",
"Do you do weddings and events?": "Fate transfer per matrimoni ed eventi?",
"Yes, group and wedding transfers are part of what we do. Send us the date, the places and the number of guests and we will send you a quote.": "Sì, i transfer per gruppi e matrimoni fanno parte del nostro lavoro. Mandaci data, luoghi e numero di invitati e ti inviamo un preventivo.",
"Can we book the return at the same time?": "Possiamo prenotare subito anche il ritorno?",
"Group transfers from Split Airport": "Transfer di gruppo dall'aeroporto di Spalato",
"Travelling as six, eight or twenty? Instead of splitting into taxis and losing each other at arrivals, the whole group travels together with the luggage, at a fixed price per vehicle.": "Viaggiate in sei, in otto o in venti? Invece di dividervi in più taxi e perdervi agli arrivi, tutto il gruppo viaggia insieme con i bagagli, a un prezzo fisso per veicolo.",
"Up to": "Fino a",
"people per van": "persone per van",
"Room for": "Spazio per",
"suitcases": "valigie",
"Several vehicles": "Più veicoli",
"for bigger groups": "per i gruppi più grandi",
"per vehicle": "per veicolo",
"One van instead of two taxis": "Un van invece di due taxi",
"The Renault Trafic takes up to 8 passengers and 8 suitcases, and the Mercedes V-Class up to 7 with 7 suitcases. You pay for the vehicle, not per seat, so the fuller it is, the less each person pays. A group of eight going from the airport to Makarska pays about €23 each.": "Il Renault Trafic porta fino a 8 passeggeri e 8 valigie, la Mercedes Classe V fino a 7 con 7 valigie. Si paga il veicolo, non il posto, quindi più è pieno e meno paga ciascuno. Un gruppo di otto dall'aeroporto a Makarska paga circa 23 € a testa.",
"For bigger groups, such as a wedding party, a sports team or a company trip, we combine several vehicles so everyone arrives together. Contact us a few days ahead on WhatsApp or by email with the group size and flights, and we will arrange the right vehicles.": "Per gruppi più grandi, come un matrimonio, una squadra sportiva o un viaggio aziendale, combiniamo più veicoli così arrivate tutti insieme. Contattaci qualche giorno prima su WhatsApp o via e-mail con il numero di persone e i voli e organizzeremo i veicoli giusti.",
"Friends' weekends, birthdays and families travelling together all work the same way: one meeting point in arrivals, one driver per vehicle, and nobody left waiting for the next taxi.": "Weekend tra amici, compleanni e famiglie che viaggiano insieme funzionano allo stesso modo: un unico punto d'incontro agli arrivi, un autista per veicolo e nessuno che aspetta il taxi successivo.",
"Book or message us": "Prenota o scrivici",
"Up to 8 people: book online. More than that: send us the group size and flights.": "Fino a 8 persone: prenota online. Di più: mandaci il numero di persone e i voli.",
"We follow the flight": "Seguiamo il volo",
"Your driver waits with a name board and helps load the bags.": "L'autista vi aspetta con un cartello con il nome e aiuta a caricare i bagagli.",
"Straight to the address": "Dritti all'indirizzo",
"See the": "Scopri la",
"Mercedes V-Class and Renault Trafic": "Mercedes Classe V e il Renault Trafic",
", or read": ", oppure leggi",
"which van suits your group": "quale van è adatto al tuo gruppo",

"Split Cruise and Ferry Port Transfers | Airport Split Transfer": "Transfer dal porto crociere e traghetti di Spalato | Airport Split Transfer",
"Private transfer from Split cruise and ferry port to Split Airport or your hotel: about 25 to 30 minutes to the airport, fixed price per vehicle.": "Transfer privato dal porto crociere e traghetti di Spalato all'aeroporto o al tuo hotel: circa 25–30 minuti fino all'aeroporto, prezzo fisso per veicolo.",
"How long is the drive from Split port to the airport?": "Quanto dura il tragitto dal porto di Spalato all'aeroporto?",
"About 25 to 30 minutes for roughly 20 km. Allow more time on summer Saturdays.": "Circa 25–30 minuti per una ventina di chilometri. Il sabato d'estate calcola più tempo.",
"Where do we meet the driver at the port?": "Dove incontriamo l'autista al porto?",
"We agree the exact meeting point with you before the day, depending on where your ship or ferry comes in.": "Concordiamo con te il punto d'incontro esatto prima del giorno del viaggio, in base a dove attracca la tua nave o il tuo traghetto.",
"What if our ferry is late?": "E se il nostro traghetto è in ritardo?",
"Tell us which ferry or catamaran you are on. If it is running late, message us on WhatsApp and we adjust the pickup.": "Dicci su quale traghetto o catamarano viaggi. Se è in ritardo, scrivici su WhatsApp e adeguiamo il ritiro.",
"Can you take us from the airport to the port?": "Potete portarci dall'aeroporto al porto?",
"Yes. Use the port as your destination when you book and add your ferry or check-in time, so we can plan a safe arrival.": "Sì. Indica il porto come destinazione quando prenoti e aggiungi l'orario del traghetto o dell'imbarco, così pianifichiamo l'arrivo con il giusto margine.",
"No, per vehicle and fixed when you book, with tolls and fuel included.": "No, per veicolo e fissato al momento della prenotazione, con pedaggi e carburante inclusi.",
"Transfers from Split cruise and ferry port": "Transfer dal porto crociere e traghetti di Spalato",
"Coming off a cruise ship, or off the ferry from Hvar or Brač, with suitcases? We take you from the port in Split straight to the airport, your hotel or anywhere on the coast, at a fixed price.": "Scendi da una nave da crociera o dal traghetto da Hvar o Brač con le valigie? Ti portiamo dal porto di Spalato direttamente all'aeroporto, al tuo hotel o ovunque sulla costa, a prezzo fisso.",
"About@@split-port-transfers.html": "Circa",
"to the airport": "fino all'aeroporto",
"25 to 30 min": "25–30 min",
"Vans for up to": "Van fino a",
"From the port to the airport": "Dal porto all'aeroporto",
"Split's port sits right next to the old town. Ferries and catamarans from the islands come in here, and cruise ships berth or anchor along the harbour. The airport is about 20 km away, usually 25 to 30 minutes by car, and longer on summer Saturdays when the island traffic peaks.": "Il porto di Spalato si trova proprio accanto al centro storico. Qui arrivano traghetti e catamarani dalle isole, mentre le navi da crociera attraccano o si ancorano nel bacino portuale. L'aeroporto dista circa 20 km, di solito 25–30 minuti in auto, di più il sabato d'estate quando il traffico verso le isole è al massimo.",
"Ports are busy in summer, so we agree the exact meeting point with you before the day. Add your ship or ferry and the time you expect to be off in the notes when you book. If the ferry is running late, send us a message on WhatsApp and we adjust the pickup.": "D'estate il porto è molto affollato, quindi concordiamo il punto d'incontro esatto prima del giorno del viaggio. Quando prenoti, indica nelle note la nave o il traghetto e l'orario in cui prevedi di sbarcare. Se il traghetto è in ritardo, mandaci un messaggio su WhatsApp e adeguiamo il ritiro.",
"Going the other way? We also drive from Split Airport or your hotel to the port, timed to your ferry or cruise check-in.": "Devi fare il percorso inverso? Ti portiamo anche dall'aeroporto di Spalato o dal tuo hotel al porto, in tempo per il traghetto o l'imbarco sulla crociera.",
"Book a transfer to the port": "Prenota un transfer per il porto",
"Tap the button. The port is already filled in as your pickup.": "Tocca il pulsante. Il porto è già inserito come punto di partenza.",
"Tell us your ship or ferry": "Indicaci la nave o il traghetto",
"Add it to the notes, with the time you expect to be off.": "Aggiungilo nelle note, con l'orario in cui prevedi di sbarcare.",
"We agree the meeting point": "Concordiamo il punto d'incontro",
"Before the day, so you know exactly where to go.": "Prima del giorno del viaggio, così sai esattamente dove andare.",
"Straight to the airport": "Dritti all'aeroporto",
"Staying in Split first? See": "Ti fermi prima a Spalato? Scopri i",
"transfers to Split city": "transfer per il centro di Spalato",
"and our": "e i nostri",
}
