T = {
# day-trips.html
"Private Day Trips from Split: Plitvice, Krka | Airport Split Transfer": "Escursioni private da Spalato: Plitvice e Krka | Airport Split Transfer",
"Private day trips from Split with an English-speaking driver: Plitvice Lakes, Krka National Park and fully custom excursions.": "Escursioni private di un giorno da Spalato con autista che parla inglese: Laghi di Plitvice, Parco nazionale di Krka ed escursioni su misura.",
"Plitvice Lakes Day Trip": "Escursione ai Laghi di Plitvice",
"Krka National Park Day Trip": "Escursione al Parco nazionale di Krka",
"Are the day trips private or shared with other tourists?": "Le escursioni sono private o condivise con altri turisti?",
"Fully private. Every day trip is a single vehicle and driver for your group only, never a shared shuttle.": "Completamente private. Ogni escursione prevede un veicolo con autista solo per il tuo gruppo, mai una navetta condivisa.",
"What's included in the day trip price?": "Cosa è incluso nel prezzo dell'escursione?",
"A private vehicle, an English-speaking driver, and a fixed price for the whole day, the driver waits at the park for your return leg.": "Un veicolo privato, un autista che parla inglese e un prezzo fisso per l'intera giornata; l'autista ti aspetta al parco per il ritorno.",
"Are national park entrance tickets included?": "I biglietti d'ingresso al parco nazionale sono inclusi?",
"No. Entrance tickets and food are not included in the transfer price and are paid separately on the day. Fuel, tolls and parking at the park are included.": "No. Biglietti d'ingresso e pasti non sono inclusi nel prezzo del trasporto e si pagano a parte il giorno stesso. Carburante, pedaggi e parcheggio al parco sono inclusi.",
"How long do the Plitvice and Krka trips take?": "Quanto durano le escursioni a Plitvice e Krka?",
"Plitvice Lakes is a 10–12 hour round trip; Krka National Park, being closer to Split, is 8–10 hours.": "L'escursione ai Laghi di Plitvice dura 10–12 ore tra andata e ritorno; il Parco nazionale di Krka, più vicino a Spalato, 8–10 ore.",
"Can you organize a custom day trip somewhere else?": "Potete organizzare un'escursione su misura altrove?",
"Yes, we arrange fully private custom tours to Dubrovnik, Trogir, Omiš, Mostar and other destinations. Contact us with your itinerary.": "Sì, organizziamo tour privati su misura a Dubrovnik, Trogir, Omiš, Mostar e altre destinazioni. Mandaci il tuo itinerario.",
"Private Excursions from Split": "Escursioni private da Spalato",
"Private Day Trips from Split": "Escursioni private di un giorno da Spalato",
"Discover Croatia comfortably with private excursions, flexible pickup and an English-speaking driver.": "Scopri la Croazia in comodità con escursioni private, partenza flessibile e un autista che parla inglese.",
"Turquoise cascading lakes and waterfalls at Plitvice Lakes National Park": "Laghi turchesi a cascata e cascate nel Parco nazionale dei Laghi di Plitvice",
"Most Popular": "La più richiesta",
"Day trips": "Escursioni",
"10–12 hours": "10–12 ore",
"Croatia's oldest and largest national park, made famous by 16 terraced lakes connected by waterfalls and wooden walking trails through untouched forest.": "Il parco nazionale più antico e più grande della Croazia, famoso per i 16 laghi a terrazze collegati da cascate e passerelle di legno nella foresta intatta.",
"UNESCO World Heritage": "Patrimonio mondiale UNESCO",
"16 turquoise lakes": "16 laghi turchesi",
"Wooden walking trails": "Passerelle di legno",
"Private return transfer": "Transfer privato di andata e ritorno",
"Book This Trip": "Prenota l'escursione",
"Skradinski Buk waterfalls cascading into the river at Krka National Park": "Le cascate di Skradinski Buk nel Parco nazionale di Krka",
"Nature Escape": "Immersi nella natura",
"8–10 hours": "8–10 ore",
"Closer to Split than Plitvice, Krka's Skradinski Buk waterfalls and riverside walking trails make for a relaxed, flexible day surrounded by nature.": "Più vicina a Spalato rispetto a Plitvice, Krka con le cascate di Skradinski Buk e i sentieri lungo il fiume offre una giornata rilassata e flessibile nella natura.",
"Skradinski Buk waterfalls": "Cascate di Skradinski Buk",
"Beautiful nature": "Natura splendida",
"Optional boat ride": "Gita in barca facoltativa",
"Flexible itinerary": "Itinerario flessibile",
"Tailored For You": "Su misura per te",
"Custom Private Tours": "Tour privati su misura",
"Want to visit Dubrovnik, Trogir, Omiš, Mostar or another destination? We organise fully private day trips tailored to your itinerary. Contact us and we'll create a custom tour for you.": "Vuoi visitare Dubrovnik, Trogir, Omiš, Mostar o un'altra destinazione? Organizziamo escursioni private di un giorno su misura per il tuo itinerario. Contattaci e creeremo un tour per te.",
"Request a Custom Tour": "Richiedi un tour su misura",
"Custom Tour Request": "Richiesta tour su misura",

# krka
"Krka Day Trip from Split, Private Tour | Airport Split Transfer": "Escursione a Krka da Spalato, tour privato | Airport Split Transfer",
"Private day trip from Split to Krka National Park with an English-speaking driver. See Skradinski Buk waterfalls, fixed price, flexible 8-10 hour itinerary.": "Escursione privata da Spalato al Parco nazionale di Krka con autista che parla inglese. Cascate di Skradinski Buk, prezzo fisso, itinerario flessibile di 8–10 ore.",
"Krka National Park Day Trip from Split": "Escursione da Spalato al Parco nazionale di Krka",
"A private, flexible day excursion from Split to Krka National Park with an English-speaking driver, round-trip transfer and time to explore the Skradinski Buk waterfalls.": "Un'escursione privata e flessibile da Spalato al Parco nazionale di Krka con autista che parla inglese, trasporto di andata e ritorno e tempo per esplorare le cascate di Skradinski Buk.",
"Hotel Pickup in Split": "Ritiro in hotel a Spalato",
"Skradinski Buk waterfalls, riverside walking trails and optional boat trip to Visovac Island.": "Cascate di Skradinski Buk, sentieri lungo il fiume e gita in barca facoltativa all'isolotto di Visovac.",
"Return Transfer to Split": "Rientro a Spalato",
"How long does the Krka National Park day trip take?": "Quanto dura l'escursione al Parco nazionale di Krka?",
"The full round trip from Split takes approximately 8–10 hours, including 3–4 hours to explore the park. Krka is closer to Split than Plitvice Lakes, which makes for a slightly more relaxed day.": "L'intera escursione da Spalato dura circa 8–10 ore, di cui 3–4 ore per visitare il parco. Krka è più vicina a Spalato rispetto ai Laghi di Plitvice, quindi la giornata è un po' più rilassata.",
"What is included in the price?": "Cosa è incluso nel prezzo?",
"Your private vehicle, English-speaking driver, all fuel and tolls, and hotel/accommodation pickup and drop-off in Split are included. Krka National Park entrance tickets, and the optional Visovac Island boat trip, are purchased separately at the park.": "Sono inclusi il veicolo privato, l'autista che parla inglese, carburante e pedaggi, e il ritiro e il rientro presso il tuo hotel o alloggio a Spalato. I biglietti d'ingresso al Parco nazionale di Krka e la gita facoltativa in barca a Visovac si acquistano a parte al parco.",
"Can I swim at Krka National Park?": "Si può fare il bagno nel Parco nazionale di Krka?",
"Swimming at Skradinski Buk has not been permitted since 2021, as part of the park's conservation efforts. You can still get close to the falls on the wooden boardwalks, and swimming remains possible at some other points along the Krka river outside the protected area.": "Dal 2021 non è più consentito fare il bagno a Skradinski Buk, per tutelare il parco. Puoi comunque avvicinarti alle cascate sulle passerelle di legno, e in alcuni altri punti lungo il fiume Krka, fuori dall'area protetta, il bagno è ancora possibile.",
"Is Krka a good alternative to Plitvice Lakes?": "Krka è una buona alternativa ai Laghi di Plitvice?",
"Krka is closer to Split, generally quieter, and centres on one spectacular waterfall system rather than a chain of lakes, a good choice if you'd like a shorter day or have already visited Plitvice. Many guests who have time for both say the two parks feel genuinely different rather than repetitive.": "Krka è più vicina a Spalato, di solito più tranquilla e ruota attorno a un unico spettacolare sistema di cascate invece che a una catena di laghi: una buona scelta se preferisci una giornata più breve o hai già visitato Plitvice. Molti ospiti che hanno tempo per entrambi dicono che i due parchi sono davvero diversi, non ripetitivi.",
"Is the boat ride to Visovac Island included?": "La gita in barca all'isolotto di Visovac è inclusa?",
"The Visovac Island boat trip is optional and booked separately at the park, usually departing from Skradin. Let your driver know in advance if you'd like time built into your day for it.": "La gita in barca a Visovac è facoltativa e si prenota a parte al parco, di solito con partenza da Skradin. Avvisa l'autista in anticipo se vuoi prevedere del tempo per farla.",
"Skradinski Buk waterfalls cascading through Krka National Park": "Le cascate di Skradinski Buk nel Parco nazionale di Krka",
"Split → Krka National Park": "Spalato → Parco nazionale di Krka",
"Private Day Trip to Krka National Park": "Escursione privata al Parco nazionale di Krka",
"8–10 hrs": "8–10 ore",
"Round Trip Duration": "Durata andata e ritorno",
"~85 km": "~85 km",
"Each Way": "Per tratta",
"Private": "Privata",
"Just Your Group": "Solo il tuo gruppo",
"Closer Than Plitvice": "Più vicina di Plitvice",
"Overview": "In breve",
"Waterfalls, Without the Long Drive": "Cascate, senza il lungo viaggio",
"Krka National Park is built around the Krka River as it drops through a series of travertine cascades, the largest and most famous being Skradinski Buk, a wide curtain of waterfalls reached by wooden boardwalks that wind through the forest and along the water's edge. At under half the driving distance of Plitvice Lakes, Krka makes for a noticeably more relaxed day: less time in the car, more time actually at the park, and still home the same afternoon with energy left over. The riverside town of Skradin, where most visits begin, adds a pleasant stop in its own right, a small stone-built harbour town worth a slow coffee before or after the walk. For visitors short on time, or anyone who's already done the longer trip to Plitvice, Krka is consistently the easier, more flexible choice without giving up the “Croatian waterfalls” experience people come here for.": "Il Parco nazionale di Krka si sviluppa attorno al fiume Krka, che scende attraverso una serie di cascate di travertino: la più grande e famosa è Skradinski Buk, un ampio sipario d'acqua raggiungibile con passerelle di legno che attraversano il bosco e costeggiano l'acqua. Con meno della metà della strada necessaria per i Laghi di Plitvice, Krka offre una giornata decisamente più rilassata: meno tempo in auto, più tempo al parco e rientro nel pomeriggio con energie ancora da spendere. La cittadina di Skradin sul fiume, da cui parte la maggior parte delle visite, merita una sosta: un piccolo porto in pietra perfetto per un caffè con calma prima o dopo la passeggiata. Per chi ha poco tempo, o ha già fatto il viaggio più lungo a Plitvice, Krka è sempre la scelta più semplice e flessibile, senza rinunciare alle cascate croate che tutti vengono a vedere.",
"What's Included": "Cosa è incluso",
"Private vehicle for your group only, no shared shuttle": "Veicolo privato solo per il tuo gruppo, nessuna navetta condivisa",
"English-speaking driver for the full day": "Autista che parla inglese per tutta la giornata",
"Hotel or accommodation pickup and drop-off in Split": "Ritiro e rientro presso hotel o alloggio a Spalato",
"All fuel, tolls and parking at the park": "Carburante, pedaggi e parcheggio al parco",
"Flexible time inside the park. Your driver waits": "Tempo flessibile al parco. L'autista ti aspetta",
"Bottled water for the journey": "Acqua in bottiglia per il viaggio",
"Not included: Krka National Park entrance tickets and the optional Visovac Island boat trip, both purchased separately at the park.": "Non inclusi: i biglietti d'ingresso al Parco nazionale di Krka e la gita facoltativa in barca a Visovac, entrambi acquistabili a parte al parco.",
"Car": "Auto",
"Škoda Superb": "Škoda Superb",
"Pickup Address": "Indirizzo di ritiro",
"Hotel name or full address in Split": "Nome dell'hotel o indirizzo completo a Spalato",
"Child seats, special requests...": "Seggiolini, richieste particolari...",
"Book This Trip · €255": "Prenota l'escursione · 255 €",
"Booking confirmed!": "Richiesta ricevuta!",
"A confirmation has been sent to your email with the full trip details.": "Ti abbiamo inviato via e-mail una conferma con tutti i dettagli dell'escursione.",
"Ask a Question on WhatsApp": "Fai una domanda su WhatsApp",
"Fixed price for the day · driver waits at the park · flexible pickup time.": "Prezzo fisso per la giornata · l'autista aspetta al parco · orario di partenza flessibile.",
"Suggested Itinerary": "Itinerario consigliato",
"A Typical Day at Krka": "Una giornata tipo a Krka",
"Pickup in Split": "Partenza da Spalato",
"A later start than Plitvice is comfortable here, given the shorter drive. Your driver collects you from your hotel or apartment.": "Visto il tragitto più breve, qui si può partire più tardi che per Plitvice. L'autista ti viene a prendere in hotel o in appartamento.",
"Arrival Near Skradin": "Arrivo vicino a Skradin",
"Your driver drops you at the park entrance and confirms a return time. Entrance tickets are purchased at the gate.": "L'autista ti lascia all'ingresso del parco e concorda l'orario del ritorno. I biglietti si acquistano all'ingresso.",
"Skradinski Buk & Walking Trails": "Skradinski Buk e sentieri",
"Follow the boardwalks along and across the falls, with time for the optional boat trip to Visovac Island if you'd like to add it.": "Segui le passerelle lungo e sopra le cascate, con il tempo per la gita facoltativa in barca a Visovac se vuoi aggiungerla.",
"Lunch in Skradin": "Pranzo a Skradin",
"The riverside town makes a pleasant lunch stop before the drive back, several restaurants sit right on the harbour.": "La cittadina sul fiume è perfetta per pranzare prima del rientro: diversi ristoranti si affacciano direttamente sul porto.",
"Return Drive to Split": "Rientro a Spalato",
"Your driver is waiting at the agreed time for the shorter drive back to Split.": "L'autista ti aspetta all'orario concordato per il breve viaggio di ritorno a Spalato.",
"Drop-off in Split": "Arrivo a Spalato",
"Back at your accommodation by mid-to-late afternoon, plenty of the evening still ahead.": "Di nuovo al tuo alloggio nel pomeriggio, con tutta la serata ancora davanti.",
"This is a suggested schedule: departure time, lunch stop and time spent in the park are all flexible and arranged directly with your driver.": "Questo è un programma indicativo: orario di partenza, sosta per il pranzo e tempo al parco sono flessibili e si concordano direttamente con l'autista.",

# plitvice
"Plitvice Day Trip from Split, Private Tour | Airport Split Transfer": "Escursione a Plitvice da Spalato, tour privato | Airport Split Transfer",
"Private day trip from Split to Plitvice Lakes National Park with an English-speaking driver. Fixed price, flexible pickup, 10-12 hours round trip. Book online.": "Escursione privata da Spalato al Parco nazionale dei Laghi di Plitvice con autista che parla inglese. Prezzo fisso, partenza flessibile, 10–12 ore andata e ritorno. Prenota online.",
"Plitvice Lakes Day Trip from Split": "Escursione da Spalato ai Laghi di Plitvice",
"A private, full-day excursion from Split to Plitvice Lakes National Park with an English-speaking driver, round-trip transfer and flexible pickup time.": "Un'escursione privata di un'intera giornata da Spalato al Parco nazionale dei Laghi di Plitvice con autista che parla inglese, trasporto di andata e ritorno e orario di partenza flessibile.",
"16 terraced lakes connected by waterfalls and wooden walking trails.": "16 laghi a terrazze collegati da cascate e passerelle di legno.",
"How long does the Plitvice Lakes day trip take?": "Quanto dura l'escursione ai Laghi di Plitvice?",
"The full round trip from Split takes approximately 10–12 hours, including around 4–5 hours to explore the national park itself. Exact timing depends on your pickup location and how long you'd like to spend inside the park.": "L'intera escursione da Spalato dura circa 10–12 ore, di cui circa 4–5 ore per visitare il parco nazionale. La durata esatta dipende dal luogo di partenza e da quanto tempo vuoi trascorrere nel parco.",
"Your private vehicle, English-speaking driver, all fuel and tolls, and hotel/accommodation pickup and drop-off in Split are included. Plitvice Lakes National Park entrance tickets are purchased separately at the park. We're happy to advise on current prices when you book.": "Sono inclusi il veicolo privato, l'autista che parla inglese, carburante e pedaggi, e il ritiro e il rientro presso il tuo hotel o alloggio a Spalato. I biglietti d'ingresso al Parco nazionale dei Laghi di Plitvice si acquistano a parte al parco. Quando prenoti, ti indichiamo volentieri i prezzi aggiornati.",
"Is this a private tour or a shared group tour?": "È un tour privato o un tour di gruppo condiviso?",
"This is a fully private excursion: just your group and your driver, with no other travellers sharing the vehicle. You set the pace once inside the park.": "È un'escursione completamente privata: solo il tuo gruppo e l'autista, senza altri viaggiatori nel veicolo. Nel parco decidi tu il ritmo.",
"How much walking is involved at Plitvice Lakes?": "Quanto si cammina ai Laghi di Plitvice?",
"The park is explored on foot via wooden boardwalks and trails, with routes ranging from around 2 to 8 kilometres depending on which route you choose. Trails are mostly flat with some gentle inclines, and electric boats and a park shuttle bus cover the longer stretches.": "Il parco si visita a piedi lungo passerelle di legno e sentieri, con percorsi da circa 2 a 8 chilometri a seconda di quello che scegli. I sentieri sono per lo più pianeggianti con qualche lieve salita, e battelli elettrici e trenini panoramici coprono i tratti più lunghi.",
"Can I book a return transfer separately, or is it always round trip?": "Posso prenotare solo l'andata o è sempre andata e ritorno?",
"Day trips are booked as a complete round trip. Your driver waits at the park and brings you back to Split the same day. If you only need a one-way transfer to Plitvice, see our regular airport transfer page instead.": "Le escursioni si prenotano sempre come andata e ritorno. L'autista ti aspetta al parco e ti riporta a Spalato in giornata. Se ti serve solo un transfer di sola andata per Plitvice, consulta invece la nostra pagina dei transfer standard.",
"Turquoise terraced lakes and waterfalls at Plitvice Lakes National Park": "Laghi turchesi a terrazze e cascate nel Parco nazionale dei Laghi di Plitvice",
"Split → Plitvice Lakes National Park": "Spalato → Parco nazionale dei Laghi di Plitvice",
"Private Day Trip to Plitvice Lakes": "Escursione privata ai Laghi di Plitvice",
"10–12 hrs": "10–12 ore",
"~140 km": "~140 km",
"Day Trip from Split": "Escursione da Spalato",
"Croatia's Most Famous National Park": "Il parco nazionale più famoso della Croazia",
"Plitvice Lakes National Park is Croatia's oldest and largest national park, and a UNESCO World Heritage Site since 1979. Sixteen terraced lakes, ranging from deep blue to vivid turquoise, cascade into one another through a series of waterfalls, all connected by wooden boardwalks and forest trails that wind through beech and fir woodland. It's a full day out from Split, around two and a half hours' drive each way, which is exactly why most visitors prefer a private day trip over trying to arrange it independently: an early departure beats the tour-bus crowds to the upper lakes, and a driver who knows the road means the long drive itself is comfortable rather than tiring. Because the park sits inland, well away from the coast, this is also one of the few day trips from Split that shows a completely different side of Croatia, dense forest, karst limestone, and water in every direction, a genuine change of scenery from the Dalmatian coastline.": "Il Parco nazionale dei Laghi di Plitvice è il parco nazionale più antico e più grande della Croazia, Patrimonio mondiale UNESCO dal 1979. Sedici laghi a terrazze, dal blu profondo al turchese intenso, si riversano l'uno nell'altro attraverso una serie di cascate, collegati da passerelle di legno e sentieri che attraversano boschi di faggi e abeti. Da Spalato è una giornata intera, circa due ore e mezza di strada per tratta, ed è proprio per questo che la maggior parte dei visitatori preferisce un'escursione privata all'organizzazione fai da te: partendo presto si arriva ai laghi superiori prima dei pullman, e un autista che conosce la strada rende il lungo viaggio comodo invece che faticoso. Poiché il parco si trova nell'entroterra, lontano dalla costa, è anche una delle poche escursioni da Spalato che mostra un volto completamente diverso della Croazia: foreste fitte, calcare carsico e acqua ovunque, un vero cambio di scenario rispetto alla costa dalmata.",
"Two Ways to Visit": "Due modi per visitarlo",
"Plitvice Lakes from Split": "I Laghi di Plitvice da Spalato",
"Private One-Way Transfer": "Transfer privato di sola andata",
"From €430": "Da 430 €",
"A direct private transfer from Split Airport or Split to Plitvice Lakes, with drop-off at the park entrance or your accommodation. Ideal if you're staying near the lakes or continuing to Zagreb.": "Un transfer privato diretto dall'aeroporto di Spalato o da Spalato ai Laghi di Plitvice, con arrivo all'ingresso del parco o al tuo alloggio. Ideale se alloggi vicino ai laghi o prosegui verso Zagabria.",
"Private Full-Day Trip": "Escursione privata di un giorno",
"A round trip from Split: your driver waits while you explore the lakes and brings you back the same day. 10–12 hours, fixed price for the whole day.": "Andata e ritorno da Spalato: l'autista ti aspetta mentre visiti i laghi e ti riporta indietro in giornata. 10–12 ore, prezzo fisso per tutta la giornata.",
"Not included: Plitvice Lakes National Park entrance tickets, purchased on arrival or in advance directly with the park (prices vary by season), and food/drinks inside the park.": "Non inclusi: i biglietti d'ingresso al Parco nazionale dei Laghi di Plitvice, da acquistare all'arrivo o in anticipo direttamente dal parco (i prezzi variano secondo la stagione), e cibo e bevande nel parco.",
"Book This Trip · €430": "Prenota l'escursione · 430 €",
"A Typical Day at Plitvice": "Una giornata tipo a Plitvice",
"Your driver collects you from your hotel or apartment at an early time to beat the tour-bus crowds to the park entrance.": "L'autista ti viene a prendere presto in hotel o in appartamento, per arrivare all'ingresso del parco prima dei pullman.",
"Arrival at Plitvice Lakes": "Arrivo ai Laghi di Plitvice",
"Explore the Lakes": "Alla scoperta dei laghi",
"Walk the wooden boardwalks past the Lower and Upper Lakes, cross the electric boat between the two halves of the park, and stop as often as you like for photos.": "Percorri le passerelle di legno lungo i Laghi inferiori e superiori, attraversa in battello elettrico tra le due parti del parco e fermati per le foto tutte le volte che vuoi.",
"Lunch Break": "Pausa pranzo",
"A short stop at one of the restaurants near the park entrance, or a picnic if you'd prefer, entirely up to you.": "Una breve sosta in uno dei ristoranti vicino all'ingresso del parco, o un picnic se preferisci: decidi tu.",
"Your driver is waiting at the agreed time for the drive back, with a short stop en route if you'd like one.": "L'autista ti aspetta all'orario concordato per il ritorno, con una breve sosta lungo la strada se lo desideri.",
"Back at your accommodation by early evening, with the rest of the day free.": "Di nuovo al tuo alloggio in prima serata, con il resto della giornata libero.",
"Day trips are booked as a complete round trip. Your driver waits at the park and brings you back to Split the same day. If you only need a one-way transfer to Plitvice, see our": "Le escursioni si prenotano sempre come andata e ritorno. L'autista ti aspetta al parco e ti riporta a Spalato in giornata. Se ti serve solo un transfer di sola andata per Plitvice, consulta invece la nostra",
"regular airport transfer page": "pagina dei transfer standard",
"instead.": ".",
}
JSR = {
"btn.dataset.label + ' · €' + price": "btn.dataset.label + ' · ' + price + ' €'",
"submitBtn.textContent = 'Sending...'": "submitBtn.textContent = 'Invio in corso...'",
"alert('Something went wrong sending your request. Please try again or contact us on WhatsApp.')": "alert('Si è verificato un errore durante l\\'invio della richiesta. Riprova o contattaci su WhatsApp.')",
}
