# Marina pages (phase 2)
FILES = ["aci-marina-split", "aci-marina-trogir", "marina-agana", "marina-baotic", "marina-dalmacija", "marina-frapa", "marina-kastela", "marina-kornati", "marina-mandalina"]
M = ["ACI Marina Split", "ACI Marina Trogir", "Marina Agana", "Marina Baotić", "Marina Dalmacija", "Marina Frapa", "Marina Kaštela", "Marina Kornati", "Marina Mandalina"]
T = {}
for f in FILES:
    T[f"About@@{f}.html"] = "Circa"
    T[f"private day trip@@{f}.html"] = "un'escursione privata di un giorno"
for en in M:
    a, la, pl = ("all'", "L'", "per l'") if en.startswith("ACI") else ("alla ", "La ", "per la ")
    T[f"Split Airport to {en} | Airport Split Transfer"] = f"Transfer dall'aeroporto di Spalato {a}{en} | Airport Split Transfer"
    T[f"How long is the drive from Split Airport to {en}?"] = f"Quanto dura il tragitto dall'aeroporto di Spalato {a}{en}?"
    T[f"How much does the transfer to {en} cost?"] = f"Quanto costa il transfer {pl}{en}?"
    T[f"Split Airport → {en}"] = f"Aeroporto di Spalato → {en}"
    T[f"Split Airport to {en}"] = f"Dall'aeroporto di Spalato {a}{en}"
    T[f"About {en}"] = f"{la}{en}"
for tm, km, tmi in [("30 min", "22 km", "30 min"), ("15 min", "8 km", "15 min"), ("25 min", "20 km", "25 min"), ("15 min", "10 km", "15 min"),
                    ("1 h 30 min", "135 km", "1 h 30 min"), ("35 min", "34 km", "35 min"), ("15–20 min", "12 km", "15–20 min"),
                    ("1 h 10 min", "100 km", "1 h 10 min"), ("55 min", "55 km", "55 min")]:
    T[f"Around {tm} in normal traffic, about {km}. On summer Saturdays, when the charter crews change, allow a little more."] = f"Circa {tmi} con traffico normale, per circa {km}. Il sabato d'estate, quando cambiano gli equipaggi dei charter, calcola un po' di più."
T.update({
"Private transfer from Split Airport to ACI Marina Split for charter crews: about 30 minutes, fixed price per vehicle, vans for up to 8 and meet and greet.": "Transfer privato dall'aeroporto di Spalato all'ACI Marina Split per equipaggi charter: circa 30 minuti, prezzo fisso per veicolo, van fino a 8 persone e accoglienza.",
"The price is per vehicle and fixed before you travel, with tolls, fuel and meet and greet included. Tap \"Get your fixed price\" and enter your flight to see the exact price for a sedan or a van. The marina is already filled in.": "Il prezzo è per veicolo e fissato prima del viaggio, con pedaggi, carburante e accoglienza inclusi. Tocca \"Calcola il prezzo fisso\" e inserisci il volo per vedere il prezzo esatto per una berlina o un van. La marina è già inserita.",
"Can you time the pickup around our charter check-in?": "Potete programmare il ritiro in base al check-in del charter?",
"Yes. Give us your flight number and check-in time when you book. We follow the flight, and if you land early we can stop on the way, for example to buy provisions.": "Sì. Quando prenoti, indicaci il numero di volo e l'orario del check-in. Seguiamo il volo e, se atterri presto, possiamo fermarci lungo la strada, per esempio per fare la cambusa.",
"We are eight people with a lot of luggage. Will one vehicle do?": "Siamo in otto con molti bagagli. Basta un veicolo?",
"Yes. The Renault Trafic takes up to 8 passengers and the Mercedes V-Class up to 7, both with room for sailing bags, so the whole crew travels together.": "Sì. Il Renault Trafic porta fino a 8 passeggeri e la Mercedes Classe V fino a 7, entrambi con spazio per le sacche da vela, così tutto l'equipaggio viaggia insieme.",
"Can we book the ride back to the airport at the end of the charter?": "Possiamo prenotare il ritorno in aeroporto a fine charter?",
"Yes. Choose \"Return\" in the form to book both legs together and get 5% off the total. We will suggest a pickup time based on your check-out and your flight.": "Sì. Scegli \"Andata e ritorno\" nel modulo per prenotare entrambe le tratte con il 5% di sconto sul totale. Ti proporremo un orario di ritiro in base al check-out e al volo.",
"ACI Marina Split is on the western side of Split's harbour, below Marjan hill and a short walk from the Riva and Diocletian's Palace.": "L'ACI Marina Split si trova sul lato occidentale del porto di Spalato, ai piedi della collina del Marjan e a pochi passi dalla Riva e dal Palazzo di Diocleziano.",
"Vans for crews of up to": "Van per equipaggi fino a",
"Getting to the marina": "Come arrivare alla marina",
"The marina is about 22 km from the airport, on the far side of the city. The drive usually takes around 30 minutes along the coast road and round the harbour. On summer Saturdays, traffic through Split can add a few minutes, and we allow for it in your pickup.": "La marina dista circa 22 km dall'aeroporto, dall'altra parte della città. Il viaggio lungo la strada costiera e attorno al porto dura di solito circa 30 minuti. Il sabato d'estate il traffico in città può aggiungere qualche minuto, e ne teniamo conto nell'orario di ritiro.",
"Most charter boats here change crews on Saturday. The old crew leaves in the morning and the new one usually boards in the afternoon, so Saturday is the busiest day on every road to the marinas. Tell us your flight and your check-in time and we plan the pickup around both. If you land hours before you can board, we can stop on the way for provisioning.": "Qui la maggior parte delle barche a noleggio cambia equipaggio il sabato. Il vecchio equipaggio sbarca la mattina e il nuovo di solito si imbarca nel pomeriggio, quindi il sabato è il giorno più trafficato su tutte le strade verso le marine. Indicaci il volo e l'orario del check-in e programmiamo il ritiro in base a entrambi. Se atterri ore prima dell'imbarco, possiamo fermarci lungo la strada per la cambusa.",
"Crews usually travel as six to eight people with soft bags and boxes of provisions. Rather than splitting into two taxis, one Mercedes V-Class (up to 7) or Renault Trafic (up to 8) takes everyone and the luggage, and the price is per vehicle, not per person.": "Gli equipaggi viaggiano di solito in sei-otto persone con sacche morbide e scatoloni di provviste. Invece di dividersi in due taxi, una Mercedes Classe V (fino a 7) o un Renault Trafic (fino a 8) porta tutti con i bagagli, e il prezzo è per veicolo, non a persona.",
"Tap the button above and add your flight. The marina is already filled in, and the price is fixed when you book.": "Tocca il pulsante qui sopra e aggiungi il volo. La marina è già inserita e il prezzo è fissato al momento della prenotazione.",
"Straight to the marina": "Dritti alla marina",
"No other passengers and no stops unless you ask. We drop you at reception or the charter office.": "Nessun altro passeggero e nessuna fermata, a meno che tu non la chieda. Ti lasciamo alla reception o all'ufficio della società di charter.",
"ACI Marina Split belongs to the ACI chain of marinas along the Croatian coast and is one of the busiest charter bases in the city. For a first or last night in Split it is hard to beat: the old town, Diocletian's Palace and the Riva are a short walk away, and the ferry port is just across the harbour. Many crews spend an evening in the old town before sailing out to Šolta, Brač or Hvar the next morning.": "L'ACI Marina Split fa parte della catena di marine ACI lungo la costa croata ed è una delle basi charter più trafficate della città. Per la prima o l'ultima notte a Spalato è difficile fare di meglio: il centro storico, il Palazzo di Diocleziano e la Riva sono a pochi passi, e il porto dei traghetti è proprio dall'altra parte del bacino. Molti equipaggi passano una serata in centro prima di salpare la mattina dopo verso Šolta, Brač o Hvar.",
"Heading somewhere else? See": "Diretto altrove? Scopri",
"all our routes from Split Airport": "tutti i nostri percorsi dall'aeroporto di Spalato",
", or add a": ", oppure aggiungi",
"before or after your charter.": "prima o dopo il charter.",
"Private transfer from Split Airport to ACI Marina Trogir on Čiovo: about 15 minutes, fixed price per vehicle, vans for crews of up to 8, meet and greet.": "Transfer privato dall'aeroporto di Spalato all'ACI Marina Trogir su Čiovo: circa 15 minuti, prezzo fisso per veicolo, van per equipaggi fino a 8 persone, accoglienza.",
"ACI Marina Trogir is on Čiovo island, across a narrow channel from Trogir's UNESCO-listed old town and only minutes from Split Airport.": "L'ACI Marina Trogir si trova sull'isola di Čiovo, oltre uno stretto canale dal centro storico UNESCO di Trogir e a pochi minuti dall'aeroporto di Spalato.",
"8 km": "8 km",
"This is one of the shortest marina transfers on the coast: about 8 km, usually around 15 minutes, over the bridge from the mainland onto Čiovo. The bridges around Trogir can slow down on Saturday afternoons, so we leave a little margin on changeover day.": "È uno dei transfer per marina più brevi della costa: circa 8 km, di solito circa 15 minuti, attraverso il ponte dalla terraferma a Čiovo. Il sabato pomeriggio i ponti di Trogir possono rallentare, quindi nel giorno del cambio equipaggi lasciamo un po' di margine.",
"ACI Marina Trogir faces the old town across the Trogir channel, so the cathedral, the Kamerlengo fortress and the waterfront restaurants are a short walk over the bridge. Charter crews like it because the berths are sheltered and the islands are close: Šolta and the Drvenik islands are a short sail away, and Split's harbour is just to the east. With the airport so near, it also suits crews landing late on Friday or flying out early on the last Saturday.": "L'ACI Marina Trogir guarda il centro storico dall'altra parte del canale di Trogir, quindi cattedrale, fortezza del Camerlengo e ristoranti sul lungomare sono a pochi passi oltre il ponte. Gli equipaggi la apprezzano perché gli ormeggi sono riparati e le isole vicine: Šolta e le isole Drvenik sono a breve navigazione, e il porto di Spalato è subito a est. Con l'aeroporto così vicino, è ideale anche per chi atterra tardi il venerdì o riparte presto l'ultimo sabato.",
"Private transfer from Split Airport to Marina Agana in the village of Marina: about 25 minutes, fixed price per vehicle, vans for up to 8, meet and greet.": "Transfer privato dall'aeroporto di Spalato alla Marina Agana nel paese di Marina: circa 25 minuti, prezzo fisso per veicolo, van fino a 8 persone, accoglienza.",
"Marina Agana sits in a sheltered bay in the village of Marina, west of Trogir: a quieter charter base within easy reach of Split Airport.": "La Marina Agana si trova in una baia riparata nel paese di Marina, a ovest di Trogir: una base charter più tranquilla, facilmente raggiungibile dall'aeroporto di Spalato.",
"The marina is about 20 km from the airport. The drive usually takes around 25 minutes, past Trogir and along the coast towards Vinišće and Marina, with the last stretch running beside the bay.": "La marina dista circa 20 km dall'aeroporto. Il viaggio dura di solito circa 25 minuti, oltre Trogir e lungo la costa verso Vinišće e Marina, con l'ultimo tratto che costeggia la baia.",
"Marina Agana is smaller and calmer than the big marinas around Split and Trogir, set at the head of a deep, protected bay. The village of Marina has a few restaurants and shops along the waterfront, and Trogir's old town is a short drive back towards the airport. Crews often choose it for a relaxed start: less Saturday bustle and quick access to open water and the islands to the west.": "La Marina Agana è più piccola e tranquilla delle grandi marine attorno a Spalato e Trogir, in fondo a una baia profonda e protetta. Il paese di Marina ha qualche ristorante e negozio sul lungomare, e il centro storico di Trogir è a breve distanza in direzione dell'aeroporto. Gli equipaggi la scelgono spesso per una partenza rilassata: meno confusione il sabato e accesso rapido al mare aperto e alle isole a ovest.",
"Private transfer from Split Airport to Marina Baotić in Seget Donji: about 15 minutes, fixed price per vehicle, vans for crews of up to 8, meet and greet.": "Transfer privato dall'aeroporto di Spalato alla Marina Baotić a Seget Donji: circa 15 minuti, prezzo fisso per veicolo, van per equipaggi fino a 8 persone, accoglienza.",
"Marina Baotić is in Seget Donji, just west of Trogir, and is one of the largest charter bases near Split Airport.": "La Marina Baotić si trova a Seget Donji, appena a ovest di Trogir, ed è una delle più grandi basi charter vicino all'aeroporto di Spalato.",
"10 km": "10 km",
"The marina is about 10 km from the airport, and the drive usually takes around 15 minutes along the coast road past Trogir. Changeover Saturdays bring a lot of charter traffic to this stretch, so we plan the pickup with that in mind.": "La marina dista circa 10 km dall'aeroporto e il viaggio lungo la strada costiera oltre Trogir dura di solito circa 15 minuti. Il sabato del cambio equipaggi questo tratto è molto trafficato, e programmiamo il ritiro tenendone conto.",
"Marina Baotić is a large, modern marina on the Trogir Riviera. Many charter fleets are based here, and from spring to autumn it is busy every Saturday. Trogir's old town is a short drive or a pleasant walk along the coast, which makes it easy to spend the evening before departure there. From the marina, the Drvenik islands, Šolta and the open water towards Hvar and Vis are all an easy first day's sail.": "La Marina Baotić è una marina grande e moderna sulla Riviera di Trogir. Qui hanno base molte flotte charter e da primavera ad autunno è piena ogni sabato. Il centro storico di Trogir è a breve distanza in auto o con una piacevole passeggiata lungo la costa, quindi è facile trascorrervi la sera prima della partenza. Dalla marina, le isole Drvenik, Šolta e il mare aperto verso Hvar e Vis sono tutti una facile prima giornata di navigazione.",
"Private transfer from Split Airport to D-Marin Dalmacija in Sukošan: about 1 h 30 min on the A1, fixed price per vehicle, vans for up to 8, meet and greet.": "Transfer privato dall'aeroporto di Spalato alla D-Marin Dalmacija a Sukošan: circa 1 h 30 min sull'A1, prezzo fisso per veicolo, van fino a 8 persone, accoglienza.",
"Marina Dalmacija (D-Marin Dalmacija) in Sukošan, south of Zadar, is one of the largest marinas on the Adriatic and a major charter base for the Kornati islands.": "La Marina Dalmacija (D-Marin Dalmacija) a Sukošan, a sud di Zadar, è una delle marine più grandi dell'Adriatico e un'importante base charter per le isole Kornati.",
"135 km": "135 km",
"1 h 30 min": "1 h 30 min",
"The marina is about 135 km from Split Airport, and the drive usually takes around 1 hour 30 minutes on the A1 motorway towards Zadar. Zadar Airport is closer to Sukošan, but many crews fly into Split for the wider choice of flights, and a private transfer makes the longer drive easy.": "La marina dista circa 135 km dall'aeroporto di Spalato e il viaggio sull'autostrada A1 verso Zadar dura di solito circa 1 ora e 30 minuti. L'aeroporto di Zadar è più vicino a Sukošan, ma molti equipaggi volano su Spalato per la maggiore scelta di voli, e un transfer privato rende facile il viaggio più lungo.",
"Marina Dalmacija is one of the biggest marinas in Croatia, with a very large charter fleet and full services on site. It is the classic starting point for sailing the Kornati islands and the Zadar archipelago. Zadar's old town, with the Sea Organ and the Greeting to the Sun, is fifteen to twenty minutes away by car if you want an evening ashore before you sail.": "La Marina Dalmacija è una delle marine più grandi della Croazia, con una flotta charter molto ampia e tutti i servizi in loco. È il classico punto di partenza per navigare tra le Kornati e l'arcipelago di Zadar. Il centro storico di Zadar, con l'Organo marino e il Saluto al Sole, è a quindici-venti minuti d'auto se vuoi passare una serata a terra prima di salpare.",
"Private transfer from Split Airport to Marina Frapa in Rogoznica: about 35 minutes, fixed price per vehicle, vans for crews of up to 8, meet and greet.": "Transfer privato dall'aeroporto di Spalato alla Marina Frapa a Rogoznica: circa 35 minuti, prezzo fisso per veicolo, van per equipaggi fino a 8 persone, accoglienza.",
"Split Airport to Marina Frapa, Rogoznica | Airport Split Transfer": "Transfer dall'aeroporto di Spalato alla Marina Frapa, Rogoznica | Airport Split Transfer",
"Marina Frapa sits in a sheltered bay at Rogoznica, on the coast between Trogir and Šibenik, and is one of the most awarded marinas on the Adriatic.": "La Marina Frapa si trova in una baia riparata a Rogoznica, sulla costa tra Trogir e Šibenik, ed è una delle marine più premiate dell'Adriatico.",
"34 km": "34 km",
"35 min": "35 min",
"The marina is about 34 km north of the airport. The drive usually takes around 35 minutes, mostly on the coast road past Trogir and Seget, then a short turn off towards Rogoznica. The marina has its own entrance before the town centre, and our drivers know it, which matters on a busy Saturday.": "La marina si trova circa 34 km a nord dell'aeroporto. Il viaggio dura di solito circa 35 minuti, per lo più sulla strada costiera oltre Trogir e Seget, poi una breve deviazione verso Rogoznica. La marina ha un ingresso proprio prima del centro del paese, e i nostri autisti lo conoscono: un dettaglio che conta in un sabato affollato.",
"Marina Frapa fills the quieter of Rogoznica's two bays, with restaurants and a boatyard on site, and it has collected more \"best marina\" awards than almost any other on the Adriatic. The small old town of Rogoznica, on its narrow isthmus, is a short walk away. From here crews head north to the Šibenik islands and the Kornati, or south towards Šolta and Hvar. Staying in town instead? See": "La Marina Frapa occupa la più tranquilla delle due baie di Rogoznica, con ristoranti e cantiere in loco, e ha raccolto più premi come \"migliore marina\" di quasi ogni altra sull'Adriatico. Il piccolo centro storico di Rogoznica, sul suo stretto istmo, è a pochi passi. Da qui gli equipaggi puntano a nord verso le isole di Šibenik e le Kornati, o a sud verso Šolta e Hvar. Alloggi in paese? Vedi i",
"transfers to Rogoznica": "transfer per Rogoznica",
"Private transfer from Split Airport to Marina Kaštela in Kaštel Gomilica: about 15 to 20 minutes, fixed price per vehicle, vans for up to 8, meet and greet.": "Transfer privato dall'aeroporto di Spalato alla Marina Kaštela a Kaštel Gomilica: circa 15–20 minuti, prezzo fisso per veicolo, van fino a 8 persone, accoglienza.",
"Marina Kaštela is in Kaštel Gomilica on the bay between Split and Trogir, one of the closest charter marinas to Split Airport.": "La Marina Kaštela si trova a Kaštel Gomilica, nella baia tra Spalato e Trogir, ed è una delle marine charter più vicine all'aeroporto di Spalato.",
"15–20 min": "15–20 min",
"The marina is about 12 km from the airport, and the drive usually takes 15 to 20 minutes along the main road above the Kaštela villages. The airport sits at the western end of the same bay, so this is one of the quickest ways from the plane to the boat.": "La marina dista circa 12 km dall'aeroporto e il viaggio lungo la strada principale sopra i paesi di Kaštela dura di solito 15–20 minuti. L'aeroporto si trova all'estremità occidentale della stessa baia: è uno dei modi più rapidi per passare dall'aereo alla barca.",
"Marina Kaštela is one of the larger marinas around Split and a base for several charter fleets. It is in Kaštel Gomilica, near the little Kaštilac fortress that appeared as Braavos in Game of Thrones, with cafés and a seafront promenade a short walk away. Split is about twenty minutes by road, and the sail out of the bay towards Šolta and Brač is short and sheltered.": "La Marina Kaštela è una delle marine più grandi attorno a Spalato e base di diverse flotte charter. Si trova a Kaštel Gomilica, vicino alla piccola fortezza del Kaštilac comparsa come Braavos nel Trono di Spade, con caffè e lungomare a pochi passi. Spalato è a una ventina di minuti in auto, e l'uscita dalla baia verso Šolta e Brač è breve e riparata.",
"Split Airport to Marina Kornati, Biograd | Airport Split Transfer": "Transfer dall'aeroporto di Spalato alla Marina Kornati, Biograd | Airport Split Transfer",
"Private transfer from Split Airport to Marina Kornati in Biograd na Moru: about 1 h 10 min, fixed price per vehicle, vans for crews of up to 8.": "Transfer privato dall'aeroporto di Spalato alla Marina Kornati a Biograd na Moru: circa 1 h 10 min, prezzo fisso per veicolo, van per equipaggi fino a 8 persone.",
"Marina Kornati is in Biograd na Moru, roughly halfway between Split and Zadar, and is one of the largest charter bases in Croatia.": "La Marina Kornati si trova a Biograd na Moru, circa a metà strada tra Spalato e Zadar, ed è una delle più grandi basi charter della Croazia.",
"The marina is about 100 km north of the airport. Most of the drive is on the motorway, so it usually takes around 1 h 10 min, a little longer on summer Saturdays when charter traffic peaks. It is a longer ride than to most marinas near Split, so tell us if you would like to stop for provisions on the way.": "La marina si trova circa 100 km a nord dell'aeroporto. Gran parte del viaggio è in autostrada, quindi dura di solito circa 1 h 10 min, un po' di più il sabato d'estate quando il traffico dei charter è al massimo. È un viaggio più lungo rispetto alla maggior parte delle marine vicino a Spalato, quindi dicci se vuoi fermarti per la cambusa lungo la strada.",
"Marina Kornati sits right by the centre of Biograd na Moru, with cafés and shops a short walk away and the island of Pašman just across the channel. It is the closest large marina to Kornati National Park and Telašćica Nature Park, which is why so many sailing weeks start here. Staying in town instead? See": "La Marina Kornati si trova proprio accanto al centro di Biograd na Moru, con caffè e negozi a pochi passi e l'isola di Pašman dall'altra parte del canale. È la grande marina più vicina al Parco nazionale delle Kornati e al Parco naturale di Telašćica, ed è per questo che tante settimane in barca partono da qui. Alloggi in città? Vedi i",
"transfers to Biograd na Moru": "transfer per Biograd na Moru",
"Private transfer from Split Airport to D-Marin Mandalina in Šibenik: about 55 minutes, fixed price per vehicle, vans for crews of up to 8, meet and greet.": "Transfer privato dall'aeroporto di Spalato alla D-Marin Mandalina a Šibenik: circa 55 minuti, prezzo fisso per veicolo, van per equipaggi fino a 8 persone, accoglienza.",
"Marina Mandalina (D-Marin Mandalina) is on the Mandalina peninsula in Šibenik, a base for charter yachts and superyachts close to the Kornati islands and Krka.": "La Marina Mandalina (D-Marin Mandalina) si trova sulla penisola di Mandalina a Šibenik, base per yacht a noleggio e superyacht vicino alle Kornati e a Krka.",
"The marina is about 55 km north of the airport. The drive usually takes around 55 minutes, mostly on the motorway towards Šibenik and then down to the Mandalina peninsula on the south side of the city.": "La marina si trova circa 55 km a nord dell'aeroporto. Il viaggio dura di solito circa 55 minuti, per lo più in autostrada verso Šibenik e poi fino alla penisola di Mandalina, sul lato sud della città.",
"Marina Mandalina is one of the main marinas in Šibenik, with berths for everything from charter yachts to superyachts. The old town and the UNESCO-listed Cathedral of St James are a short drive away, and the marina is a natural starting point for the Kornati National Park and the Krka river, which boats can sail up towards Skradin. If you arrive a day early, the old town is well worth an evening.": "La Marina Mandalina è una delle principali marine di Šibenik, con ormeggi per ogni tipo di imbarcazione, dagli yacht a noleggio ai superyacht. Il centro storico e la Cattedrale di San Giacomo, patrimonio UNESCO, sono a breve distanza, e la marina è il punto di partenza naturale per il Parco nazionale delle Kornati e il fiume Krka, che si può risalire in barca fino a Skradin. Se arrivi un giorno prima, il centro storico merita una serata.",
})
