# Blog posts, batch 3 (phase 2): taxi prices; Split taxi/bus/transfer
T = {
"Split Airport Taxi Prices (2026 Guide) | Airport Split Transfer": "Prezzi dei taxi dall'aeroporto di Spalato (2026) | Airport Split Transfer",
"How much is a taxi from Split Airport to Split?": "Quanto costa un taxi dall'aeroporto di Spalato a Spalato?",
"A metered rank taxi usually costs €35–50 to Split city centre. A fixed-price private transfer costs around €50 for a car or €65–70 for a van.": "Un taxi al posteggio con tassametro costa di solito 35–50 € fino al centro di Spalato. Un transfer privato a prezzo fisso costa circa 50 € in auto o 65–70 € in van.",
"Do Split Airport taxis take cards?": "I taxi dell'aeroporto di Spalato accettano carte?",
"Many do, but not all, ask before you get in. With our private transfers you can pay by card or cash to the driver.": "Molti sì, ma non tutti: chiedi prima di salire. Con i nostri transfer privati puoi pagare l'autista con carta o in contanti.",
"Is a private transfer more expensive than a taxi?": "Un transfer privato costa più di un taxi?",
"On most routes it costs about the same as a rank taxi, but the price is fixed before you land and includes meet & greet, tolls and child seats.": "Sulla maggior parte dei percorsi costa più o meno come un taxi al posteggio, ma il prezzo è fisso prima dell'atterraggio e include accoglienza, pedaggi e seggiolini.",
"\"How much is a taxi from Split Airport?\" is the first thing most visitors search, and the honest answer is: it depends on which kind of taxi. There are three, the metered taxis waiting at the rank, ride-hailing apps, and fixed-price private transfers, and they price the same journey in very different ways.": "\"Quanto costa un taxi dall'aeroporto di Spalato?\" è la prima cosa che cercano quasi tutti, e la risposta onesta è: dipende da quale taxi. Ce ne sono tre tipi, i taxi con tassametro al posteggio, le app di ride-hailing e i transfer privati a prezzo fisso, e fanno pagare lo stesso viaggio in modi molto diversi.",
"Rank taxis: metered": "Taxi al posteggio: tassametro",
"Taxis at the rank outside arrivals run on the meter. To Split city centre, expect roughly": "I taxi al posteggio fuori dagli arrivi usano il tassametro. Fino al centro di Spalato calcola circa",
". Longer routes are harder to predict because the fare depends on the company, the route the driver takes, and traffic. Always confirm the price or ask for an estimate before you set off, and ask for a receipt.": ". I percorsi più lunghi sono più difficili da prevedere, perché la tariffa dipende dalla compagnia, dal percorso scelto dall'autista e dal traffico. Conferma sempre il prezzo o chiedi una stima prima di partire, e chiedi la ricevuta.",
"Ride-hailing apps: surge pricing": "App di ride-hailing: tariffe dinamiche",
"Apps like Bolt operate around Split and can be cheaper than the rank outside peak times. In July and August, surge pricing can push fares above the rank taxis, and availability late at night or very early in the morning is not guaranteed. Most app cars are sedans, so groups with luggage may need two.": "App come Bolt funzionano a Spalato e fuori dalle ore di punta possono costare meno del posteggio. A luglio e agosto le tariffe dinamiche possono superare quelle dei taxi, e la disponibilità a tarda notte o all'alba non è garantita. Quasi tutte le auto delle app sono berline, quindi ai gruppi con bagagli possono servirne due.",
"Private transfers: fixed per vehicle": "Transfer privati: prezzo fisso per veicolo",
"A private transfer is priced per vehicle before you book. The price doesn't change with traffic, delays or the time of day, and it already includes tolls, fuel, meet & greet in arrivals and child seats on request. These are typical one-way prices with us:": "Un transfer privato ha un prezzo per veicolo stabilito prima della prenotazione. Il prezzo non cambia con traffico, ritardi o orario, e include già pedaggi, carburante, accoglienza agli arrivi e seggiolini su richiesta. Questi sono i nostri prezzi tipici di sola andata:",
"Route from Split Airport": "Percorso dall'aeroporto di Spalato",
"Drive time": "Durata",
"Car (1–4)": "Auto (1–4)",
"Van (up to 8)": "Van (fino a 8)",
"~7 km": "~7 km", "~20 km": "~20 km", "~27 km": "~27 km", "~45 km": "~45 km", "~65 km": "~65 km", "~89 km": "~89 km", "~230 km": "~230 km",
"Split centre / ferry port": "Centro di Spalato / porto",
"25–30 min": "25–30 min",
"3–3.5 h": "3–3,5 h",
"The exact price depends on your address and shows instantly in the": "Il prezzo esatto dipende dal tuo indirizzo e appare subito nel",
"booking form": "modulo di prenotazione",
". A return trip booked together gets 5% off.": ". Andata e ritorno prenotati insieme hanno il 5% di sconto.",
"Which one is cheapest?": "Qual è il più economico?",
"For one or two people going into Split outside peak season, an app ride can be the cheapest car option. For everyone else the gap closes quickly: a rank taxi to Split costs about the same as a transfer, and on longer routes a fixed price removes the risk of a meter running through summer traffic on the coast road. If you want the fixed-price option, see our": "Per una o due persone dirette a Spalato fuori stagione, un'app può essere l'opzione in auto più economica. Per tutti gli altri la differenza si riduce subito: un taxi al posteggio per Spalato costa più o meno come un transfer, e sui percorsi più lunghi un prezzo fisso elimina il rischio di un tassametro che corre nel traffico estivo della costiera. Se vuoi l'opzione a prezzo fisso, vedi il nostro",
"Split Airport taxi at a fixed price": "taxi a prezzo fisso dall'aeroporto di Spalato",
"The biggest saving is for groups. A van for up to eight people to Makarska costs around €185 in total: about €23 per person, only a little more than the bus, but from the arrivals hall to your door.": "Il risparmio più grande è per i gruppi. Un van fino a otto persone per Makarska costa circa 185 € in totale: circa 23 € a testa, poco più dell'autobus, ma dalla sala arrivi fino alla tua porta.",
"Things that can add to the price": "Cosa può far salire il prezzo",
"Rank taxis:": "Taxi al posteggio:",
"luggage surcharges, night rates and detours in traffic.": "supplementi per i bagagli, tariffe notturne e deviazioni nel traffico.",
"Apps:": "App:",
"surge pricing and cancellations during busy periods.": "tariffe dinamiche e cancellazioni nei periodi di punta.",
"Private transfers:": "Transfer privati:",
"extra stops or route changes asked for on the day. With us these are always agreed before the ride, never added at the end.": "soste extra o cambi di percorso richiesti il giorno stesso. Con noi si concordano sempre prima del viaggio, mai aggiunti alla fine.",
"Frequently Asked Questions": "Domande frequenti",
"Split Airport to Split: Taxi, Bus or Transfer | Airport Split Transfer": "Dall'aeroporto a Spalato: taxi, autobus o transfer | Airport Split Transfer",
"How far is Split Airport from Split city centre?": "Quanto dista l'aeroporto di Spalato dal centro?",
"About 20 km. The drive takes 25–30 minutes in normal traffic and longer on summer afternoons.": "Circa 20 km. Il viaggio dura 25–30 minuti con traffico normale, di più nei pomeriggi d'estate.",
"What is the cheapest way from Split Airport to Split?": "Qual è il modo più economico per andare dall'aeroporto a Spalato?",
"The local city bus (line 37) is the cheapest, followed by the airport shuttle at roughly €8–10 per person. Both are slower than a taxi or transfer and don't take you to your door.": "Il più economico è l'autobus urbano (linea 37), seguito dalla navetta aeroportuale a circa 8–10 € a persona. Entrambi sono più lenti di un taxi o di un transfer e non ti portano fino alla porta.",
"How much is a private transfer from Split Airport to Split?": "Quanto costa un transfer privato dall'aeroporto a Spalato?",
"Around €50 for a car with up to 4 passengers and around €65–70 for a van with up to 8, per vehicle. The booking form shows the exact fixed price for your address.": "Circa 50 € per un'auto fino a 4 passeggeri e circa 65–70 € per un van fino a 8, per veicolo. Il modulo di prenotazione mostra il prezzo fisso esatto per il tuo indirizzo.",
"Split Airport is not actually in Split. It sits in Kaštela, about 20 km west of the old town, so every arrival starts with the same question: how do I get into the city? There are three realistic answers, the airport shuttle, a taxi from the rank, or a private transfer booked in advance, and each one is the right choice for somebody.": "L'aeroporto di Spalato in realtà non è a Spalato. Si trova a Kaštela, circa 20 km a ovest del centro storico, quindi ogni arrivo comincia con la stessa domanda: come arrivo in città? Le risposte realistiche sono tre, la navetta aeroportuale, un taxi al posteggio o un transfer privato prenotato in anticipo, e ognuna è la scelta giusta per qualcuno.",
"Option 1: the airport shuttle bus": "Opzione 1: la navetta aeroportuale",
"The official airport shuttle leaves from right outside arrivals and runs to Split main bus station, which sits next to the ferry port and a five-minute walk from Diocletian's Palace. Departures are timed around arriving flights, the trip takes 30–40 minutes, and a ticket costs roughly €8–10 per person. Fares and timetables change from season to season, so check before you fly.": "La navetta ufficiale parte proprio davanti agli arrivi e va alla stazione principale degli autobus di Spalato, accanto al porto e a cinque minuti a piedi dal Palazzo di Diocleziano. Le partenze sono coordinate con gli arrivi dei voli, il viaggio dura 30–40 minuti e il biglietto costa circa 8–10 € a persona. Tariffe e orari cambiano da una stagione all'altra, quindi controlla prima di partire.",
"Best for:": "Ideale per:",
"solo travellers and couples with light luggage who are staying in or near the old town, or catching a ferry.": "chi viaggia da solo e coppie con pochi bagagli che alloggiano nel centro storico o nelle vicinanze, o che devono prendere un traghetto.",
"There is also the local city bus (line 37), which stops on the main road outside the airport. It is very cheap but slow, close to an hour to Split, and it does not end in the centre, so it rarely makes sense with suitcases.": "C'è anche l'autobus urbano (linea 37), che ferma sulla strada principale fuori dall'aeroporto. È molto economico ma lento, quasi un'ora fino a Spalato, e non arriva in centro, quindi con le valigie raramente ha senso.",
"Option 2: a taxi from the rank": "Opzione 2: un taxi al posteggio",
"The taxi rank is directly outside the terminal. Taxis are metered, and a ride to the centre usually lands somewhere between €35 and €50 depending on the company, traffic and time of day. Ride-hailing apps also work at the airport, but prices rise sharply with summer demand and cars can be scarce late at night.": "Il posteggio dei taxi è proprio davanti al terminal. I taxi hanno il tassametro e una corsa fino al centro costa di solito tra 35 e 50 €, a seconda della compagnia, del traffico e dell'orario. In aeroporto funzionano anche le app, ma d'estate i prezzi salgono molto e a tarda notte le auto possono scarseggiare.",
"travellers who didn't book anything and don't want to wait for the next shuttle.": "chi non ha prenotato nulla e non vuole aspettare la navetta successiva.",
"The catch is uncertainty. You don't know the final price until you arrive, and on a busy July afternoon the queue for a car can be longer than the drive itself. Groups of five or more may also find that the next car in line is a sedan.": "Il problema è l'incertezza. Non conosci il prezzo finale finché non arrivi, e in un affollato pomeriggio di luglio la coda per un'auto può durare più del viaggio. I gruppi di cinque o più persone possono anche scoprire che la prossima auto in coda è una berlina.",
"Option 3: a private transfer": "Opzione 3: un transfer privato",
"A pre-booked transfer costs about the same as a rank taxi, but the price is fixed before you land. With us, Split Airport to Split city centre is around": "Un transfer prenotato costa più o meno come un taxi al posteggio, ma il prezzo è fisso prima dell'atterraggio. Con noi, dall'aeroporto al centro di Spalato costa circa",
"€50 in a car for up to 4 people": "50 € in auto fino a 4 persone",
"and around": "e circa",
"€65–70 in a van for up to 8": "65–70 € in van fino a 8 persone",
"per vehicle, not per person, with tolls, fuel and meet & greet included. Read more on our": "per veicolo, non a persona, con pedaggi, carburante e accoglienza inclusi. Scopri di più nella pagina",
"page.": ".",
"Your driver tracks your flight, waits in the arrivals hall with a name sign and takes you to your exact address. That matters in Split more than in most cities: much of the old town is pedestrian-only, and a driver who knows the nearest drop-off point saves you dragging suitcases across marble streets.": "L'autista segue il tuo volo, ti aspetta nella sala arrivi con un cartello con il tuo nome e ti porta all'indirizzo esatto. A Spalato questo conta più che altrove: gran parte del centro storico è pedonale, e un autista che conosce il punto di arrivo più vicino ti evita di trascinare le valigie sulle strade di pietra.",
"families, groups, late arrivals, and anyone staying outside the bus station area.": "famiglie, gruppi, arrivi a tarda sera e chiunque alloggi lontano dalla stazione degli autobus.",
"Quick comparison": "Confronto rapido",
"Option": "Opzione",
"Price": "Prezzo",
"Notes": "Note",
"Airport shuttle": "Navetta aeroportuale",
"~€8–10 per person": "~8–10 € a persona",
"30–40 min": "30–40 min",
"Bus station only": "Solo stazione autobus",
"Taxi from the rank": "Taxi al posteggio",
"~€35–50 per car": "~35–50 € per auto",
"Metered, queue in summer": "Tassametro, coda d'estate",
"Private transfer": "Transfer privato",
"~€50 car / ~€65 van": "~50 € auto / ~65 € van",
"Fixed price, door to door": "Prezzo fisso, porta a porta",
"For two people with backpacks heading to the ferry, the shuttle is hard to beat. For a family of four with luggage, the shuttle already costs €32–40 and still leaves you at the bus station, at that point a private transfer to the door costs only a little more.": "Per due persone con lo zaino dirette al traghetto, la navetta è difficile da battere. Per una famiglia di quattro con bagagli, la navetta costa già 32–40 € e ti lascia comunque alla stazione degli autobus: a quel punto un transfer privato fino alla porta costa solo poco di più.",
}
