# Blog posts, batch 4 (phase 2): early morning; how to book; Dubrovnik worth it
T = {
"Early Morning Transfer to Split Airport | Airport Split Transfer": "Transfer all'alba per l'aeroporto di Spalato | Airport Split Transfer",
"Is there a bus to Split Airport early in the morning?": "C'è un autobus per l'aeroporto di Spalato la mattina presto?",
"Service at very early hours is limited. Check the first airport shuttle departure against your flight time before you rely on it.": "Nelle primissime ore il servizio è limitato. Prima di contarci, confronta la prima partenza della navetta con l'orario del tuo volo.",
"How early should I get to Split Airport?": "Con quanto anticipo devo arrivare all'aeroporto di Spalato?",
"About 2 hours before departure in summer, when morning security queues are longest.": "D'estate circa 2 ore prima della partenza, quando le code ai controlli del mattino sono più lunghe.",
"Do you charge extra for early morning transfers?": "Fate pagare di più i transfer all'alba?",
"No. The price is the same at any time of day, with no night rate.": "No. Il prezzo è lo stesso a qualsiasi ora, senza tariffa notturna.",
"Many flights out of Split leave between 6 and 8 in the morning, especially budget airlines and charter flights on changeover days. That means a check-in around 4–5am, and the hardest part of the trip is often getting to the airport before the day has started.": "Molti voli da Spalato partono tra le 6 e le 8 del mattino, soprattutto low cost e charter nei giorni di cambio. Significa un check-in verso le 4–5, e la parte più difficile del viaggio è spesso arrivare in aeroporto prima che la giornata sia cominciata.",
"Why early mornings are tricky": "Perché le partenze all'alba sono complicate",
"Buses aren't running yet,": "Gli autobus non circolano ancora,",
"or only a few are. Check the first airport shuttle departure against your flight time before you rely on it.": "o ne passano pochi. Prima di contarci, confronta la prima partenza della navetta con l'orario del tuo volo.",
"Ride-hailing apps are unreliable": "Le app di ride-hailing non sono affidabili",
"at 4am. There may be no cars nearby, or a driver may accept and then cancel.": "alle 4 del mattino. Potrebbero non esserci auto vicine, o un autista potrebbe accettare e poi cancellare.",
"Street taxis are rare": "I taxi per strada sono rari",
"outside the centre of Split, and almost non-existent in smaller towns along the coast.": "fuori dal centro di Spalato, e quasi inesistenti nei paesi più piccoli lungo la costa.",
"How early should you leave?": "Quanto presto partire?",
"Aim to be at the airport": "Cerca di essere in aeroporto",
"2 hours before departure": "2 ore prima della partenza",
"in summer. Split Airport's terminal is modern but busy in peak season, and security queues build quickly in the morning wave of departures. Then add the drive time:": "d'estate. Il terminal dell'aeroporto di Spalato è moderno ma affollato in alta stagione, e le code ai controlli crescono in fretta con l'ondata di partenze del mattino. Poi aggiungi il tempo di viaggio:",
"Split city centre: 25–30 minutes": "Centro di Spalato: 25–30 minuti",
"Trogir: 10–15 minutes": "Trogir: 10–15 minuti",
"Podstrana: around 30 minutes": "Podstrana: circa 30 minuti",
"Omiš: around 45 minutes": "Omiš: circa 45 minuti",
"Makarska: around 1 hour 20 minutes": "Makarska: circa 1 ora e 20 minuti",
"Roads are quiet at that hour, so drive times are usually reliable. The risk is the time before the car arrives, not the drive.": "A quell'ora le strade sono tranquille, quindi i tempi di viaggio sono di solito affidabili. Il rischio è il tempo prima che arrivi l'auto, non il viaggio.",
"Book the day before, not on the morning": "Prenota il giorno prima, non la mattina stessa",
"A pre-booked transfer is the calm option. The driver is at your door at the agreed time, and the price is the same at 4am as at noon. There's no night rate. When you book, give us your flight time and we'll suggest a pickup time. If anything changes, you can move or cancel the booking free of charge.": "Un transfer prenotato è l'opzione più tranquilla. L'autista è alla tua porta all'ora concordata, e il prezzo è lo stesso alle 4 del mattino come a mezzogiorno. Non c'è tariffa notturna. Quando prenoti, indicaci l'orario del volo e ti proporremo un orario di ritiro. Se cambia qualcosa, puoi spostare o cancellare la prenotazione gratuitamente.",
"Tip: if you book your arrival and departure together as a return trip, you get 5% off both ways and never have to think about the return at the end of your holiday.": "Consiglio: se prenoti arrivo e partenza insieme come andata e ritorno, hai il 5% di sconto su entrambe le tratte e non devi pensare al ritorno a fine vacanza.",
"Checklist for the night before": "Checklist per la sera prima",
"Double-check the pickup time and address in your booking confirmation.": "Ricontrolla orario e indirizzo di ritiro nella conferma della prenotazione.",
"Tell us if your accommodation has a hard-to-find entrance or gate.": "Avvisaci se il tuo alloggio ha un ingresso o un cancello difficile da trovare.",
"Check your flight status in case of a time change.": "Controlla lo stato del volo in caso di cambio d'orario.",
"Have your passport and boarding pass ready. You'll be sleepy.": "Tieni pronti passaporto e carta d'imbarco. Avrai sonno.",
"How to Book a Reliable Split Airport Transfer | Airport Split Transfer": "Come prenotare un transfer affidabile dall'aeroporto di Spalato | Airport Split Transfer",
"What happens if my flight to Split is delayed?": "Cosa succede se il mio volo per Spalato è in ritardo?",
"We track your flight number and your driver adjusts the pickup time automatically. There is no extra charge for reasonable delays.": "Seguiamo il tuo volo e l'autista adegua automaticamente l'orario di ritiro. Per i ritardi ragionevoli non c'è alcun costo aggiuntivo.",
"Can I cancel my Split Airport transfer?": "Posso cancellare il mio transfer dall'aeroporto di Spalato?",
"Yes, cancellation is free at any time before pickup, by email, phone or WhatsApp.": "Sì, la cancellazione è gratuita in qualsiasi momento prima del ritiro, via e-mail, telefono o WhatsApp.",
"How do I pay for the transfer?": "Come pago il transfer?",
"You pay the driver on the day, by card or cash, unless another payment method was agreed in advance.": "Paghi l'autista il giorno stesso, con carta o in contanti, salvo diverso metodo concordato in anticipo.",
"Most airport transfers go fine. The ones that don't usually fail in the same few ways: the driver isn't there, the price changes, or the car is too small for the group. Here's what to check before you book, so yours is one of the ones that go fine.": "La maggior parte dei transfer aeroportuali va bene. Quelli che vanno male di solito falliscono per gli stessi motivi: l'autista non c'è, il prezzo cambia o l'auto è troppo piccola per il gruppo. Ecco cosa controllare prima di prenotare, perché il tuo sia uno di quelli che vanno bene.",
"1. A fixed price, per vehicle": "1. Un prezzo fisso per veicolo",
"You should know the full price before you pay anything. It should be per vehicle, not per person, and include tolls, fuel and waiting in arrivals. Watch out for low headline prices that add \"airport fees\" or luggage charges later.": "Devi conoscere il prezzo completo prima di pagare qualsiasi cosa. Deve essere per veicolo, non a persona, e includere pedaggi, carburante e attesa agli arrivi. Attenzione ai prezzi bassi in vetrina che poi aggiungono \"tasse aeroportuali\" o supplementi bagagli.",
"2. Flight tracking": "2. Monitoraggio del volo",
"Your booking should ask for a flight number. A company that tracks flights will adjust the pickup if you land late, without charging you for the delay. If a booking form doesn't ask for your flight number, ask what happens when the flight is late.": "La prenotazione dovrebbe chiedere il numero di volo. Una società che segue i voli sposterà il ritiro se atterri in ritardo, senza farti pagare l'attesa. Se un modulo non chiede il numero di volo, chiedi cosa succede quando il volo è in ritardo.",
"3. Meet & greet inside arrivals": "3. Accoglienza dentro la sala arrivi",
"The driver should wait in the arrivals hall with a name sign, not in the car park. At Split Airport that saves you finding a car in a busy summer car park with your luggage.": "L'autista dovrebbe aspettarti nella sala arrivi con un cartello con il tuo nome, non nel parcheggio. All'aeroporto di Spalato questo ti evita di cercare un'auto in un parcheggio estivo affollato con i bagagli.",
"4. The right vehicle for your group": "4. Il veicolo giusto per il gruppo",
"Four people with four large suitcases don't fit comfortably in most taxis. Look for a company that asks how many passengers you are and offers a van for bigger groups. We use a Škoda Superb for up to 4 and vans for up to 8.": "Quattro persone con quattro valigie grandi non stanno comode nella maggior parte dei taxi. Cerca una società che chieda quanti passeggeri siete e offra un van per i gruppi più grandi. Noi usiamo una Škoda Superb fino a 4 persone e van fino a 8.",
"5. Free child seats": "5. Seggiolini gratuiti",
"Children in Croatia must travel in a suitable child seat. A good transfer company provides them free of charge when you ask during booking.": "In Croazia i bambini devono viaggiare su un seggiolino adeguato. Una buona società di transfer li fornisce gratis se li chiedi alla prenotazione.",
"6. Free cancellation": "6. Cancellazione gratuita",
"Plans change. Check that you can cancel or change the booking without a fee: ideally right up to pickup, not just 48 hours before.": "I piani cambiano. Verifica di poter cancellare o modificare la prenotazione senza penali: idealmente fino al ritiro, non solo fino a 48 ore prima.",
"7. A way to reach a real person": "7. Un modo per parlare con una persona vera",
"Before you fly, make sure you have a phone number and WhatsApp for the company, not just an email. If your flight is diverted or your phone dies, you need to reach someone quickly.": "Prima di partire, assicurati di avere un numero di telefono e un WhatsApp della società, non solo un'e-mail. Se il volo viene dirottato o il telefono si scarica, devi poter raggiungere qualcuno in fretta.",
"8. Real reviews": "8. Recensioni vere",
"Look for reviews on Google, not just testimonials on the company's own website, and check how the company answers when something went wrong.": "Cerca recensioni su Google, non solo testimonianze sul sito della società, e guarda come risponde quando qualcosa è andato storto.",
"How booking works with us": "Come si prenota con noi",
"Enter your pickup and drop-off addresses in the": "Inserisci l'indirizzo di partenza e di arrivo nel",
"and see the fixed price for each vehicle instantly.": "e vedi subito il prezzo fisso per ogni veicolo.",
"Add your flight number, number of passengers and any child seats.": "Aggiungi numero di volo, numero di passeggeri ed eventuali seggiolini.",
"Get a confirmation by email. Pay the driver by card or cash on the day.": "Ricevi la conferma via e-mail. Paghi l'autista con carta o in contanti il giorno stesso.",
"Your driver tracks your flight and waits in arrivals with your name.": "L'autista segue il tuo volo e ti aspetta agli arrivi con il tuo nome.",
"Questions before you book? Message us on": "Domande prima di prenotare? Scrivici su",
"we usually reply within minutes.": ", di solito rispondiamo in pochi minuti.",
"Split Airport to Dubrovnik: Is It Worth It? | Airport Split Transfer": "Dall'aeroporto di Spalato a Dubrovnik: conviene? | Airport Split Transfer",
"About 3 to 3.5 hours, depending on traffic and the route.": "Circa 3–3,5 ore, a seconda del traffico e del percorso.",
"Do I need a passport to drive from Split to Dubrovnik?": "Serve il passaporto per andare in auto da Spalato a Dubrovnik?",
"The route over the Pelješac Bridge stays in Croatia, but keep passports with you in case the driver uses the road through Neum in Bosnia and Herzegovina.": "Il percorso sul ponte di Pelješac resta in Croazia, ma tieni con te i documenti nel caso l'autista passi per Neum, in Bosnia ed Erzegovina.",
"How much is a transfer from Split Airport to Dubrovnik?": "Quanto costa un transfer dall'aeroporto di Spalato a Dubrovnik?",
"Around €380 for a car with up to 4 passengers and around €455 for a van with up to 8, per vehicle.": "Circa 380 € per un'auto fino a 4 passeggeri e circa 455 € per un van fino a 8, per veicolo.",
"Many travellers heading to Dubrovnik end up flying into Split instead: because flights are cheaper, there are more routes, or they want to see both cities. The question is whether the 230 km in between is a problem or part of the trip. (For the route itself and places to stop, see our": "Molti viaggiatori diretti a Dubrovnik finiscono per atterrare a Spalato: perché i voli costano meno, ci sono più collegamenti o vogliono vedere entrambe le città. La domanda è se i 230 km in mezzo siano un problema o parte del viaggio. (Per il percorso e i posti dove fermarsi, vedi la nostra",
"Split to Dubrovnik route guide": "guida al percorso Spalato–Dubrovnik",
"When it makes sense": "Quando conviene",
"The flight price difference is big.": "La differenza di prezzo del volo è grande.",
"For a family, saving €100 or more per ticket on flights into Split easily covers the drive.": "Per una famiglia, risparmiare 100 € o più a biglietto sui voli per Spalato copre facilmente il viaggio in auto.",
"You want to see Split too.": "Vuoi vedere anche Spalato.",
"Fly in, spend a few days in Split, then transfer to Dubrovnik and fly home from there.": "Atterri, passi qualche giorno a Spalato, poi ti trasferisci a Dubrovnik e riparti da lì.",
"There's no direct flight": "Non c'è un volo diretto",
"from your city to Dubrovnik on your dates, especially outside summer.": "dalla tua città a Dubrovnik nelle tue date, soprattutto fuori stagione.",
"If you're flying in only to go straight to Dubrovnik for a short stay, and a direct flight to Dubrovnik costs about the same, flying direct is simpler.": "Se atterri solo per andare subito a Dubrovnik per un breve soggiorno, e un volo diretto per Dubrovnik costa più o meno uguale, volare direttamente è più semplice.",
"How long does it take?": "Quanto ci vuole?",
"By car, 3 to 3.5 hours. The motorway covers the first part; the rest follows the coast. Since the Pelješac Bridge opened in 2022, the route can avoid the short stretch through Bosnia and Herzegovina at Neum. Keep passports handy anyway, drivers sometimes choose the Neum road depending on traffic.": "In auto 3–3,5 ore. La prima parte è in autostrada, il resto segue la costa. Da quando nel 2022 è stato aperto il ponte di Pelješac, il percorso può evitare il breve tratto in Bosnia ed Erzegovina a Neum. Tieni comunque i documenti a portata di mano: a seconda del traffico gli autisti a volte scelgono la strada per Neum.",
"Your options compared": "Le opzioni a confronto",
"Bus": "Autobus",
"~€20–30 per person": "~20–30 € a persona",
"4.5–5 h": "4,5–5 h",
"Change in Split first": "Cambio a Spalato",
"Catamaran (summer)": "Catamarano (estate)",
"~€40–60 per person": "~40–60 € a persona",
"4–5 h": "4–5 h",
"From Split port, stops at islands": "Dal porto di Spalato, fermate sulle isole",
"~€380 car / ~€455 van": "~380 € auto / ~455 € van",
"Door to door, stops on request": "Porta a porta, soste su richiesta",
"Bus and ferry fares change by season; check with the operators before you travel.": "Le tariffe di autobus e traghetti cambiano con la stagione; verifica con gli operatori prima di partire.",
"What a transfer costs": "Quanto costa un transfer",
"A private transfer costs around": "Un transfer privato costa circa",
"€380 in a car for up to 4": "380 € in auto fino a 4 persone",
"€455 in a van for up to 8": "455 € in van fino a 8 persone",
", per vehicle. For a group of eight that's about €57 per person: not far from the catamaran, but directly from the arrivals hall to your hotel door in Dubrovnik, with no connection to make.": ", per veicolo. Per un gruppo di otto sono circa 57 € a testa: non lontano dal catamarano, ma direttamente dalla sala arrivi alla porta dell'hotel a Dubrovnik, senza coincidenze.",
"It also turns the drive into part of the holiday. With a private driver you can stop for photos, coffee, or lunch in Ston for oysters. Tell us what you'd like when booking and we'll plan the time.": "In più il viaggio diventa parte della vacanza. Con un autista privato puoi fermarti per foto, un caffè o un pranzo a base di ostriche a Ston. Dicci cosa desideri quando prenoti e organizzeremo i tempi.",
"The verdict": "Il verdetto",
"For couples on a budget, the bus is fine. For families and groups with luggage, a private transfer is usually the most comfortable way: and when the flight savings are big, it often pays for itself.": "Per le coppie con un budget ridotto l'autobus va benissimo. Per famiglie e gruppi con bagagli un transfer privato è di solito il modo più comodo, e quando il risparmio sui voli è grande spesso si ripaga da solo.",
}
