# Blog posts, batch 5 (phase 2): Makarska options; Omiš; Podstrana
T = {
"Split Airport to Makarska: Transport Options | Airport Split Transfer": "Dall'aeroporto di Spalato a Makarska: i mezzi | Airport Split Transfer",
"Is there a direct bus from Split Airport to Makarska?": "C'è un autobus diretto dall'aeroporto di Spalato a Makarska?",
"Not usually. Most travellers take the airport shuttle to Split bus station and change to a coastal bus to Makarska.": "Di solito no. La maggior parte dei viaggiatori prende la navetta fino alla stazione degli autobus di Spalato e cambia con un autobus costiero per Makarska.",
"How long does it take to get from Split Airport to Makarska?": "Quanto ci vuole dall'aeroporto di Spalato a Makarska?",
"About 1 hour 20 minutes by car. By bus via Split, allow 3 hours or more including the change.": "In auto circa 1 ora e 20 minuti. In autobus via Spalato, calcola 3 ore o più compreso il cambio.",
"How much is a transfer from Split Airport to Makarska?": "Quanto costa un transfer dall'aeroporto di Spalato a Makarska?",
"Around €155 for a car with up to 4 passengers and around €185 for a van with up to 8, per vehicle, fixed in advance.": "Circa 155 € per un'auto fino a 4 passeggeri e circa 185 € per un van fino a 8, per veicolo, fissati in anticipo.",
"Makarska is about 89 km south of Split Airport, roughly 1 hour 20 minutes by car. There's no direct public transport from the terminal, so the choice is really about how many changes you're willing to make with your luggage. Here are the four options, from cheapest to most direct. (For the drive itself and the towns along the Riviera, see our": "Makarska si trova circa 89 km a sud dell'aeroporto di Spalato, circa 1 ora e 20 minuti in auto. Non ci sono mezzi pubblici diretti dal terminal, quindi la scelta dipende da quanti cambi sei disposto a fare con i bagagli. Ecco le quattro opzioni, dalla più economica alla più diretta. (Per il viaggio e le località della Riviera, vedi la nostra",
"Split to Makarska route guide": "guida al percorso Spalato–Makarska",
"1. Bus via Split": "1. Autobus via Spalato",
"Take the airport shuttle to Split main bus station (30–40 minutes), then a coastal bus to Makarska. Coastal buses run often in summer and take around 1.5–2 hours. Together with waiting time, plan on 3 hours or more door to door, and around €20 per person for both tickets.": "Prendi la navetta fino alla stazione principale degli autobus di Spalato (30–40 minuti), poi un autobus costiero per Makarska. D'estate gli autobus costieri sono frequenti e impiegano circa 1,5–2 ore. Con le attese, calcola 3 ore o più porta a porta e circa 20 € a persona per entrambi i biglietti.",
"It's the cheapest option for one person travelling light. It's also the slowest, and in July and August buses toward the Riviera can be full.": "È l'opzione più economica per una persona con pochi bagagli. È anche la più lenta, e a luglio e agosto gli autobus verso la Riviera possono essere pieni.",
"2. Rental car": "2. Auto a noleggio",
"Car hire desks are in the terminal, and the coast road is easy to drive. The problem is Makarska itself: parking in the centre is limited and expensive in summer, and many apartments have no space. If you plan to stay by the beach most of the week, you may pay for a car that sits parked.": "I banchi del noleggio sono nel terminal e la strada costiera è facile da guidare. Il problema è Makarska: d'estate il parcheggio in centro è scarso e caro, e molti appartamenti non hanno posto auto. Se pensi di stare in spiaggia quasi tutta la settimana, potresti pagare un'auto che resta ferma.",
"3. Taxi from the rank": "3. Taxi al posteggio",
"A metered taxi works, but on a 90 km route through summer traffic the final price is hard to predict. Always agree an estimate before you set off.": "Un taxi con tassametro funziona, ma su 90 km nel traffico estivo il prezzo finale è difficile da prevedere. Concorda sempre una stima prima di partire.",
"4. Private transfer": "4. Transfer privato",
"A fixed-price transfer from the arrivals hall to your door costs around": "Un transfer a prezzo fisso dalla sala arrivi alla tua porta costa circa",
"€155 in a car for up to 4": "155 € in auto fino a 4 persone",
"€185 in a van for up to 8": "185 € in van fino a 8 persone",
". For a family of four that's €39 per person; for a group of eight in a van, about €23 each: close to the bus fare, without the change in Split.": ". Per una famiglia di quattro sono 39 € a persona; per un gruppo di otto in van, circa 23 € a testa: vicino al prezzo dell'autobus, senza il cambio a Spalato.",
"Bus via Split": "Autobus via Spalato",
"~€20 per person": "~20 € a persona",
"3 h+": "3 h+",
"Two buses, change in Split": "Due autobus, cambio a Spalato",
"Rental car": "Auto a noleggio",
"Varies + parking": "Variabile + parcheggio",
"Parking in Makarska is hard": "Parcheggiare a Makarska è difficile",
"Rank taxi": "Taxi al posteggio",
"Metered": "Tassametro",
"Price depends on traffic": "Il prezzo dipende dal traffico",
"~€155 car / ~€185 van": "~155 € auto / ~185 € van",
"Fixed, door to door": "Fisso, porta a porta",
"Summer Saturdays": "I sabati d'estate",
"Saturday is changeover day for holiday rentals along the whole Riviera, and the coast road through Omiš slows down in both directions. If you book with your flight number, your driver plans for that. On the way back, we'll suggest a pickup time with enough buffer for Saturday traffic.": "Il sabato è il giorno di cambio degli affitti su tutta la Riviera, e la strada costiera che passa per Omiš rallenta in entrambe le direzioni. Se prenoti indicando il numero di volo, l'autista ne tiene conto. Per il ritorno ti proporremo un orario di ritiro con un margine sufficiente per il traffico del sabato.",
"Split Airport to Omiš: Transfer Guide | Airport Split Transfer": "Dall'aeroporto di Spalato a Omiš: guida al transfer | Airport Split Transfer",
"How far is Omiš from Split Airport?": "Quanto dista Omiš dall'aeroporto di Spalato?",
"About 45 km, which is around 45 minutes by car in normal traffic.": "Circa 45 km, cioè circa 45 minuti in auto con traffico normale.",
"How much is a transfer from Split Airport to Omiš?": "Quanto costa un transfer dall'aeroporto di Spalato a Omiš?",
"Around €90 for a car with up to 4 passengers and around €130 for a van with up to 8, per vehicle.": "Circa 90 € per un'auto fino a 4 passeggeri e circa 130 € per un van fino a 8, per veicolo.",
"Can you drive me to an apartment above Omiš or in the Cetina valley?": "Potete portarmi a un appartamento sopra Omiš o nella valle della Cetina?",
"Yes. Give us the exact address when booking and the driver will confirm the access and drop-off point in advance.": "Sì. Indicaci l'indirizzo esatto quando prenoti e l'autista confermerà in anticipo l'accesso e il punto di arrivo.",
"Omiš sits where the Cetina river cuts through the mountains into the sea, about 45 km from Split Airport. The drive takes around 45 minutes, and it's one of the most scenic arrivals on the coast, the last few kilometres run along the sea with the cliffs of the canyon ahead of you.": "Omiš sorge dove il fiume Cetina attraversa le montagne e sfocia nel mare, a circa 45 km dall'aeroporto di Spalato. Il viaggio dura circa 45 minuti ed è uno degli arrivi più panoramici della costa: gli ultimi chilometri corrono lungo il mare con le pareti del canyon davanti.",
"From the airport, the road bypasses Split and joins the coast road (the D8) past Stobreč and Podstrana. After that it's a straight run along the sea into Omiš. In summer, traffic through Podstrana and the Omiš bridge is the main thing that slows you down, especially on Saturday afternoons.": "Dall'aeroporto la strada aggira Spalato e si immette sulla costiera (la D8) oltre Stobreč e Podstrana. Poi si va dritti lungo il mare fino a Omiš. D'estate a rallentare è soprattutto il traffico a Podstrana e sul ponte di Omiš, in particolare il sabato pomeriggio.",
"By bus": "In autobus",
"There's no direct bus from the airport. Take the airport shuttle into Split main bus station and change to a coastal bus heading south, most of them stop in Omiš. Allow around two hours door to door, and more in peak season when buses fill up.": "Non c'è un autobus diretto dall'aeroporto. Prendi la navetta fino alla stazione principale degli autobus di Spalato e cambia con un autobus costiero verso sud: la maggior parte ferma a Omiš. Calcola circa due ore porta a porta, di più in alta stagione quando gli autobus si riempiono.",
"By private transfer": "Con un transfer privato",
"€90 in a car for up to 4": "90 € in auto fino a 4 persone",
"€130 in a van for up to 8": "130 € in van fino a 8 persone",
", fixed per vehicle. Your driver waits in arrivals and takes you straight to your accommodation.": ", fisso per veicolo. L'autista ti aspetta agli arrivi e ti porta direttamente all'alloggio.",
"That matters in Omiš more than in most places. Many apartments are not in the town itself but up the hill, in villages like Duće, Ruskamen or Lokva Rogoznica along the coast, or up the Cetina valley. These addresses can be hard to find, and some aren't on any bus route. Put your exact address in the booking, and the driver will check the access before the day.": "A Omiš questo conta più che altrove. Molti appartamenti non sono in paese ma in collina, in frazioni lungo la costa come Duće, Ruskamen o Lokva Rogoznica, oppure su nella valle della Cetina. Questi indirizzi possono essere difficili da trovare e alcuni non sono serviti da alcun autobus. Indica l'indirizzo esatto nella prenotazione e l'autista verificherà l'accesso prima del giorno del viaggio.",
"Things to do once you're there": "Cosa fare una volta arrivati",
"Rafting and canyoning": "Rafting e canyoning",
"on the Cetina: the most popular activities, running from spring to early autumn.": "sulla Cetina: le attività più richieste, dalla primavera all'inizio dell'autunno.",
"Zipline": "Zipline",
"over the Cetina canyon.": "sopra il canyon della Cetina.",
"The fortresses": "Le fortezze",
"Mirabella and Fortica above the town, with views over the river mouth.": "Mirabella e Fortica sopra il paese, con vista sulla foce del fiume.",
"The beaches": "Le spiagge",
"the long sandy beach right in town is rare on this coast and great for children.": ": la lunga spiaggia di sabbia in paese è una rarità su questa costa ed è perfetta per i bambini.",
"Many activity companies meet in town, so it's easy to go without a car once you've arrived.": "Molti operatori danno appuntamento in paese, quindi una volta arrivati è facile fare a meno dell'auto.",
"Split Airport to Podstrana Taxi Price (2026) | Airport Split Transfer": "Prezzo del taxi dall'aeroporto di Spalato a Podstrana (2026) | Airport Split Transfer",
"How much is a taxi from Split Airport to Podstrana?": "Quanto costa un taxi dall'aeroporto di Spalato a Podstrana?",
"A private transfer costs around €55 for a car with up to 4 passengers and around €75 for a van with up to 8. Rank taxis are metered, so the price depends on traffic.": "Un transfer privato costa circa 55 € per un'auto fino a 4 passeggeri e circa 75 € per un van fino a 8. I taxi al posteggio hanno il tassametro, quindi il prezzo dipende dal traffico.",
"About 30 minutes. The road bypasses Split city centre.": "Circa 30 minuti. La strada aggira il centro di Spalato.",
"Do you drive to Le Méridien Lav?": "Portate i clienti al Le Méridien Lav?",
"Yes, we drop guests at the hotel reception. Just enter the hotel name as your drop-off address.": "Sì, lasciamo gli ospiti alla reception dell'hotel. Basta inserire il nome dell'hotel come destinazione.",
"Podstrana is the long seaside stretch just south of Split, between Stobreč and Omiš. From the airport it's about 27 km and around 30 minutes by car, because the road bypasses the city centre instead of going through it.": "Podstrana è il lungo tratto sul mare appena a sud di Spalato, tra Stobreč e Omiš. Dall'aeroporto sono circa 27 km e circa 30 minuti in auto, perché la strada aggira il centro invece di attraversarlo.",
"How much is a taxi to Podstrana?": "Quanto costa un taxi per Podstrana?",
"A metered taxi from the airport rank is priced by distance and traffic, so the final price is only known when you arrive. A private transfer with us is fixed before you land: around": "Un taxi con tassametro dal posteggio dell'aeroporto si paga in base a distanza e traffico, quindi il prezzo finale si conosce solo all'arrivo. Un transfer privato con noi è fisso prima dell'atterraggio: circa",
"€55 in a car for up to 4": "55 € in auto fino a 4 persone",
"€75 in a van for up to 8": "75 € in van fino a 8 persone",
", per vehicle. That includes tolls, fuel, meet & greet in arrivals and child seats on request. Book a return trip together and you get 5% off both ways. See how our": ", per veicolo. Sono inclusi pedaggi, carburante, accoglienza agli arrivi e seggiolini su richiesta. Prenotando insieme andata e ritorno hai il 5% di sconto su entrambe le tratte. Scopri come funziona il nostro servizio",
"service works.": ".",
"The exact price depends on where in Podstrana you're staying, the area is almost ten kilometres long, and shows instantly in the": "Il prezzo esatto dipende da dove alloggi a Podstrana, che si estende per quasi dieci chilometri, e compare subito nel",
"Is there a bus?": "C'è un autobus?",
"Local buses from Split run along the coast through Podstrana, but there's no direct connection from the airport. You would take the shuttle into Split first, then a local bus back out: usually well over an hour with a change, and not practical with suitcases.": "Gli autobus urbani da Spalato percorrono la costa attraverso Podstrana, ma non c'è un collegamento diretto dall'aeroporto. Dovresti prendere prima la navetta per Spalato e poi un autobus per tornare indietro: di solito ben più di un'ora con un cambio, poco pratico con le valigie.",
"Hotels in Podstrana": "Hotel a Podstrana",
"Podstrana is home to some of the largest resort hotels near Split, including": "A Podstrana si trovano alcuni dei resort più grandi vicino a Spalato, tra cui il",
"Le Méridien Lav": "Le Méridien Lav",
". Drivers know the hotel entrances and drop you at reception, not on the main road. If you're in a private apartment, the side streets down to the sea can be narrow and steep. Put your exact address in the booking and we'll confirm the best drop-off point.": ". Gli autisti conoscono gli ingressi degli hotel e ti lasciano alla reception, non sulla strada principale. Se alloggi in un appartamento privato, le stradine che scendono al mare possono essere strette e ripide. Indica l'indirizzo esatto nella prenotazione e confermeremo il punto di arrivo migliore.",
"Staying in Podstrana, visiting Split": "Alloggiare a Podstrana, visitare Spalato",
"Podstrana is a good base: quieter than Split, with long beaches, and only 15–20 minutes from the old town. Local buses run to Split regularly. For an evening out, a taxi back is easy to find in Split, but agree the price first.": "Podstrana è una buona base: più tranquilla di Spalato, con lunghe spiagge e a soli 15–20 minuti dal centro storico. Gli autobus urbani per Spalato sono frequenti. Per una serata fuori, a Spalato è facile trovare un taxi per il ritorno, ma concorda prima il prezzo.",
}
