# Prices +10% on 2026-10-07 (minimum fares unchanged): the English
# segments whose euro amounts changed, with the same change in the translation.
T = {
'A metered rank taxi usually costs €35–50 to Split city centre. A fixed-price private transfer costs around €55 for a car or €70–75 for a van.': 'Un taxi al posteggio con tassametro costa di solito 35–50 € fino al centro di Spalato. Un transfer privato a prezzo fisso costa circa 55 € in auto o 70–75 € in van.',
'The biggest saving is for groups. A van for up to eight people to Makarska costs around €205 in total: about €26 per person, only a little more than the bus, but from the arrivals hall to your door.': "Il risparmio più grande è per i gruppi. Un van fino a otto persone per Makarska costa circa 205 € in totale: circa 26 € a testa, poco più dell'autobus, ma dalla sala arrivi fino alla tua porta.",
'Around €125 for a car with up to 4 passengers and around €150 for a van with up to 8, per vehicle.': "Circa 125 € per un'auto fino a 4 passeggeri e circa 150 € per un van fino a 8, per veicolo.",
'€125 in a car for up to 4': '125 € in auto fino a 4 persone',
'€150 in a van for up to 8': '150 € in van fino a 8 persone',
", per vehicle. For a family of four, that's about €31 per person, from the arrivals hall to your door.": ', per veicolo. Per una famiglia di quattro sono circa 31 € a persona, dalla sala arrivi alla tua porta.',
'Around €415 for a car with up to 4 passengers and around €500 for a van with up to 8, per vehicle.': "Circa 415 € per un'auto fino a 4 passeggeri e circa 500 € per un van fino a 8, per veicolo.",
'~€415 car / ~€500 van': '~415 € auto / ~500 € van',
'€415 in a car for up to 4': '415 € in auto fino a 4 persone',
'€500 in a van for up to 8': '500 € in van fino a 8 persone',
", per vehicle. For a group of eight that's about €63 per person: not far from the catamaran, but directly from the arrivals hall to your hotel door in Dubrovnik, with no connection to make.": ", per veicolo. Per un gruppo di otto sono circa 63 € a testa: non lontano dal catamarano, ma direttamente dalla sala arrivi alla porta dell'hotel a Dubrovnik, senza coincidenze.",
'Around €170 for a car with up to 4 passengers and around €205 for a van with up to 8, per vehicle, fixed in advance.': "Circa 170 € per un'auto fino a 4 passeggeri e circa 205 € per un van fino a 8, per veicolo, fissati in anticipo.",
'€170 in a car for up to 4': '170 € in auto fino a 4 persone',
'€205 in a van for up to 8': '205 € in van fino a 8 persone',
". For a family of four that's €43 per person; for a group of eight in a van, about €26 each: close to the bus fare, without the change in Split.": ". Per una famiglia di quattro sono 43 € a persona; per un gruppo di otto in van, circa 26 € a testa: vicino al prezzo dell'autobus, senza il cambio a Spalato.",
'~€170 car / ~€205 van': '~170 € auto / ~205 € van',
'Around €100 for a car with up to 4 passengers and around €140 for a van with up to 8, per vehicle.': "Circa 100 € per un'auto fino a 4 passeggeri e circa 140 € per un van fino a 8, per veicolo.",
'€100 in a car for up to 4': '100 € in auto fino a 4 persone',
'€140 in a van for up to 8': '140 € in van fino a 8 persone',
'A private transfer costs around €60 for a car with up to 4 passengers and around €85 for a van with up to 8. Rank taxis are metered, so the price depends on traffic.': "Un transfer privato costa circa 60 € per un'auto fino a 4 passeggeri e circa 85 € per un van fino a 8. I taxi al posteggio hanno il tassametro, quindi il prezzo dipende dal traffico.",
'€60 in a car for up to 4': '60 € in auto fino a 4 persone',
'€85 in a van for up to 8': '85 € in van fino a 8 persone',
'Around €55 for a car with up to 4 passengers and around €70–75 for a van with up to 8, per vehicle. The booking form shows the exact fixed price for your address.': "Circa 55 € per un'auto fino a 4 passeggeri e circa 70–75 € per un van fino a 8, per veicolo. Il modulo di prenotazione mostra il prezzo fisso esatto per il tuo indirizzo.",
'€55 in a car for up to 4 people': '55 € in auto fino a 4 persone',
'€70–75 in a van for up to 8': '70–75 € in van fino a 8 persone',
'~€55 car / ~€70 van': '~55 € auto / ~70 € van',
'The Renault Trafic takes up to 8 passengers and 8 suitcases, and the Mercedes V-Class up to 7 with 7 suitcases. You pay for the vehicle, not per seat, so the fuller it is, the less each person pays. A group of eight going from the airport to Makarska pays about €26 each.': "Il Renault Trafic porta fino a 8 passeggeri e 8 valigie, la Mercedes Classe V fino a 7 con 7 valigie. Si paga il veicolo, non il posto, quindi più è pieno e meno paga ciascuno. Un gruppo di otto dall'aeroporto a Makarska paga circa 26 € a testa.",
'Book This Trip · €280': "Prenota l'escursione · 280 €",
'From €475': 'Da 475 €',
'Book This Trip · €475': "Prenota l'escursione · 475 €",
'Both a private one-way transfer from Split Airport to Plitvice Lakes and a private full-day trip with return to Split start from €475. For a one-way transfer, the exact price depends on your pickup and drop-off address. Enter both in our booking form to see an instant, fixed price for the Sedan or for the Business Van/Van: tolls, fuel and meet-and-greet at arrivals are always included.': "Sia il transfer privato di sola andata dall'aeroporto di Spalato ai Laghi di Plitvice sia l'escursione privata di un giorno con rientro a Spalato partono da 475 €. Per il transfer di sola andata il prezzo esatto dipende dall'indirizzo di partenza e di arrivo. Inseriscili entrambi nel modulo di prenotazione e vedrai subito il prezzo fisso per la berlina o per il van: pedaggi, carburante e accoglienza agli arrivi sono sempre inclusi.",
}
